#!/bin/bash

#Delete Logs
rm -f /var/log/openvpn.log-*
rm -f /var/log/php8.*-fpm.log.*
rm -f /var/log/sonata_recordings.log-*
rm -f /var/log/vitalpbx/lets_encrypt-*.log
rm -f /var/log/vitalpbx/wa_inbound_*.log
rm -f /var/log/vitalpbx/sms_webhook_*.log
find /var/log/vitalpbx/ -name "log_*.log" -type f -mtime +7 -delete
rm -f /var/log/messages.*
rm -f /var/log/mail.log.*
rm -f /var/log/kern.log.*
rm -f /var/log/fail2ban.log.*
rm -f /var/log/auth.log.*
rm -f /var/log/alternatives.log.*
rm -f /var/log/syslog.*
find /var/log/asterisk/ -name "full.*" -type f -mtime +7 -delete
find /var/log/asterisk/ -name "full-*" -type f -mtime +7 -delete
echo '' > /var/log/mail.log
echo '' > /var/log/syslog
echo '' > /var/log/vitalpbx/authentications.log
echo '' > /var/log/asterisk/full
echo '' > /var/log/asterisk/fail2ban
rm -f /var/log/vitalpbx/maintenance-*.log
rm -f /var/log/vitalpbx/phonebook_access.log

#Clean Journal
journalctl --rotate
journalctl --vacuum-time=1s

#Clean Postfix Queue
postsuper -d ALL
