#!/bin/sh

# This code is the property of VitalPBX LLC Company
# License: Proprietary
# Date: 30-Jul-2020
# Run the VitalPBX environment. It runs in VitalPBX post installation

dir=${0%/*}

set -e

$dir/generate_maint_key
$dir/apply_migrations
$dir/php_ini
$dir/odbc_ini
$dir/config_web_server

$dir/build_firewall
$dir/configure_tenants
$dir/vitalpbx "optimizeMariaDB"
$dir/vitalpbx "optimizeNginxSettings"
$dir/vitalpbx "optimizePHPFPM"
$dir/vitalpbx "optimizeServerSettings"
$dir/build_firewall_blacklists >/dev/null 2>&1 &
