#!/bin/sh

# This code is the property of VitalPBX LLC Company
# License: Proprietary
# Date: 24-Nov-2020
# Run VitalPBX scripts for updating system configurations

dir=${0%/*}

set -e

$dir/generate_maint_key
$dir/apply_migrations
$dir/php_ini
$dir/config_web_server
$dir/configure_tenants
$dir/vitalpbx "generateBrandingCSS"
$dir/whitelist_migration
$dir/clean_server > /dev/null 2>&1 &
$dir/vitalpbx "checkLicense" > /dev/null 2>&1 &
