/** Generate the extension boundary from the same validator used by the desktop. */
import fs from "node:fs/promises";
import ts from "typescript";
const source = await fs.readFile(new URL("../../src/coworker/browserCompanion/protocol.ts", import.meta.url), "utf8");
const pure = source.slice(source.indexOf("export function safeUrl"));
const output = "// Generated by scripts/browser-companion/schema.mjs --write; do not edit.\n" + ts.transpileModule(pure, {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const file = new URL("../../browser-companion/schema.js", import.meta.url);
if (process.argv.includes("--write")) await fs.writeFile(file, output);
else if (await fs.readFile(file,"utf8") !== output) throw Error("Browser schema is stale; run schema.mjs --write");
