use ombutel;

insert ignore into `ombu_notification_templates` (`name`, `from_email`, `from_name`, `subject`, `email_body`) values(
    'call_analysis_report',
    null,
    null,
    'Call Analysis Report',
    '<div style="max-width: 600px; background-color: #fdfdfd; padding: 20px; margin: 0 auto; border-radius: 8px; border: 1px solid #ddd;">
<div style="text-align: center; margin-bottom: 20px;">
<h1 style="color: #333; font-size: 24px; margin: 0;">Call Analysis Report</h1>
<p style="color: #888; font-size: 14px; margin: 5px 0 15px;">Analysis powered by AI</p>
</div>
<!-- Call Summary -->
<div style="margin-bottom: 20px;">
<h2 style="color: #0056b3; font-size: 20px; margin-bottom: 10px; border-bottom: 1px solid #e1e1e1; padding-bottom: 5px;">Call Summary</h2>
<p style="font-size: 14px; line-height: 1.6;">${CALL_SUMMARY}</p>
</div>
<!-- Call Timeline -->
<div style="margin-bottom: 20px;">
<h2 style="color: #0056b3; font-size: 20px; margin-bottom: 10px; border-bottom: 1px solid #e1e1e1; padding-bottom: 5px;">Call Timeline</h2>
${TRANSCRIPTION_TIMELINE}</div>
<!-- Call Sentiments -->
<div style="margin-bottom: 20px;">
<h2 style="color: #0056b3; font-size: 20px; margin-bottom: 10px; border-bottom: 1px solid #e1e1e1; padding-bottom: 5px;">Call Sentiments</h2>
<div style="display: flex; justify-content: space-between;">
<div style="width: 32%; text-align: center; padding: 10px; background-color: #f2f2f2; border-radius: 8px;">
<p style="margin: 0; font-size: 14px;">Positive</p>
<p style="font-weight: bold; font-size: 16px; margin: 5px 0;">${POSITIVE}</p>
</div>
<div style="width: 32%; text-align: center; padding: 10px; background-color: #f2f2f2; border-radius: 8px;">
<p style="margin: 0; font-size: 14px;">Negative</p>
<p style="font-weight: bold; font-size: 16px; margin: 5px 0;">${NEGATIVE}</p>
</div>
<div style="width: 32%; text-align: center; padding: 10px; background-color: #f2f2f2; border-radius: 8px;">
<p style="margin: 0; font-size: 14px;">Neutral</p>
<p style="font-weight: bold; font-size: 16px; margin: 5px 0;">${NEUTRAL}</p>
</div>
</div>
</div>
<!-- Issue Type -->
<div style="margin-bottom: 20px;">
<h2 style="color: #0056b3; font-size: 20px; margin-bottom: 10px; border-bottom: 1px solid #e1e1e1; padding-bottom: 5px;">Issue Type</h2>
<p style="font-size: 14px; line-height: 1.6;">${ISSUE}</p>
</div>
<!-- Call Resolution -->
<div style="margin-bottom: 20px;">
<h2 style="color: #0056b3; font-size: 20px; margin-bottom: 10px; border-bottom: 1px solid #e1e1e1; padding-bottom: 5px;">Call Resolution</h2>
<p style="font-size: 14px; line-height: 1.6;">${RESOLUTION}</p>
</div>
<!-- Keywords and Topics -->
<div style="margin-bottom: 20px;">
<h2 style="color: #0056b3; font-size: 20px; margin-bottom: 10px; border-bottom: 1px solid #e1e1e1; padding-bottom: 5px;">Keywords</h2>
<p style="font-size: 14px; line-height: 1.6;">${KEYWORDS}</p>
</div>
<div style="margin-bottom: 20px;">
<h2 style="color: #0056b3; font-size: 20px; margin-bottom: 10px; border-bottom: 1px solid #e1e1e1; padding-bottom: 5px;">Topics</h2>
<p style="font-size: 14px; line-height: 1.6;">${TOPICS}</p>
</div>
<!-- Improvements Suggestions -->
<div style="margin-bottom: 20px;">
<h2 style="color: #0056b3; font-size: 20px; margin-bottom: 10px; border-bottom: 1px solid #e1e1e1; padding-bottom: 5px;">Improvement Suggestions</h2>
<p style="font-size: 14px; line-height: 1.6;">${SUGGESTIONS}</p>
</div>
<!-- AI Disclaimer -->
<div style="text-align: center; font-size: 12px; color: #888;">
<p><strong>Note:</strong> This report was generated by an AI, and the data may not be fully accurate.</p>
</div>
</div>');