// APNs VoIP push sender (token-based, .p8 ES256 JWT auth).
//
// This module delivers **VoIP** pushes to iOS devices so the Connect app can
// wake from a killed/backgrounded state and report an incoming call to CallKit.
// It is intentionally:
//   • CALL-ONLY — never use this for voicemail / SMS / missed-call / chat /
//     general notifications. Apple terminates apps that receive a VoIP push
//     without promptly reporting a CallKit call. Those events must continue to
//     use the existing Expo/APNs *alert* path.
//   • Dependency-free — uses Node's built-in `http2` + `crypto` only, so no new
//     npm packages are introduced.
//
// Auth: token-based APNs (recommended over certificates). We sign a short-lived
// ES256 JWT with the Apple `.p8` AuthKey and send it as the `authorization`
// bearer on every request. The JWT is cached and refreshed well within Apple's
// 60-minute validity window.
//
// Required environment variables (no real secret values are committed):
//   APNS_TEAM_ID         Apple Developer Team ID (10 chars)            e.g. ABCDE12345
//   APNS_KEY_ID          Key ID of the APNs AuthKey (.p8)             e.g. KEY1234567
//   APNS_AUTH_KEY_P8     The .p8 private key PEM contents (multi-line) OR
//   APNS_AUTH_KEY_BASE64 base64 of the .p8 contents (handy for single-line env)
//   APNS_BUNDLE_ID       App bundle id   (default: com.connectcommunications.mobile)
//   APNS_VOIP_TOPIC      VoIP topic      (default: <bundle id>.voip)
//   APNS_PRODUCTION      "true" → api.push.apple.com, else sandbox host
//
// If the required vars are absent, `isApnsVoipConfigured()` returns false and
// callers MUST skip VoIP delivery (Android/Expo behavior is unaffected).

import http2 from "http2";
import { createPrivateKey, createSign, KeyObject } from "crypto";

const APNS_PROD_HOST = "https://api.push.apple.com";
const APNS_SANDBOX_HOST = "https://api.sandbox.push.apple.com";

const DEFAULT_BUNDLE_ID = "com.connectcommunications.mobile";

export interface ApnsVoipCallPayload {
  /** Connect invite UUID — correlates CallKit / SIP / in-app across the call. */
  callId: string;
  tenantId: string;
  /** Target user/extension identifier so the app can scope the CallKit report. */
  toExtension: string;
  callerNumber?: string | null;
  callerName?: string | null;
  /** ISO-8601 timestamp of the originating call event. */
  timestamp: string;
}

export interface ApnsVoipSendResult {
  ok: boolean;
  /** HTTP/2 :status from APNs (200 = accepted). null when transport failed. */
  status: number | null;
  /** apns-id echoed/generated by Apple, for cross-referencing in Apple logs. */
  apnsId: string | null;
  /** APNs failure reason string (e.g. "BadDeviceToken", "Unregistered"). */
  reason: string | null;
  /** True when APNs says the token is dead and should be marked stale. */
  tokenInvalid: boolean;
  error?: string;
}

function envBundleId(): string {
  return (process.env.APNS_BUNDLE_ID || DEFAULT_BUNDLE_ID).trim();
}

function envVoipTopic(): string {
  const explicit = (process.env.APNS_VOIP_TOPIC || "").trim();
  if (explicit) return explicit;
  return `${envBundleId()}.voip`;
}

function envHost(): string {
  return (process.env.APNS_PRODUCTION || "false").toLowerCase() === "true"
    ? APNS_PROD_HOST
    : APNS_SANDBOX_HOST;
}

function readAuthKeyPem(): string | null {
  const direct = process.env.APNS_AUTH_KEY_P8;
  if (direct && direct.includes("BEGIN")) {
    // Allow literal "\n" escapes commonly used when storing PEM in a single-line env.
    return direct.includes("\\n") ? direct.replace(/\\n/g, "\n") : direct;
  }
  const b64 = process.env.APNS_AUTH_KEY_BASE64;
  if (b64 && b64.trim()) {
    try {
      return Buffer.from(b64.trim(), "base64").toString("utf8");
    } catch {
      return null;
    }
  }
  return null;
}

/** True only when every credential needed to send a VoIP push is present. */
export function isApnsVoipConfigured(): boolean {
  return Boolean(
    process.env.APNS_TEAM_ID &&
      process.env.APNS_KEY_ID &&
      readAuthKeyPem(),
  );
}

// ── ES256 JWT signing (cached) ───────────────────────────────────────────────

let cachedJwt: { token: string; issuedAt: number } | null = null;
let cachedKey: KeyObject | null = null;
// Apple accepts a provider token for up to 60 min; refresh at 50 to be safe.
const JWT_TTL_MS = 50 * 60 * 1000;

function base64url(input: Buffer | string): string {
  return Buffer.from(input)
    .toString("base64")
    .replace(/=/g, "")
    .replace(/\+/g, "-")
    .replace(/\//g, "_");
}

function getSigningKey(pem: string): KeyObject {
  if (!cachedKey) {
    cachedKey = createPrivateKey({ key: pem, format: "pem" });
  }
  return cachedKey;
}

function buildProviderJwt(): string | null {
  const teamId = process.env.APNS_TEAM_ID?.trim();
  const keyId = process.env.APNS_KEY_ID?.trim();
  const pem = readAuthKeyPem();
  if (!teamId || !keyId || !pem) return null;

  const now = Date.now();
  if (cachedJwt && now - cachedJwt.issuedAt < JWT_TTL_MS) {
    return cachedJwt.token;
  }

  const header = { alg: "ES256", kid: keyId };
  const claims = { iss: teamId, iat: Math.floor(now / 1000) };
  const signingInput = `${base64url(JSON.stringify(header))}.${base64url(JSON.stringify(claims))}`;

  try {
    const key = getSigningKey(pem);
    // `dsaEncoding: "ieee-p1363"` yields the raw R||S signature JWT/JOSE expects
    // (Node's default is DER, which APNs rejects).
    const signer = createSign("SHA256");
    signer.update(signingInput);
    signer.end();
    const signature = signer.sign({ key, dsaEncoding: "ieee-p1363" });
    const token = `${signingInput}.${base64url(signature)}`;
    cachedJwt = { token, issuedAt: now };
    return token;
  } catch (err) {
    console.error(
      JSON.stringify({
        event: "apns_voip_jwt_error",
        message: err instanceof Error ? err.message : String(err),
      }),
    );
    return null;
  }
}

/** Force the next send to mint a fresh provider JWT (e.g. after a 403). */
export function resetApnsProviderTokenCache(): void {
  cachedJwt = null;
}

// ── Send ─────────────────────────────────────────────────────────────────────

const APNS_INVALID_TOKEN_REASONS = new Set([
  "BadDeviceToken",
  "Unregistered",
  "DeviceTokenNotForTopic",
]);

/**
 * Send a single VoIP push to one device token.
 *
 * The payload is deliberately minimal — only what CallKit needs to present the
 * call — to keep VoIP pushes small and avoid leaking sensitive data into the
 * APNs envelope.
 */
export function sendApnsVoipPush(
  deviceToken: string,
  payload: ApnsVoipCallPayload,
): Promise<ApnsVoipSendResult> {
  return new Promise((resolve) => {
    const jwt = buildProviderJwt();
    if (!jwt) {
      resolve({
        ok: false,
        status: null,
        apnsId: null,
        reason: null,
        tokenInvalid: false,
        error: "apns_not_configured",
      });
      return;
    }

    const body = JSON.stringify({
      // CallKit-minimal payload. No alert/sound — VoIP pushes are silent wakes.
      callId: payload.callId,
      tenantId: payload.tenantId,
      toExtension: payload.toExtension,
      callerNumber: payload.callerNumber ?? null,
      callerName: payload.callerName ?? null,
      timestamp: payload.timestamp,
    });

    let session: http2.ClientHttp2Session;
    try {
      session = http2.connect(envHost());
    } catch (err) {
      resolve({
        ok: false,
        status: null,
        apnsId: null,
        reason: null,
        tokenInvalid: false,
        error: err instanceof Error ? err.message : String(err),
      });
      return;
    }

    let settled = false;
    const finish = (result: ApnsVoipSendResult) => {
      if (settled) return;
      settled = true;
      try {
        session.close();
      } catch {
        /* ignore */
      }
      resolve(result);
    };

    session.on("error", (err) => {
      finish({
        ok: false,
        status: null,
        apnsId: null,
        reason: null,
        tokenInvalid: false,
        error: err instanceof Error ? err.message : String(err),
      });
    });

    const req = session.request({
      ":method": "POST",
      ":path": `/3/device/${deviceToken}`,
      authorization: `bearer ${jwt}`,
      "apns-topic": envVoipTopic(),
      "apns-push-type": "voip",
      "apns-priority": "10",
      // Short-lived: an inbound call ring is only relevant for a few seconds.
      "apns-expiration": String(Math.floor(Date.now() / 1000) + 30),
      "content-type": "application/json",
      "content-length": Buffer.byteLength(body),
    });

    let status: number | null = null;
    let apnsId: string | null = null;
    let raw = "";

    req.on("response", (headers) => {
      status = Number(headers[":status"]) || null;
      apnsId = (headers["apns-id"] as string) || null;
    });
    req.setEncoding("utf8");
    req.on("data", (chunk) => {
      raw += chunk;
    });
    req.on("end", () => {
      let reason: string | null = null;
      if (raw) {
        try {
          reason = (JSON.parse(raw)?.reason as string) || null;
        } catch {
          reason = null;
        }
      }
      const ok = status === 200;
      const tokenInvalid =
        status === 410 || (reason != null && APNS_INVALID_TOKEN_REASONS.has(reason));
      finish({ ok, status, apnsId, reason, tokenInvalid });
    });
    req.on("error", (err) => {
      finish({
        ok: false,
        status,
        apnsId,
        reason: null,
        tokenInvalid: false,
        error: err instanceof Error ? err.message : String(err),
      });
    });

    req.write(body);
    req.end();
  });
}

/** Diagnostics helper — what topic/host/config we would use (no secrets). */
export function describeApnsVoipConfig(): {
  configured: boolean;
  topic: string;
  host: string;
  bundleId: string;
} {
  return {
    configured: isApnsVoipConfigured(),
    topic: envVoipTopic(),
    host: envHost(),
    bundleId: envBundleId(),
  };
}
