-- Remote support: the kill switch, revocations, capability tiers and the
-- session event/chat timeline (mandate Phases 11, 12, 21, 22, 29, 30, 37).
--
-- Generated by `prisma migrate diff` from the previous schema to this one.
-- Additive only: no column is dropped, no type is narrowed, and every new
-- column carries a default, so an api running the PREVIOUS build keeps
-- working against this schema for the length of a blue/green cutover.

-- CreateEnum
CREATE TYPE "RemoteSupportRevocationScope" AS ENUM ('TECHNICIAN', 'DEVICE', 'TENANT');

-- AlterTable
ALTER TABLE "RemoteSupportSession" ADD COLUMN     "capabilitiesGranted" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "capabilitiesRequested" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "clientOnCall" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "deviceId" TEXT;

-- CreateTable
CREATE TABLE "RemoteSupportControl" (
    "id" TEXT NOT NULL DEFAULT 'global',
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "disabledReason" TEXT,
    "disabledByUserId" TEXT,
    "disabledAt" TIMESTAMP(3),
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RemoteSupportControl_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RemoteSupportRevocation" (
    "id" TEXT NOT NULL,
    "scope" "RemoteSupportRevocationScope" NOT NULL,
    "subjectId" TEXT NOT NULL,
    "reason" TEXT,
    "createdByUserId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "liftedAt" TIMESTAMP(3),
    "liftedByUserId" TEXT,

    CONSTRAINT "RemoteSupportRevocation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RemoteSupportEvent" (
    "id" TEXT NOT NULL,
    "sessionId" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "actorRole" TEXT NOT NULL,
    "actorUserId" TEXT,
    "code" TEXT NOT NULL,
    "body" TEXT,
    "meta" JSONB,
    "at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RemoteSupportEvent_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "RemoteSupportRevocation_scope_subjectId_liftedAt_idx" ON "RemoteSupportRevocation"("scope", "subjectId", "liftedAt");

-- CreateIndex
CREATE INDEX "RemoteSupportRevocation_liftedAt_idx" ON "RemoteSupportRevocation"("liftedAt");

-- CreateIndex
CREATE INDEX "RemoteSupportEvent_sessionId_at_idx" ON "RemoteSupportEvent"("sessionId", "at");

-- CreateIndex
CREATE INDEX "RemoteSupportEvent_tenantId_at_idx" ON "RemoteSupportEvent"("tenantId", "at");

-- CreateIndex
CREATE INDEX "RemoteSupportSession_requestedByUserId_createdAt_idx" ON "RemoteSupportSession"("requestedByUserId", "createdAt");

-- CreateIndex
CREATE INDEX "RemoteSupportSession_deviceId_idx" ON "RemoteSupportSession"("deviceId");

-- AddForeignKey
ALTER TABLE "RemoteSupportEvent" ADD CONSTRAINT "RemoteSupportEvent_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "RemoteSupportSession"("id") ON DELETE CASCADE ON UPDATE CASCADE;

