/**
 * Generates the reference docs FROM SOURCE so they cannot drift (brief §61):
 *   docs/community/API.md          — every route (method, path, file), grouped by domain
 *   docs/community/ERD.md          — models + relations from prisma/schema.prisma (Mermaid)
 *   docs/community/EVENTS.md       — analytics event catalog + notification classes
 *   docs/community/PERMISSIONS.md  — org permission matrix (role presets × keys)
 *   docs/community/DOMAINS.md      — domain map (registered modules + test counts)
 * Run: pnpm --filter @loopcom/community-api docs:generate
 */
import { readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { ANALYTICS_EVENTS } from "../lib/analytics.js";
import { NOTIFICATION_CLASSES } from "../lib/notify.js";
import { ORG_PERMISSIONS, ROLE_PRESETS } from "../organizations/permissions.js";

const root = path.resolve(process.cwd(), "../..");
const apiSrc = path.resolve(process.cwd(), "src");
const out = path.join(root, "docs/community");
mkdirSync(out, { recursive: true });

function walk(dir: string, acc: string[] = []): string[] {
  for (const n of readdirSync(dir)) {
    const p = path.join(dir, n);
    if (statSync(p).isDirectory()) walk(p, acc);
    else if (/\.ts$/.test(n) && !/\.test\.ts$/.test(n)) acc.push(p);
  }
  return acc;
}

// ── API ───────────────────────────────────────────────────────────────────
type Route = { method: string; path: string; file: string; auth: string };
const routes: Route[] = [];
for (const file of walk(apiSrc)) {
  const src = readFileSync(file, "utf8");
  const rel = path.relative(apiSrc, file).replace(/\\/g, "/");
  for (const m of src.matchAll(/app\.(get|post|put|patch|delete)\(\s*["'`]([^"'`]+)["'`]/g)) {
    const p = m[2];
    const auth = p.startsWith("/public/") || p === "/health" || p.startsWith("/auth/register") || p.startsWith("/auth/login") || p.startsWith("/auth/refresh") || p.startsWith("/auth/password/") || p.startsWith("/auth/oauth") || p === "/auth/loopcom" || p.startsWith("/auth/passkeys/login") || p.startsWith("/media/file/") || p === "/flags" || p === "/analytics/events" || p.startsWith("/dev/") || p.startsWith("/search")
      ? "public"
      : p.startsWith("/admin/")
        ? "staff"
        : "signed-in";
    routes.push({ method: m[1].toUpperCase(), path: p, file: rel, auth });
  }
}
routes.sort((a, b) => a.file.localeCompare(b.file) || a.path.localeCompare(b.path));
const byDomain = new Map<string, Route[]>();
for (const r of routes) {
  const d = r.file.split("/")[0];
  byDomain.set(d, [...(byDomain.get(d) ?? []), r]);
}
let api = `# Loopcom Community — API reference\n\nGenerated from source by \`src/testing/generateDocs.ts\` — ${routes.length} routes. Base URL: \`COMMUNITY_API_URL\` (local http://localhost:3101). Auth: \`Authorization: Bearer <access token>\` (15-minute JWT from /auth/login or /auth/refresh). Every error body is \`{ error, message }\` with a human sentence. Mutations accept \`Idempotency-Key\`. Lists page with \`?cursor=&limit=\`.\n\n| Auth | Meaning |\n|---|---|\n| public | no token needed |\n| signed-in | any Loopcom ID |\n| staff | StaffGrant MODERATOR/ADMIN |\n\n`;
for (const [domain, list] of [...byDomain.entries()].sort()) {
  api += `## ${domain} (${list.length})\n\n| Method | Path | Auth | File |\n|---|---|---|---|\n`;
  for (const r of list) api += `| ${r.method} | \`${r.path}\` | ${r.auth} | ${r.file} |\n`;
  api += "\n";
}
writeFileSync(path.join(out, "API.md"), api);

// ── ERD ───────────────────────────────────────────────────────────────────
const schema = readFileSync(path.resolve(process.cwd(), "prisma/schema.prisma"), "utf8");
const models = [...schema.matchAll(/model (\w+) \{([\s\S]*?)\n\}/g)].map((m) => ({ name: m[1], body: m[2] }));
let erd = `# Loopcom Community — data model\n\n${models.length} models in \`apps/community-api/prisma/schema.prisma\` (own database). Generated by \`src/testing/generateDocs.ts\`.\n\n\`\`\`mermaid\nerDiagram\n`;
const rel: string[] = [];
for (const m of models) {
  const fields = m.body.split("\n").map((l) => l.trim()).filter((l) => l && !l.startsWith("//") && !l.startsWith("@@") && !l.startsWith("///"));
  erd += `  ${m.name} {\n`;
  for (const f of fields.slice(0, 12)) {
    const [name, type] = f.split(/\s+/);
    if (!name || !type || /\[\]$/.test(type) && models.some((x) => x.name === type.replace("[]", "").replace("?", ""))) continue;
    const t = type.replace("?", "").replace("[]", "");
    if (models.some((x) => x.name === t)) continue;
    erd += `    ${t.replace(/[^A-Za-z0-9_]/g, "")} ${name}\n`;
  }
  erd += `  }\n`;
  for (const r of m.body.matchAll(/@relation\([^)]*fields:\s*\[(\w+)\][^)]*references:\s*\[(\w+)\]/g)) {
    const line = m.body.split("\n").find((l) => l.includes(r[0]))!;
    const target = line.trim().split(/\s+/)[1]?.replace("?", "");
    if (target && models.some((x) => x.name === target)) rel.push(`  ${target} ||--o{ ${m.name} : "${r[1]}"`);
  }
}
erd += [...new Set(rel)].join("\n") + "\n```\n\n## Tables by domain\n\n";
const groups: Record<string, string[]> = {};
for (const m of models) {
  const g = /^(Person|Session|Passkey|OAuthAccount|VerificationCode|StaffGrant)$/.test(m.name) ? "Identity" : /^(Profile|Experience|Education|ProfileService|Certification|PortfolioItem|PrivacySetting|Recommendation|Endorsement)$/.test(m.name) ? "Profiles" : /^(Organization|OrgLocation|Membership|OrgInvite|Verification|CatalogItem)$/.test(m.name) ? "Organizations" : /^(Connection|Follow|Block|Mute|RelationshipTag|Report)$/.test(m.name) ? "Graph" : /^(Post|PostMedia|Mention|Comment|Reaction|Save|Poll|PollOption|PollVote|ScheduledPost|Hide)$/.test(m.name) ? "Posts & feed" : /^(Thread|ThreadParticipant|Message)$/.test(m.name) ? "Messaging" : /^(Group|GroupMember|GroupFile)$/.test(m.name) ? "Groups" : /^(Event|EventRsvp)$/.test(m.name) ? "Events" : /^(Job|JobApplication|JobAlert|JobSave)$/.test(m.name) ? "Jobs" : /^(Category|Listing|ListingMedia|ListingSave)$/.test(m.name) ? "Marketplace" : /^(Rfq|RfqAttachment|RfqInvite|Quote|QuoteAttachment|RfqQuestion)$/.test(m.name) ? "RFQ" : /^(OpportunityType|Opportunity|OpportunityInterest)$/.test(m.name) ? "Opportunities" : /^IntroRequest$/.test(m.name) ? "Introductions" : /^(PrivateNote|Reminder)$/.test(m.name) ? "Mini-CRM" : /^(Notification|NotificationPref|DeviceToken|OutboundMail)$/.test(m.name) ? "Notifications" : /^(SavedSearch|RecentSearch)$/.test(m.name) ? "Search" : /^MediaAsset$/.test(m.name) ? "Media" : /^(AnalyticsEvent|AnalyticsDaily|RecommendationImpression|FeatureFlag|Experiment|ExperimentAssignment)$/.test(m.name) ? "Analytics & experiments" : /^(ModerationCase|ModerationAction|Restriction|Appeal|AuditLog|IdempotencyKey|OutreachStat)$/.test(m.name) ? "Moderation, audit, safety" : "Other";
  (groups[g] ??= []).push(m.name);
}
for (const [g, list] of Object.entries(groups)) erd += `- **${g}**: ${list.join(", ")}\n`;
writeFileSync(path.join(out, "ERD.md"), erd);

// ── Events + notification classes ─────────────────────────────────────────
let ev = `# Loopcom Community — event catalog\n\nGenerated from \`src/lib/analytics.ts\` and \`src/lib/notify.ts\`.\n\n## Analytics events (${ANALYTICS_EVENTS.length})\n\nSchema (AnalyticsEvent): personId?, sessionId?, event, objectType?, objectId?, client?, appVersion?, surface?, position?, recommendationId?, experimentId?, props (screened: no keys matching password|secret|token|card|ssn|body|message), occurredAt.\n\n`;
for (const e of ANALYTICS_EVENTS) ev += `- \`${e}\`\n`;
ev += `\n## Notification classes (${Object.keys(NOTIFICATION_CLASSES).length})\n\n| Class | Label | Batch window (min) | In-app | Push | Email | SMS |\n|---|---|---|---|---|---|---|\n`;
for (const [k, c] of Object.entries(NOTIFICATION_CLASSES)) ev += `| \`${k}\` | ${c.label} | ${c.batchMinutes} | ${c.defaults.inApp ? "✓" : "—"} | ${c.defaults.push ? "✓" : "—"} | ${c.defaults.email ? "✓" : "—"} | ${c.defaults.sms ? "✓" : "—"} |\n`;
writeFileSync(path.join(out, "EVENTS.md"), ev);

// ── Permissions ───────────────────────────────────────────────────────────
let perm = `# Loopcom Community — permissions matrix\n\nGenerated from \`src/organizations/permissions.ts\`. Three layers, checked in order: platform (StaffGrant), organization (Membership role + explicit keys), relationship (degree/blocks/section visibility in \`src/policy/graph.ts\`).\n\n## Organization roles × permission keys\n\n| Key | ${Object.keys(ROLE_PRESETS).join(" | ")} |\n|---|${Object.keys(ROLE_PRESETS).map(() => "---").join("|")}|\n`;
for (const key of ORG_PERMISSIONS) perm += `| \`${key}\` | ${Object.values(ROLE_PRESETS).map((set) => (set.includes(key) ? "✓" : "—")).join(" | ")} |\n`;
perm += `\nCUSTOM roles carry an explicit \`permissions[]\` list; presets may also add keys. Owners cannot be demoted below one remaining owner. Platform staff: MODERATOR (moderation queue, reads), ADMIN (everything incl. flags/experiments/users/organizations).\n`;
writeFileSync(path.join(out, "PERMISSIONS.md"), perm);

// ── Domains ───────────────────────────────────────────────────────────────
const domainsSrc = readFileSync(path.join(apiSrc, "domains.ts"), "utf8");
const registered = [...domainsSrc.matchAll(/\["(\w[\w-]*)",\s*"(\w+)"\]/g)].map((m) => m[1]);
let dm = `# Loopcom Community — domain map\n\nRegistered in \`src/domains.ts\` (a domain not listed there does not exist). Each domain: \`routes.ts\` (HTTP), \`policy.ts\` (pure decisions), \`service.ts\` (db work), \`*.test.ts\` (integration tests on the real db).\n\n| Domain | Routes | Test files |\n|---|---|---|\n`;
for (const d of registered) {
  const dir = path.join(apiSrc, d);
  let tests = 0;
  try {
    tests = readdirSync(dir).filter((f) => f.endsWith(".test.ts")).length;
  } catch {
    /* missing */
  }
  dm += `| ${d} | ${byDomain.get(d)?.length ?? 0} | ${tests} |\n`;
}
dm += `\nCross-cutting: \`auth/\` (identity), \`core/\` (SSE, analytics ingest, flags, privacy, devices, schedulers), \`lib/\` (audit, notify, realtime, storage, mail, push, idempotency, search, pagination), \`policy/graph.ts\`, \`concierge/\`.\n`;
writeFileSync(path.join(out, "DOMAINS.md"), dm);

console.log(`docs: ${routes.length} routes, ${models.length} models, ${ANALYTICS_EVENTS.length} events, ${Object.keys(NOTIFICATION_CLASSES).length} notification classes, ${registered.length} domains → ${out}`);
