use `ombutel`;

insert into `ombu_geo_firewall` (`iso`, `country`) values
    ('gf', 'French Guiana'),
    ('gs', 'South Georgia and South Sandwich Islands'),
    ('aw', 'Aruba'),
    ('vi', 'Virgin Islands (U.S.)'),
    ('cw', 'Curaçao'),
    ('bq', 'Bonaire, Sint Eustatius and Saba'),
    ('bb', 'Barbados'),
    ('vc', 'Saint Vincent and the Grenadines'),
    ('gd', 'Grenada'),
    ('lc', 'Saint Lucia'),
    ('mq', 'Martinique'),
    ('dm', 'Dominica'),
    ('gp', 'Guadeloupe'),
    ('ms', 'Montserrat'),
    ('ag', 'Antigua and Barbuda'),
    ('kn', 'Saint Kitts and Nevis'),
    ('ai', 'Anguilla'),
    ('vg', 'Virgin Islands (British)'),
    ('sx', 'Sint Maarten'),
    ('bl', 'Saint Barthélemy'),
    ('ky', 'Cayman Islands'),
    ('tc', 'Turks and Caicos Islands'),
    ('cv', 'Cabo Verde'),
    ('ad', 'Andorra'),
    ('sm', 'San Marino'),
    ('li', 'Liechtenstein'),
    ('je', 'Jersey'),
    ('gg', 'Guernsey'),
    ('im', 'Isle of Man'),
    ('ax', 'Åland Islands'),
    ('fo', 'Faroe Islands'),
    ('sj', 'Svalbard and Jan Mayen'),
    ('mo', 'Macao'),
    ('hk', 'Hong Kong'),
    ('st', 'Sao Tome and Principe'),
    ('km', 'Comoros'),
    ('yt', 'Mayotte'),
    ('re', 'Réunion'),
    ('mu', 'Mauritius'),
    ('mt', 'Malta'),
    ('hm', 'Heard Island and McDonald Islands'),
    ('sg', 'Singapore'),
    ('pw', 'Palau'),
    ('to', 'Tonga'),
    ('nu', 'Niue'),
    ('as', 'American Samoa'),
    ('ws', 'Samoa'),
    ('wf', 'Wallis and Futuna'),
    ('tv', 'Tuvalu'),
    ('ki', 'Kiribati'),
    ('nr', 'Nauru'),
    ('fm', 'Micronesia (Federated States of)'),
    ('mh', 'Marshall Islands'),
    ('gu', 'Guam'),
    ('mp', 'Northern Mariana Islands'),
    ('cx', 'Christmas Island'),
    ('io', 'British Indian Ocean Territory'),
    ('sc', 'Seychelles'),
    ('pm', 'Saint Pierre and Miquelon'),
    ('bh', 'Bahrain'),
    ('mf', 'Saint Martin');

