use `ombutel`;

alter table `states`
 add column `abbreviation` varchar(255) null default null;

/* USA States Abbreviations */
update `states` set `abbreviation` = 'AL' where `state` = 'Alabama';
update `states` set `abbreviation` = 'AK' where `state` = 'Alaska';
update `states` set `abbreviation` = 'AS' where `state` = 'American Samoa';
update `states` set `abbreviation` = 'AZ' where `state` = 'Arizona';
update `states` set `abbreviation` = 'AR' where `state` = 'Arkansas';
update `states` set `abbreviation` = 'CA' where `state` = 'California';
update `states` set `abbreviation` = 'CO' where `state` = 'Colorado';
update `states` set `abbreviation` = 'CT' where `state` = 'Connecticut';
update `states` set `abbreviation` = 'DE' where `state` = 'Delaware';
update `states` set `abbreviation` = 'DC' where `state` = 'District of Columbia';
update `states` set `abbreviation` = 'FM' where `state` = 'Federated States of Micronesia';
update `states` set `abbreviation` = 'FL' where `state` = 'Florida';
update `states` set `abbreviation` = 'GA' where `state` = 'Georgia';
update `states` set `abbreviation` = 'GU' where `state` = 'Guam';
update `states` set `abbreviation` = 'HI' where `state` = 'Hawaii';
update `states` set `abbreviation` = 'ID' where `state` = 'Idaho';
update `states` set `abbreviation` = 'IL' where `state` = 'Illinois';
update `states` set `abbreviation` = 'IN' where `state` = 'Indiana';
update `states` set `abbreviation` = 'IA' where `state` = 'Iowa';
update `states` set `abbreviation` = 'KS' where `state` = 'Kansas';
update `states` set `abbreviation` = 'KY' where `state` = 'Kentucky';
update `states` set `abbreviation` = 'LA' where `state` = 'Louisiana';
update `states` set `abbreviation` = 'ME' where `state` = 'Maine';
update `states` set `abbreviation` = 'MH' where `state` = 'Marshall Islands';
update `states` set `abbreviation` = 'MD' where `state` = 'Maryland';
update `states` set `abbreviation` = 'MA' where `state` = 'Massachusetts';
update `states` set `abbreviation` = 'MI' where `state` = 'Michigan';
update `states` set `abbreviation` = 'MN' where `state` = 'Minnesota';
update `states` set `abbreviation` = 'MS' where `state` = 'Mississippi';
update `states` set `abbreviation` = 'MO' where `state` = 'Missouri';
update `states` set `abbreviation` = 'MT' where `state` = 'Montana';
update `states` set `abbreviation` = 'NE' where `state` = 'Nebraska';
update `states` set `abbreviation` = 'NV' where `state` = 'Nevada';
update `states` set `abbreviation` = 'NH' where `state` = 'New Hampshire';
update `states` set `abbreviation` = 'NJ' where `state` = 'New Jersey';
update `states` set `abbreviation` = 'NM' where `state` = 'New Mexico';
update `states` set `abbreviation` = 'NY' where `state` = 'New York';
update `states` set `abbreviation` = 'NC' where `state` = 'North Carolina';
update `states` set `abbreviation` = 'ND' where `state` = 'North Dakota';
update `states` set `abbreviation` = 'MP' where `state` = 'Northern Mariana Islands';
update `states` set `abbreviation` = 'OH' where `state` = 'Ohio';
update `states` set `abbreviation` = 'OK' where `state` = 'Oklahoma';
update `states` set `abbreviation` = 'OR' where `state` = 'Oregon';
update `states` set `abbreviation` = 'PW' where `state` = 'Palau';
update `states` set `abbreviation` = 'PA' where `state` = 'Pennsylvania';
update `states` set `abbreviation` = 'PR' where `state` = 'Puerto Rico';
update `states` set `abbreviation` = 'RI' where `state` = 'Rhode Island';
update `states` set `abbreviation` = 'SC' where `state` = 'South Carolina';
update `states` set `abbreviation` = 'SD' where `state` = 'South Dakota';
update `states` set `abbreviation` = 'TN' where `state` = 'Tennessee';
update `states` set `abbreviation` = 'TX' where `state` = 'Texas';
update `states` set `abbreviation` = 'UT' where `state` = 'Utah';
update `states` set `abbreviation` = 'VT' where `state` = 'Vermont';
update `states` set `abbreviation` = 'VI' where `state` = 'Virgin Islands';
update `states` set `abbreviation` = 'VA' where `state` = 'Virginia';
update `states` set `abbreviation` = 'WA' where `state` = 'Washington';
update `states` set `abbreviation` = 'WV' where `state` = 'West Virginia';
update `states` set `abbreviation` = 'WI' where `state` = 'Wisconsin';
update `states` set `abbreviation` = 'WY' where `state` = 'Wyoming';

/* Canada Provinces/States abbreviations */
update `states` set `abbreviation` = 'AB' where `state` = 'Alberta';
update `states` set `abbreviation` = 'BC' where `state` = 'British Columbia';
update `states` set `abbreviation` = 'MB' where `state` = 'Manitoba';
update `states` set `abbreviation` = 'NB' where `state` = 'New Brunswick';
update `states` set `abbreviation` = 'NL' where `state` = 'Newfoundland and Labrador';
update `states` set `abbreviation` = 'NT' where `state` = 'Northwest Territories';
update `states` set `abbreviation` = 'NS' where `state` = 'Nova Scotia';
update `states` set `abbreviation` = 'NU' where `state` = 'Nunavut';
update `states` set `abbreviation` = 'ON' where `state` = 'Ontario';
update `states` set `abbreviation` = 'PE' where `state` = 'Prince Edward Island';
update `states` set `abbreviation` = 'QC' where `state` = 'Quebec';
update `states` set `abbreviation` = 'SK' where `state` = 'Saskatchewan';
update `states` set `abbreviation` = 'YT' where `state` = 'Yukon';