; *********************************************************************************
; @Date : Wed Jun 3 16:48:04 GMT 2026
; @Document : extensions__15-global.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[globals]
ASTAGIDIR=/var/lib/asterisk/agi-bin
ASTETCDIR=/etc/asterisk
ASTLOGDIR=/var/log/asterisk
ASTMODDIR=/usr/lib/asterisk/modules
ASTSOUNDDIR=/var/lib/asterisk/sounds
ASTSPOOLDIR=/var/spool/asterisk
ASTVARLIBDIR=/var/lib/asterisk
RINGTIMEDEF=30
RECORDING_FORMAT=wav
RECORDING_SCRIPT=
SEND_DIVERSION_HEADERS=no
PLAY_CW_TONE=no
SCRIPTS_PATH=/usr/share/vitalpbx/scripts
