; *********************************************************************************
; @Date : Sun May 3 21:39:27 GMT 2026
; @Document : extensions__25-10-hints.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T10_extension-hints]
exten => 101,hint,pjsip/T10_101&Custom:T10_DND_101

exten => unavailable,hint,T10_unavailable

exten => QAGENT,hint,Custom:T10_QAGENT

exten => 701,hint,park:701@parking-10-parkedcalls

exten => 702,hint,park:702@parking-10-parkedcalls

exten => 703,hint,park:703@parking-10-parkedcalls

exten => 704,hint,park:704@parking-10-parkedcalls

exten => 705,hint,park:705@parking-10-parkedcalls

exten => 706,hint,park:706@parking-10-parkedcalls

exten => 707,hint,park:707@parking-10-parkedcalls

exten => 708,hint,park:708@parking-10-parkedcalls

exten => 709,hint,park:709@parking-10-parkedcalls

exten => 710,hint,park:710@parking-10-parkedcalls

exten => TC8,hint,Custom:TC8
 same => 1,NoOp(Time Condition: Main)
 same => n,Gosub(sub-set-global-vars,s,1(ab6beaa898dd9618,${EXTEN},parking-10))
 same => n,Gosub(sub-set-call-vars,s,1(ab6beaa898dd9618,${EXTEN},,,))
 same => n,Gosub(sub-construct-cid,s,1)
 same => n,Gosub(sub-toggle-tc-state,s,1(8,TG-8))


