; *********************************************************************************
; @Date : Sun May 3 21:39:17 GMT 2026
; @Document : extensions__25-6-hints.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T6_extension-hints]
exten => 101,hint,pjsip/T6_101&pjsip/T6_101_1&Custom:T6_DND_101

exten => 102,hint,pjsip/T6_102&Custom:T6_DND_102

exten => 103,hint,Custom:VirtualDev43&Custom:T6_DND_103

exten => 104,hint,pjsip/T6_104&Custom:VirtualDev108&Custom:T6_DND_104

exten => unavailable,hint,T6_unavailable

exten => QAGENT,hint,Custom:T6_QAGENT

exten => 701,hint,park:701@parking-6-parkedcalls

exten => 702,hint,park:702@parking-6-parkedcalls

exten => 703,hint,park:703@parking-6-parkedcalls

exten => 704,hint,park:704@parking-6-parkedcalls

exten => 705,hint,park:705@parking-6-parkedcalls

exten => 706,hint,park:706@parking-6-parkedcalls

exten => 707,hint,park:707@parking-6-parkedcalls

exten => 708,hint,park:708@parking-6-parkedcalls

exten => 709,hint,park:709@parking-6-parkedcalls

exten => 710,hint,park:710@parking-6-parkedcalls

exten => TC3,hint,Custom:TC3
 same => 1,NoOp(Time Condition: Nexus Realty)
 same => n,Gosub(sub-set-global-vars,s,1(32a3be93ff315930,${EXTEN},parking-6))
 same => n,Gosub(sub-set-call-vars,s,1(32a3be93ff315930,${EXTEN},,,))
 same => n,Gosub(sub-construct-cid,s,1)
 same => n,Gosub(sub-toggle-tc-state,s,1(3,TG-3))


