; *********************************************************************************
; @Date : Thu Jun 4 14:04:42 GMT 2026
; @Document : extensions__25-25-hints.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T25_extension-hints]
exten => 1002,hint,Custom:VirtualDev175&Custom:T25_DND_1002

exten => 1003,hint,pjsip/T25_1003&Custom:T25_DND_1003

exten => 101,hint,pjsip/T25_101&pjsip/T25_101_1&Custom:VirtualDev211&Custom:T25_DND_101

exten => unavailable,hint,T25_unavailable

exten => QAGENT,hint,Custom:T25_QAGENT

exten => 701,hint,park:701@parking-25-parkedcalls

exten => 702,hint,park:702@parking-25-parkedcalls

exten => 703,hint,park:703@parking-25-parkedcalls

exten => 704,hint,park:704@parking-25-parkedcalls

exten => 705,hint,park:705@parking-25-parkedcalls

exten => 706,hint,park:706@parking-25-parkedcalls

exten => 707,hint,park:707@parking-25-parkedcalls

exten => 708,hint,park:708@parking-25-parkedcalls

exten => 709,hint,park:709@parking-25-parkedcalls

exten => 710,hint,park:710@parking-25-parkedcalls

exten => TC16,hint,Custom:TC16
 same => 1,NoOp(Time Condition: Main)
 same => n,Gosub(sub-set-global-vars,s,1(fcab1cd3482527c3,${EXTEN},parking-25))
 same => n,Gosub(sub-set-call-vars,s,1(fcab1cd3482527c3,${EXTEN},,,))
 same => n,Gosub(sub-construct-cid,s,1)
 same => n,Gosub(sub-toggle-tc-state,s,1(16,TG-15))


