; *********************************************************************************
; @Date : Thu May 14 17:16:29 GMT 2026
; @Document : extensions__25-9-hints.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T9_extension-hints]
exten => 101,hint,pjsip/T9_101&Custom:T9_DND_101

exten => 102,hint,pjsip/T9_102&Custom:T9_DND_102

exten => 103,hint,pjsip/T9_103&Custom:T9_DND_103

exten => 104,hint,pjsip/T9_104&Custom:VirtualDev76&Custom:T9_DND_104

exten => 105,hint,pjsip/T9_105&Custom:VirtualDev126&Custom:T9_DND_105

exten => 106,hint,pjsip/T9_106&Custom:VirtualDev125&Custom:T9_DND_106

exten => 108,hint,Custom:VirtualDev72&Custom:T9_DND_108

exten => 109,hint,Custom:VirtualDev73&Custom:T9_DND_109

exten => 107,hint,Custom:VirtualDev82&Custom:T9_DND_107

exten => 110,hint,Custom:VirtualDev83&Custom:T9_DND_110

exten => unavailable,hint,T9_unavailable

exten => QAGENT,hint,Custom:T9_QAGENT

exten => 701,hint,park:701@parking-9-parkedcalls

exten => 702,hint,park:702@parking-9-parkedcalls

exten => 703,hint,park:703@parking-9-parkedcalls

exten => 704,hint,park:704@parking-9-parkedcalls

exten => 705,hint,park:705@parking-9-parkedcalls

exten => 706,hint,park:706@parking-9-parkedcalls

exten => 707,hint,park:707@parking-9-parkedcalls

exten => 708,hint,park:708@parking-9-parkedcalls

exten => 709,hint,park:709@parking-9-parkedcalls

exten => 710,hint,park:710@parking-9-parkedcalls

exten => TC5,hint,Custom:TC5
 same => 1,NoOp(Time Condition: Main)
 same => n,Gosub(sub-set-global-vars,s,1(2b9df1ace9927067,${EXTEN},parking-9))
 same => n,Gosub(sub-set-call-vars,s,1(2b9df1ace9927067,${EXTEN},,,))
 same => n,Gosub(sub-construct-cid,s,1)
 same => n,Gosub(sub-toggle-tc-state,s,1(5,TG-6))

exten => TC13,hint,Custom:TC13
 same => 1,NoOp(Time Condition: CS New Job)
 same => n,Gosub(sub-set-global-vars,s,1(2b9df1ace9927067,${EXTEN},parking-9))
 same => n,Gosub(sub-set-call-vars,s,1(2b9df1ace9927067,${EXTEN},,,))
 same => n,Gosub(sub-construct-cid,s,1)
 same => n,Gosub(sub-toggle-tc-state,s,1(13,TG-13))

exten => TC14,hint,Custom:TC14
 same => 1,NoOp(Time Condition: CS Job Update)
 same => n,Gosub(sub-set-global-vars,s,1(2b9df1ace9927067,${EXTEN},parking-9))
 same => n,Gosub(sub-set-call-vars,s,1(2b9df1ace9927067,${EXTEN},,,))
 same => n,Gosub(sub-construct-cid,s,1)
 same => n,Gosub(sub-toggle-tc-state,s,1(14,TG-14))

exten => TC15,hint,Custom:TC15
 same => 1,NoOp(Time Condition: Digital Printing)
 same => n,Gosub(sub-set-global-vars,s,1(2b9df1ace9927067,${EXTEN},parking-9))
 same => n,Gosub(sub-set-call-vars,s,1(2b9df1ace9927067,${EXTEN},,,))
 same => n,Gosub(sub-construct-cid,s,1)
 same => n,Gosub(sub-toggle-tc-state,s,1(15,TG-14))


