[dynamic-routing-out]
exten => s,1,NoOP(Test if save on dynamic routing list)
 same => n,Set(CALLER=${ARG1})
 same => n,Set(CALLED=${ARG2})
 same => n,Set(STATUS=${ARG3})
 same => n,Set(TRKID=${ARG4})
 same => n,Set(ALLOW_DR=${DB(${TENANT}/extensions/${CALLER}/dynamic_routing)})
 same => n,Set(DYNROUTING_OMC=${DB(${TENANT}/dynamic_routing/settings/only_missed_calls)})
 same => n,GotoIf($["${ALLOW_DR}"="yes"]?:comeback)
 same => n,System(/usr/share/vitalpbx/scripts/dynamic_routing "out" "${CALLER}" "${CALLED}" "${STATUS}" "${TRKID}" "${DYNROUTING_OMC}" "${TENANT}")
 same => n(comeback),Return()

[dynamic-routing-in]
exten => s,1,NoOP(Test if must to apply dynamic routing)
 same => n,Set(EXTERNAL_CALLER=${ARG1})
 same => n,Set(DYNROUTING_DM=${DB(${TENANT_PATH}/dynamic_routing/settings/digits_match)})
 same => n,GotoIf($["${DYNROUTING_DM}"="0"]?gd)
 same => n,Set(EXTERNAL_CALLER=${EXTERNAL_CALLER:-${DYNROUTING_DM}})
 same => n(gd),Set(MATCHED_NUMBER=${SHELL(/usr/share/vitalpbx/scripts/dynamic_routing "match_number" "${TENANT_PATH}" "${EXTERNAL_CALLER}" "${DYNROUTING_DM}")})
 same => n,GotoIf($["${MATCHED_NUMBER}"="not_found"]?rb)
 same => n,Set(DESTINATION=${SHELL(/usr/share/vitalpbx/scripts/dynamic_routing "in" "${MATCHED_NUMBER}" "${TENANT_PATH}")})
 same => n,GotoIf($["${DESTINATION}"="nok"]?rb)
 same => n,Set(__DYNROUTING=yes)
 same => n,Goto(${DESTINATION})
 same => n(rb),Return()

[dynamic-routing-connected]
exten => s,1,NoOP(Test if call was completed)
 same => n,Set(STATUS=${ARG1})
 same => n,Set(EXTERNAL_CALLER=${ARG2})
 same => n,Set(DYNROUTING_DM=${DB(${TENANT_PATH}/dynamic_routing/settings/digits_match)})
 same => n,Set(DYNROUTING_DELUSED=${DB(${TENANT_PATH}/dynamic_routing/settings/delete_used_records)})
 same => n,GotoIf($["${DYNROUTING_DM}"="0"]?gd)
 same => n,Set(EXTERNAL_CALLER=${EXTERNAL_CALLER:-${DYNROUTING_DM}})
 same => n(gd),Set(MATCHED_NUMBER=${SHELL(/usr/share/vitalpbx/scripts/dynamic_routing "match_number" "${TENANT_PATH}" "${EXTERNAL_CALLER}" "${DYNROUTING_DM}")})
 same => n,GotoIf($["${MATCHED_NUMBER}"="not_found"]?rb)
 same => n,System(/usr/share/vitalpbx/scripts/dynamic_routing "clean" "${MATCHED_NUMBER}" "${DYNROUTING_DELUSED}" "${STATUS}" "${TENANT_PATH}")
 same => n(rb),Return()