; *********************************************************************************
; @Date : Wed May 20 16:37:17 GMT 2026
; @Document : extensions__25-3-hints.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T3_extension-hints]
exten => 301,hint,pjsip/T3_301&pjsip/T3_301_1&Custom:T3_DND_301

exten => 302,hint,pjsip/T3_302&pjsip/T3_302_1&Custom:T3_DND_302

exten => 305,hint,Custom:VirtualDev84&Custom:T3_DND_305

exten => 103,hint,pjsip/T3_103&Custom:T3_DND_103

exten => 306,hint,Custom:VirtualDev177&Custom:T3_DND_306

exten => 307,hint,pjsip/T3_307&pjsip/T3_307_1&Custom:T3_DND_307

exten => unavailable,hint,T3_unavailable

exten => QAGENT,hint,Custom:T3_QAGENT

exten => 701,hint,park:701@parking-3-parkedcalls

exten => 702,hint,park:702@parking-3-parkedcalls

exten => 703,hint,park:703@parking-3-parkedcalls

exten => 704,hint,park:704@parking-3-parkedcalls

exten => 705,hint,park:705@parking-3-parkedcalls

exten => 706,hint,park:706@parking-3-parkedcalls

exten => 707,hint,park:707@parking-3-parkedcalls

exten => 708,hint,park:708@parking-3-parkedcalls

exten => 709,hint,park:709@parking-3-parkedcalls

exten => 710,hint,park:710@parking-3-parkedcalls

exten => TC7,hint,Custom:TC7
 same => 1,NoOp(Time Condition: Fix Up)
 same => n,Gosub(sub-set-global-vars,s,1(56a4d7cbd1c39e31,${EXTEN},parking-3))
 same => n,Gosub(sub-set-call-vars,s,1(56a4d7cbd1c39e31,${EXTEN},,,))
 same => n,Gosub(sub-construct-cid,s,1)
 same => n,Gosub(sub-toggle-tc-state,s,1(7,TG-7))

exten => TC9,hint,Custom:TC9
 same => 1,NoOp(Time Condition: Fleetease)
 same => n,Gosub(sub-set-global-vars,s,1(56a4d7cbd1c39e31,${EXTEN},parking-3))
 same => n,Gosub(sub-set-call-vars,s,1(56a4d7cbd1c39e31,${EXTEN},,,))
 same => n,Gosub(sub-construct-cid,s,1)
 same => n,Gosub(sub-toggle-tc-state,s,1(9,TG-9))

exten => TC12,hint,Custom:TC12
 same => 1,NoOp(Time Condition: Main)
 same => n,Gosub(sub-set-global-vars,s,1(56a4d7cbd1c39e31,${EXTEN},parking-3))
 same => n,Gosub(sub-set-call-vars,s,1(56a4d7cbd1c39e31,${EXTEN},,,))
 same => n,Gosub(sub-construct-cid,s,1)
 same => n,Gosub(sub-toggle-tc-state,s,1(12,TG-12))


