; *********************************************************************************
; @Date : Sun May 10 19:58:46 GMT 2026
; @Document : extensions__25-7-hints.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T7_extension-hints]
exten => 101,hint,pjsip/T7_101&Custom:T7_DND_101

exten => 102,hint,pjsip/T7_102&pjsip/T7_102_1&Custom:T7_DND_102

exten => 103,hint,pjsip/T7_103&Custom:T7_DND_103

exten => 104,hint,pjsip/T7_104&Custom:T7_DND_104

exten => 105,hint,pjsip/T7_105&Custom:T7_DND_105

exten => 106,hint,pjsip/T7_106&Custom:T7_DND_106

exten => 107,hint,pjsip/T7_107&Custom:T7_DND_107

exten => 108,hint,Custom:VirtualDev31&Custom:T7_DND_108

exten => 109,hint,Custom:VirtualDev32&Custom:T7_DND_109

exten => 110,hint,Custom:VirtualDev156&Custom:T7_DND_110

exten => unavailable,hint,T7_unavailable

exten => QAGENT,hint,Custom:T7_QAGENT

exten => 701,hint,park:701@parking-7-parkedcalls

exten => 702,hint,park:702@parking-7-parkedcalls

exten => 703,hint,park:703@parking-7-parkedcalls

exten => 704,hint,park:704@parking-7-parkedcalls

exten => 705,hint,park:705@parking-7-parkedcalls

exten => 706,hint,park:706@parking-7-parkedcalls

exten => 707,hint,park:707@parking-7-parkedcalls

exten => 708,hint,park:708@parking-7-parkedcalls

exten => 709,hint,park:709@parking-7-parkedcalls

exten => 710,hint,park:710@parking-7-parkedcalls

exten => TC2,hint,Custom:TC2
 same => 1,NoOp(Time Condition: Main)
 same => n,Gosub(sub-set-global-vars,s,1(59943f7a1616b24e,${EXTEN},parking-7))
 same => n,Gosub(sub-set-call-vars,s,1(59943f7a1616b24e,${EXTEN},,,))
 same => n,Gosub(sub-construct-cid,s,1)
 same => n,Gosub(sub-toggle-tc-state,s,1(2,TG-2))


