; *********************************************************************************
; @Date : Sun May 3 21:39:31 GMT 2026
; @Document : manager__50-14-users.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


