[astmanager] ; this must be generated automatically
secret = REDACTED
deny = 0.0.0.0/0.0.0.0
permit= 127.0.0.1/255.255.255.0
read = system,call,command,agent,user,command,reporting,dialplan
write = system,call,command,agent,user,config,command,reporting,cdr,dialplan,originate,message
writetimeout = 60000
eventfilter=!Event: VarSet
eventfilter=!Event: RTCPSent
eventfilter=!Event: RTCPReceived
eventfilter=!Event: RTCP*
eventfilter=!Event: LogChannel
eventfilter=!Event: Verbose
eventfilter=!Event: MessageWaiting
eventfilter=!Event: MWIGet
eventfilter=!Event: ContactStateChange
