; *********************************************************************************
; @Date : Wed Jun 3 0:56:31 GMT 2026
; @Document : manager__50-31-users.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


