; *********************************************************************************
; @Date : Thu May 21 16:43:28 GMT 2026
; @Document : manager__50-29-users.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


