; *********************************************************************************
; @Date : Thu May 21 16:43:28 GMT 2026
; @Document : pjsip__50-29-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T29_101](p1)
type=endpoint
auth=authT29_101
identify_by=username,auth_username
outbound_auth=authT29_101
aors=T29_101
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T29_101
set_var=CHANNEL(parkinglot)=parking-29
subscribe_context=T29_extension-hints
language=en
moh_suggest=default
context=T29_cos-all
mailboxes=101@ny_garden_sprinkler-voicemail
device_state_busy_at=0
callerid="Office" <101>

[authT29_101]
type=auth
auth_type=userpass
username=T29_101
password=REDACTED

[T29_101](p1-aor)
type=aor
max_contacts=5


