; *********************************************************************************
; @Date : Sun May 3 21:39:42 GMT 2026
; @Document : pjsip__50-25-trunks.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

