; *********************************************************************************
; @Date : Thu Jun 4 14:04:42 GMT 2026
; @Document : pjsip__50-25-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T25_1003](p1)
type=endpoint
auth=authT25_1003
identify_by=username,auth_username
outbound_auth=authT25_1003
aors=T25_1003
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T25_1003
set_var=CHANNEL(parkinglot)=parking-25
subscribe_context=T25_extension-hints
language=en
moh_suggest=default
context=T25_cos-all
mailboxes=1003@relax_tires-voicemail
device_state_busy_at=0
callerid="test" <1003>

[authT25_1003]
type=auth
auth_type=userpass
username=T25_1003
password=REDACTED

[T25_1003](p1-aor)
type=aor
max_contacts=5

[T25_101](p1)
type=endpoint
auth=authT25_101
identify_by=username,auth_username
outbound_auth=authT25_101
aors=T25_101
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T25_101
set_var=CHANNEL(parkinglot)=parking-25
subscribe_context=T25_extension-hints
language=en
moh_suggest=default
context=T25_cos-all
mailboxes=101@relax_tires-voicemail
device_state_busy_at=0
callerid="S M Weiss" <101>

[authT25_101]
type=auth
auth_type=userpass
username=T25_101
password=REDACTED

[T25_101](p1-aor)
type=aor
max_contacts=5

[T25_101_1](p12)
type=endpoint
auth=authT25_101_1
identify_by=username,auth_username
outbound_auth=authT25_101_1
aors=T25_101_1
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T25_101_1
set_var=CHANNEL(parkinglot)=parking-25
subscribe_context=T25_extension-hints
language=en
moh_suggest=default
context=T25_cos-all
mailboxes=101@relax_tires-voicemail
device_state_busy_at=0
callerid="S M Weiss" <101>

[authT25_101_1]
type=auth
auth_type=userpass
username=T25_101_1
password=REDACTED

[T25_101_1](p12-aor)
type=aor
max_contacts=3


