; *********************************************************************************
; @Date : Thu May 21 16:43:10 GMT 2026
; @Document : pjsip__50-28-trunks.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

