; *********************************************************************************
; @Date : Sun May 3 21:39:31 GMT 2026
; @Document : pjsip__50-14-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T14_101](p1)
type=endpoint
auth=authT14_101
identify_by=username,auth_username
outbound_auth=authT14_101
aors=T14_101
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T14_101
set_var=CHANNEL(parkinglot)=parking-14
subscribe_context=T14_extension-hints
language=en
moh_suggest=default
context=T14_cos-all
mailboxes=101@solidify_concrete-voicemail
device_state_busy_at=0
callerid="Shlomo" <101>

[authT14_101]
type=auth
auth_type=userpass
username=T14_101
password=REDACTED

[T14_101](p1-aor)
type=aor
max_contacts=5

[T14_102](p1)
type=endpoint
auth=authT14_102
identify_by=username,auth_username
outbound_auth=authT14_102
aors=T14_102
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T14_102
set_var=CHANNEL(parkinglot)=parking-14
subscribe_context=T14_extension-hints
language=en
moh_suggest=default
context=T14_cos-all
mailboxes=102@solidify_concrete-voicemail
device_state_busy_at=0
callerid="Office" <102>

[authT14_102]
type=auth
auth_type=userpass
username=T14_102
password=REDACTED

[T14_102](p1-aor)
type=aor
max_contacts=5

[T14_101_1](p12)
type=endpoint
auth=authT14_101_1
identify_by=username,auth_username
outbound_auth=authT14_101_1
aors=T14_101_1
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T14_101_1
set_var=CHANNEL(parkinglot)=parking-14
subscribe_context=T14_extension-hints
language=en
moh_suggest=default
context=T14_cos-all
mailboxes=101@solidify_concrete-voicemail
device_state_busy_at=0
callerid="Shlomo" <101>

[authT14_101_1]
type=auth
auth_type=userpass
username=T14_101_1
password=REDACTED

[T14_101_1](p12-aor)
type=aor
max_contacts=1

[T14_102_1](p12)
type=endpoint
auth=authT14_102_1
identify_by=username,auth_username
outbound_auth=authT14_102_1
aors=T14_102_1
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T14_102_1
set_var=CHANNEL(parkinglot)=parking-14
subscribe_context=T14_extension-hints
language=en
moh_suggest=default
context=T14_cos-all
mailboxes=102@solidify_concrete-voicemail
device_state_busy_at=0
callerid="Office" <102>

[authT14_102_1]
type=auth
auth_type=userpass
username=T14_102_1
password=REDACTED

[T14_102_1](p12-aor)
type=aor
max_contacts=1


