; *********************************************************************************
; @Date : Sun May 3 21:39:16 GMT 2026
; @Document : pjsip__50-6-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T6_101](p1)
type=endpoint
auth=authT6_101
identify_by=username,auth_username
outbound_auth=authT6_101
aors=T6_101
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T6_101
set_var=CHANNEL(parkinglot)=parking-6
subscribe_context=T6_extension-hints
language=en
moh_suggest=default
context=T6_cos-all
mailboxes=101@displaydex-voicemail
device_state_busy_at=0
callerid="Eli Lovi" <101>

[authT6_101]
type=auth
auth_type=userpass
username=T6_101
password=REDACTED

[T6_101](p1-aor)
type=aor
max_contacts=5

[T6_102](p1)
type=endpoint
auth=authT6_102
identify_by=username,auth_username
outbound_auth=authT6_102
aors=T6_102
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T6_102
set_var=CHANNEL(parkinglot)=parking-6
subscribe_context=T6_extension-hints
language=en
moh_suggest=default
context=T6_cos-all
mailboxes=102@displaydex-voicemail
device_state_busy_at=0
callerid="Michael Ffromowitz" <102>

[authT6_102]
type=auth
auth_type=userpass
username=T6_102
password=REDACTED

[T6_102](p1-aor)
type=aor
max_contacts=5

[T6_104](p1)
type=endpoint
auth=authT6_104
identify_by=username,auth_username
outbound_auth=authT6_104
aors=T6_104
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T6_104
set_var=CHANNEL(parkinglot)=parking-6
subscribe_context=T6_extension-hints
language=en
moh_suggest=default
context=T6_cos-all
mailboxes=104@displaydex-voicemail
device_state_busy_at=0
callerid="Yehuda Tyberg" <104>

[authT6_104]
type=auth
auth_type=userpass
username=T6_104
password=REDACTED

[T6_104](p1-aor)
type=aor
max_contacts=5

[T6_101_1](p12)
type=endpoint
auth=authT6_101_1
identify_by=username,auth_username
outbound_auth=authT6_101_1
aors=T6_101_1
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T6_101_1
set_var=CHANNEL(parkinglot)=parking-6
subscribe_context=T6_extension-hints
language=en
moh_suggest=default
context=T6_cos-all
mailboxes=101@displaydex-voicemail
device_state_busy_at=0
callerid="Eli Lovi" <101>

[authT6_101_1]
type=auth
auth_type=userpass
username=T6_101_1
password=REDACTED

[T6_101_1](p12-aor)
type=aor
max_contacts=1


