; *********************************************************************************
; @Date : Sun May 3 21:39:31 GMT 2026
; @Document : pjsip__50-14-trunks.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

