; *********************************************************************************
; @Date : Sun May 3 21:39:35 GMT 2026
; @Document : pjsip__50-20-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T20_102](p1)
type=endpoint
auth=authT20_102
identify_by=username,auth_username
outbound_auth=authT20_102
aors=T20_102
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T20_102
set_var=CHANNEL(parkinglot)=parking-20
subscribe_context=T20_extension-hints
language=en
moh_suggest=default
context=T20_cos-all
mailboxes=102@smooth_leasing-voicemail
device_state_busy_at=0
callerid="Secretary" <102>

[authT20_102]
type=auth
auth_type=userpass
username=T20_102
password=REDACTED

[T20_102](p1-aor)
type=aor
max_contacts=1


