[general]
persistentmembers = yes
autofill = yes
monitor-type = MixMonitor
updatecdr = no
shared_lastcall= yes
negative_penalty_invalid = no
log_membername_as_agent = no
force_longest_waiting_caller = no