; *********************************************************************************
; @Date : Sun May 3 21:39:14 GMT 2026
; @Document : queues__50-5-main.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


