; *********************************************************************************
; @Date : Thu Jun 4 10:46:32 GMT 2026
; @Document : queues__50-2-main.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T2_Q600]
setqueueentryvar=yes
setqueuevar=yes
timeoutpriority=app
strategy=linear
musicclass=default
autofill=yes
maxlen=0
announce=
wrapuptime=0
announce-round-seconds=0
announce-to-first-user=no
announce-position=no
relative-periodic-announce=yes
announce-holdtime=no
autopause=no
ringinuse=yes
timeoutrestart=no
joinempty=yes
timeout=15
leavewhenempty=no
retry=5
queue-thankyou=

