; *********************************************************************************
; @Date : Thu May 28 5:47:38 GMT 2026
; @Document : queues__50-1-main.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


