/**
 * Billing report helpers — read-only SELECT queries + CSV serialisation.
 *
 * All functions accept an injected `db` so they are unit-testable without a
 * live Postgres connection (same pattern as adminCardSave.ts).
 *
 * Safety:
 *  - Row caps prevent runaway queries on large datasets.
 *  - CSV cells are sanitised against formula-injection (cells that start with
 *    =, +, -, @, TAB, or CR are prefixed with a single-quote).
 *  - The CSV body is returned as a plain string; callers set the Fastify reply
 *    headers so nothing here touches HTTP concerns.
 */

// ── Row-cap constants ─────────────────────────────────────────────────────────

export const AGING_ROW_CAP = 2_000;
export const FAILED_PAYMENTS_ROW_CAP = 1_000;
export const INVOICE_EXPORT_ROW_CAP = 5_000;
export const TX_EXPORT_ROW_CAP = 5_000;

// ── Types ─────────────────────────────────────────────────────────────────────

export type AgingRow = {
  invoiceId: string;
  invoiceNumber: string | null;
  tenantId: string;
  tenantName: string;
  status: string;
  dueDate: Date | null;
  daysOverdue: number;
  balanceDueCents: number;
  totalCents: number;
  createdAt: Date;
};

export type FailedPaymentRow = {
  invoiceId: string;
  invoiceNumber: string | null;
  tenantId: string;
  tenantName: string;
  totalCents: number;
  balanceDueCents: number;
  status: string;
  lastFailureReason: string | null;
  lastResponseCode: string | null;
  lastAttemptAt: Date | null;
  failedAt: Date | null;
};

export type InvoiceExportRow = {
  invoiceNumber: string | null;
  tenantName: string;
  status: string;
  periodStart: Date | null;
  periodEnd: Date | null;
  issueDate: Date | null;
  dueDate: Date | null;
  paidAt: Date | null;
  subtotalCents: number;
  taxCents: number;
  totalCents: number;
  balanceDueCents: number;
  cardBrand: string | null;
  cardLast4: string | null;
};

export type TxExportRow = {
  createdAt: Date;
  tenantName: string;
  invoiceNumber: string | null;
  amountCents: number;
  status: string;
  processorTransactionId: string | null;
  cardBrand: string | null;
  cardLast4: string | null;
  responseCode: string | null;
  responseMessage: string | null;
};

export type ReportDb = {
  billingInvoice: {
    findMany(args: unknown): Promise<unknown[]>;
  };
  paymentTransaction: {
    findMany(args: unknown): Promise<unknown[]>;
  };
};

// ── Days-overdue helper ───────────────────────────────────────────────────────

export function computeDaysOverdue(dueDate: Date | null, status: string, now: Date = new Date()): number {
  if (!dueDate) return 0;
  if (status === "PAID" || status === "VOID" || status === "DRAFT") return 0;
  const ms = now.getTime() - dueDate.getTime();
  return ms > 0 ? Math.floor(ms / (1000 * 60 * 60 * 24)) : 0;
}

// ── CSV cell sanitisation ─────────────────────────────────────────────────────

/**
 * Sanitise a single CSV cell value:
 *  - Converts to string (null/undefined → "")
 *  - Prefixes formula-injection starters (= + - @ TAB CR) with a single-quote
 *  - Wraps in double-quotes if the value contains commas, double-quotes, or newlines
 *  - Escapes embedded double-quotes by doubling them
 */
export function csvCell(value: unknown): string {
  if (value === null || value === undefined) return "";
  const s = String(value);
  // CSV injection defence: prefix with single-quote when the cell would be
  // interpreted as a formula by Excel / Sheets.
  const FORMULA_STARTERS = /^[=+\-@\t\r]/;
  const safe = FORMULA_STARTERS.test(s) ? `'${s}` : s;
  // If the value needs quoting, wrap in double-quotes and escape internal ones
  if (safe.includes(",") || safe.includes('"') || safe.includes("\n") || safe.includes("\r")) {
    return `"${safe.replace(/"/g, '""')}"`;
  }
  return safe;
}

export function csvRow(cells: unknown[]): string {
  return cells.map(csvCell).join(",");
}

// ── Date formatting ───────────────────────────────────────────────────────────

export function fmtIso(d: Date | null | undefined): string {
  if (!d) return "";
  return d instanceof Date ? d.toISOString().slice(0, 10) : String(d).slice(0, 10);
}

export function fmtDatetime(d: Date | null | undefined): string {
  if (!d) return "";
  return d instanceof Date ? d.toISOString().replace("T", " ").slice(0, 19) + " UTC" : String(d);
}

function centsToDollars(cents: number): string {
  return (cents / 100).toFixed(2);
}

// ── CSV header metadata rows ──────────────────────────────────────────────────

export function csvMeta(reportName: string, generatedBy: string): string {
  const now = new Date();
  return [
    csvRow(["# Report", reportName]),
    csvRow(["# Generated At", fmtDatetime(now)]),
    csvRow(["# Generated By", generatedBy]),
    "",
  ].join("\n");
}

// ── Today's date for filename suffix ─────────────────────────────────────────

export function todayDateSuffix(): string {
  return new Date().toISOString().slice(0, 10); // YYYY-MM-DD
}

// ── Aging report ─────────────────────────────────────────────────────────────

export type BillingReportScope = { tenantId?: string };

export async function queryAgingReport(
  reportDb: ReportDb,
  scope: BillingReportScope = {},
): Promise<{ rows: AgingRow[]; capped: boolean }> {
  const raw = await reportDb.billingInvoice.findMany({
    where: {
      status: { in: ["OPEN", "FAILED", "OVERDUE"] },
      balanceDueCents: { gt: 0 },
      ...(scope.tenantId ? { tenantId: scope.tenantId } : {}),
    },
    orderBy: [{ dueDate: "asc" }],
    take: AGING_ROW_CAP + 1,
    select: {
      id: true,
      invoiceNumber: true,
      tenantId: true,
      status: true,
      dueDate: true,
      balanceDueCents: true,
      totalCents: true,
      createdAt: true,
      tenant: { select: { name: true } },
    },
  }) as any[];

  const capped = raw.length > AGING_ROW_CAP;
  const slice = raw.slice(0, AGING_ROW_CAP);

  const now = new Date();
  const rows: AgingRow[] = slice.map((r: any) => ({
    invoiceId: r.id,
    invoiceNumber: r.invoiceNumber,
    tenantId: r.tenantId,
    tenantName: r.tenant?.name ?? r.tenantId,
    status: r.status,
    dueDate: r.dueDate ? new Date(r.dueDate) : null,
    daysOverdue: computeDaysOverdue(r.dueDate ? new Date(r.dueDate) : null, r.status, now),
    balanceDueCents: r.balanceDueCents,
    totalCents: r.totalCents,
    createdAt: new Date(r.createdAt),
  }));

  return { rows, capped };
}

export function agingToCsv(rows: AgingRow[], meta: string): string {
  const header = csvRow(["Tenant", "Invoice #", "Status", "Due Date", "Days Overdue", "Balance Due", "Total"]);
  const dataRows = rows.map((r) =>
    csvRow([
      r.tenantName,
      r.invoiceNumber ?? "",
      r.status,
      fmtIso(r.dueDate),
      r.daysOverdue,
      centsToDollars(r.balanceDueCents),
      centsToDollars(r.totalCents),
    ]),
  );
  return [meta, header, ...dataRows].join("\n");
}

// ── Failed payments report ────────────────────────────────────────────────────

export async function queryFailedPaymentsReport(
  reportDb: ReportDb,
  scope: BillingReportScope = {},
): Promise<{ rows: FailedPaymentRow[]; capped: boolean }> {
  const raw = await reportDb.billingInvoice.findMany({
    where: {
      status: { in: ["FAILED", "OVERDUE"] },
      ...(scope.tenantId ? { tenantId: scope.tenantId } : {}),
    },
    orderBy: [{ failedAt: "desc" }, { dueDate: "asc" }],
    take: FAILED_PAYMENTS_ROW_CAP + 1,
    select: {
      id: true,
      invoiceNumber: true,
      tenantId: true,
      status: true,
      totalCents: true,
      balanceDueCents: true,
      failedAt: true,
      tenant: { select: { name: true } },
      transactions: {
        where: { status: { in: ["DECLINED", "ERROR"] } },
        orderBy: { createdAt: "desc" },
        take: 1,
        select: { responseMessage: true, responseCode: true, createdAt: true },
      },
    },
  }) as any[];

  const capped = raw.length > FAILED_PAYMENTS_ROW_CAP;
  const slice = raw.slice(0, FAILED_PAYMENTS_ROW_CAP);

  const rows: FailedPaymentRow[] = slice.map((r: any) => {
    const lastTx = r.transactions?.[0] ?? null;
    return {
      invoiceId: r.id,
      invoiceNumber: r.invoiceNumber,
      tenantId: r.tenantId,
      tenantName: r.tenant?.name ?? r.tenantId,
      totalCents: r.totalCents,
      balanceDueCents: r.balanceDueCents,
      status: r.status,
      lastFailureReason: lastTx?.responseMessage ?? null,
      lastResponseCode: lastTx?.responseCode ?? null,
      lastAttemptAt: lastTx?.createdAt ? new Date(lastTx.createdAt) : null,
      failedAt: r.failedAt ? new Date(r.failedAt) : null,
    };
  });

  return { rows, capped };
}

export function failedPaymentsToCsv(rows: FailedPaymentRow[], meta: string): string {
  const header = csvRow(["Tenant", "Invoice #", "Status", "Total", "Balance Due", "Last Failure Reason", "Response Code", "Last Attempt", "Failed At"]);
  const dataRows = rows.map((r) =>
    csvRow([
      r.tenantName,
      r.invoiceNumber ?? "",
      r.status,
      centsToDollars(r.totalCents),
      centsToDollars(r.balanceDueCents),
      r.lastFailureReason ?? "",
      r.lastResponseCode ?? "",
      fmtDatetime(r.lastAttemptAt),
      fmtDatetime(r.failedAt),
    ]),
  );
  return [meta, header, ...dataRows].join("\n");
}

// ── Invoice export ────────────────────────────────────────────────────────────

export async function queryInvoiceExport(
  reportDb: ReportDb,
  filters: { status?: string; tenantId?: string },
): Promise<{ rows: InvoiceExportRow[]; capped: boolean }> {
  const where: Record<string, unknown> = {};
  if (filters.status && filters.status !== "ALL") where.status = filters.status;
  if (filters.tenantId) where.tenantId = filters.tenantId;

  const raw = await reportDb.billingInvoice.findMany({
    where,
    orderBy: { createdAt: "desc" },
    take: INVOICE_EXPORT_ROW_CAP + 1,
    select: {
      invoiceNumber: true,
      status: true,
      periodStart: true,
      periodEnd: true,
      issueDate: true,
      dueDate: true,
      paidAt: true,
      subtotalCents: true,
      taxCents: true,
      totalCents: true,
      balanceDueCents: true,
      tenant: { select: { name: true } },
      paymentMethod: { select: { brand: true, last4: true } },
    },
  }) as any[];

  const capped = raw.length > INVOICE_EXPORT_ROW_CAP;
  const slice = raw.slice(0, INVOICE_EXPORT_ROW_CAP);

  const rows: InvoiceExportRow[] = slice.map((r: any) => ({
    invoiceNumber: r.invoiceNumber,
    tenantName: r.tenant?.name ?? "",
    status: r.status,
    periodStart: r.periodStart ? new Date(r.periodStart) : null,
    periodEnd: r.periodEnd ? new Date(r.periodEnd) : null,
    issueDate: r.issueDate ? new Date(r.issueDate) : null,
    dueDate: r.dueDate ? new Date(r.dueDate) : null,
    paidAt: r.paidAt ? new Date(r.paidAt) : null,
    subtotalCents: r.subtotalCents,
    taxCents: r.taxCents,
    totalCents: r.totalCents,
    balanceDueCents: r.balanceDueCents,
    cardBrand: r.paymentMethod?.brand ?? null,
    cardLast4: r.paymentMethod?.last4 ?? null,
  }));

  return { rows, capped };
}

export function invoiceExportToCsv(rows: InvoiceExportRow[], meta: string): string {
  const header = csvRow([
    "Invoice #", "Tenant", "Status",
    "Period Start", "Period End", "Issue Date", "Due Date", "Paid At",
    "Subtotal", "Tax", "Total", "Balance Due",
    "Card Brand", "Card Last4",
  ]);
  const dataRows = rows.map((r) =>
    csvRow([
      r.invoiceNumber ?? "",
      r.tenantName,
      r.status,
      fmtIso(r.periodStart),
      fmtIso(r.periodEnd),
      fmtIso(r.issueDate),
      fmtIso(r.dueDate),
      fmtIso(r.paidAt),
      centsToDollars(r.subtotalCents),
      centsToDollars(r.taxCents),
      centsToDollars(r.totalCents),
      centsToDollars(r.balanceDueCents),
      r.cardBrand ?? "",
      r.cardLast4 ?? "",
    ]),
  );
  return [meta, header, ...dataRows].join("\n");
}

// ── Transaction export ────────────────────────────────────────────────────────

export async function queryTransactionExport(
  reportDb: ReportDb,
  filters: { status?: string; tenantId?: string },
): Promise<{ rows: TxExportRow[]; capped: boolean }> {
  const where: Record<string, unknown> = {};
  if (filters.status && filters.status !== "ALL") where.status = filters.status;
  if (filters.tenantId) where.tenantId = filters.tenantId;

  const raw = await reportDb.paymentTransaction.findMany({
    where,
    orderBy: { createdAt: "desc" },
    take: TX_EXPORT_ROW_CAP + 1,
    select: {
      createdAt: true,
      amountCents: true,
      status: true,
      processorTransactionId: true,
      responseCode: true,
      responseMessage: true,
      tenant: { select: { name: true } },
      invoice: { select: { invoiceNumber: true } },
      paymentMethod: { select: { brand: true, last4: true } },
    },
  }) as any[];

  const capped = raw.length > TX_EXPORT_ROW_CAP;
  const slice = raw.slice(0, TX_EXPORT_ROW_CAP);

  const rows: TxExportRow[] = slice.map((r: any) => ({
    createdAt: new Date(r.createdAt),
    tenantName: r.tenant?.name ?? "",
    invoiceNumber: r.invoice?.invoiceNumber ?? null,
    amountCents: r.amountCents,
    status: r.status,
    processorTransactionId: r.processorTransactionId ?? null,
    cardBrand: r.paymentMethod?.brand ?? null,
    cardLast4: r.paymentMethod?.last4 ?? null,
    responseCode: r.responseCode ?? null,
    responseMessage: r.responseMessage ?? null,
  }));

  return { rows, capped };
}

export function transactionExportToCsv(rows: TxExportRow[], meta: string): string {
  const header = csvRow([
    "Date", "Tenant", "Invoice #", "Amount", "Status",
    "Processor Ref", "Card Brand", "Card Last4",
    "Response Code", "Response Message",
  ]);
  const dataRows = rows.map((r) =>
    csvRow([
      fmtDatetime(r.createdAt),
      r.tenantName,
      r.invoiceNumber ?? "",
      centsToDollars(r.amountCents),
      r.status,
      r.processorTransactionId ?? "",
      r.cardBrand ?? "",
      r.cardLast4 ?? "",
      r.responseCode ?? "",
      r.responseMessage ?? "",
    ]),
  );
  return [meta, header, ...dataRows].join("\n");
}
