/**
 * SMS-to-email reply routing — the PURE half of Part 3 (reply-to-text-back).
 *
 * The forward job puts `Reply-To: sms+<threadId>.<sig>@<replyDomain>` on every
 * SMS email (Gmail plus-addressing delivers that to the base mailbox, e.g.
 * sms@loopcom.net). This module owns:
 *
 *   • minting that address (the forward job calls mintSmsReplyAddress, so the
 *     mint and the verify can NEVER drift apart), and verifying it —
 *     HMAC-SHA256 over the threadId, base64url, first 24 chars, timing-safe
 *     compare. The address is the capability: only someone who received the
 *     forward email holds it.
 *   • pulling a person's actual words out of a reply email — mail clients bury
 *     them under quoted history, signatures and "Sent from my iPhone" lines,
 *     and every one of those would otherwise be TEXTED TO A CUSTOMER.
 *   • recognising auto-generated mail (out-of-office, bounces). An OOO
 *     responder replying to a forward must never become an SMS.
 *
 * ⛔ Nothing here transforms the message body's language or content — Yiddish
 * (or any RTL text) passes through byte-for-byte. Stripping only ever CUTS
 * whole trailing sections, it never rewrites a line the person typed.
 */
import { createHmac, timingSafeEqual } from "node:crypto";

const b64url = (b: Buffer) => b.toString("base64").replace(/=+$/g, "").replace(/\+/g, "-").replace(/\//g, "_");

export const SMS_REPLY_SIG_LENGTH = 24;

/** The signature half of the reply address. Byte-identical to what the forward job has always minted. */
export function mintSmsReplySignature(threadId: string, secret: string): string {
  return b64url(createHmac("sha256", secret).update(threadId).digest()).slice(0, SMS_REPLY_SIG_LENGTH);
}

/** Full reply address, e.g. `sms+cmxyz.AbC-12@loopcom.net`. */
export function mintSmsReplyAddress(threadId: string, secret: string, domain: string): string {
  return `sms+${threadId}.${mintSmsReplySignature(threadId, secret)}@${domain}`;
}

export interface ParsedSmsReplyAddress {
  threadId: string;
  sig: string;
  domain: string;
}

/** Parse one address of the `sms+<threadId>.<sig>@<domain>` shape. Null when it isn't one. */
export function parseSmsReplyAddress(address: string): ParsedSmsReplyAddress | null {
  const m = /^sms\+([A-Za-z0-9]+)\.([A-Za-z0-9_-]{16,64})@([^@\s]+)$/i.exec(String(address || "").trim());
  if (!m) return null;
  return { threadId: m[1], sig: m[2], domain: m[3].toLowerCase() };
}

/**
 * Find the reply address among every recipient address a mail carried
 * (To, Cc, Delivered-To, X-Original-To, envelope). Bound to OUR reply domain —
 * a token minted for another deployment's domain is not ours to honour.
 */
export function findSmsReplyAddress(candidates: string[], replyDomain: string): ParsedSmsReplyAddress | null {
  const want = String(replyDomain || "").trim().toLowerCase();
  if (!want) return null;
  for (const c of candidates || []) {
    const parsed = parseSmsReplyAddress(c);
    if (parsed && parsed.domain === want) return parsed;
  }
  return null;
}

/** Timing-safe signature check. */
export function verifySmsReplySignature(threadId: string, sig: string, secret: string): boolean {
  if (!threadId || !sig || !secret) return false;
  const expected = mintSmsReplySignature(threadId, secret);
  const a = Buffer.from(expected);
  const b = Buffer.from(String(sig));
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

/**
 * True for mail no human wrote — vacation responders, bounces, list mail.
 * `headers` keys must be lower-cased. Texting an out-of-office blurb to a
 * customer is the failure this exists to prevent.
 */
export function isAutoGeneratedEmail(headers: Record<string, string>, subject: string): boolean {
  const h = (name: string) => String(headers?.[name] ?? "").trim().toLowerCase();
  const autoSubmitted = h("auto-submitted");
  if (autoSubmitted && autoSubmitted !== "no") return true;
  const precedence = h("precedence");
  if (precedence === "bulk" || precedence === "junk" || precedence === "auto_reply" || precedence === "list") return true;
  if (headers && ("x-autoreply" in headers || "x-autorespond" in headers)) return true;
  if (h("x-auto-response-suppress")) return true;
  if (h("return-path") === "<>") return true; // bounce
  const subj = String(subject || "").trim().toLowerCase();
  if (/^(automatic reply|auto(-|\s)?reply|out of office|autosvar|automatische antwort|réponse automatique)/i.test(subj)) return true;
  if (/^(delivery status notification|undeliverable|mail delivery failed)/i.test(subj)) return true;
  return false;
}

// ── reply-text extraction ─────────────────────────────────────────────────────

/** Very small HTML→text for replies that carry no text/plain part. */
export function htmlToReplyText(html: string): string {
  let s = String(html || "");
  // Gmail wraps the quoted history in a well-known container — drop it whole.
  s = s.replace(/<(div|blockquote)[^>]*class="[^"]*gmail_quote[^"]*"[\s\S]*$/i, "");
  s = s.replace(/<blockquote[\s\S]*$/i, "");
  s = s.replace(/<style[\s\S]*?<\/style>/gi, "").replace(/<script[\s\S]*?<\/script>/gi, "");
  s = s.replace(/<br\s*\/?>(\n)?/gi, "\n").replace(/<\/(p|div|tr|li|h[1-6])>/gi, "\n");
  s = s.replace(/<[^>]+>/g, "");
  s = s
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/gi, "'");
  return s;
}

const ATTRIBUTION_RE = /^On .{0,300}wrote:\s*$/; // "On Tue, Aug 20 ... <x@y> wrote:"
const ORIGINAL_MESSAGE_RE = /^\s*-{2,}\s*(Original|Forwarded) Message\s*-{2,}\s*$/i;
const OUTLOOK_DIVIDER_RE = /^_{5,}\s*$/;
const SIGNATURE_RE = /^--\s*$/;
const SENT_FROM_RE = /^(sent from my|get outlook for)/i;

/**
 * The person's own words, with quoted history / signatures / client footers cut
 * off. Prefers the text/plain part; falls back to a crude HTML conversion.
 * Returns "" when nothing human remains.
 */
export function extractSmsReplyText(text: string | null | undefined, html?: string | null): string {
  let raw = String(text ?? "").trim() ? String(text) : htmlToReplyText(String(html ?? ""));
  raw = raw.replace(/\r\n/g, "\n");
  const lines = raw.split("\n");
  const kept: string[] = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    // Gmail attribution ("On ... wrote:") — may wrap onto a second/third line.
    // ⛔ Join only CONSECUTIVE NON-EMPTY lines: a real attribution never wraps
    // across a blank line, while a person's own message may well START with
    // "On my way" right above the quoted block.
    if (/^On\b/.test(trimmed)) {
      let joined = trimmed;
      let isAttribution = ATTRIBUTION_RE.test(joined);
      for (let j = i + 1; !isAttribution && j <= i + 2; j++) {
        const cont = lines[j]?.trim();
        if (!cont) break;
        joined = `${joined} ${cont}`;
        isAttribution = /^On .{0,400}wrote:$/.test(joined);
      }
      if (isAttribution) break;
    }
    if (ORIGINAL_MESSAGE_RE.test(trimmed) || OUTLOOK_DIVIDER_RE.test(trimmed)) break;
    // Outlook top-posting block: "From: ..." followed shortly by Sent:/Date:/To:
    if (/^From:\s*.+$/i.test(trimmed)) {
      const next = [lines[i + 1]?.trim() ?? "", lines[i + 2]?.trim() ?? ""];
      if (next.some((n) => /^(Sent|Date|To):\s/i.test(n))) break;
    }
    if (trimmed.startsWith(">")) break; // plain quoted block
    if (SIGNATURE_RE.test(line)) break; // "-- " signature divider
    kept.push(line);
  }

  // Drop trailing client footers ("Sent from my iPhone") and blank lines.
  while (kept.length > 0) {
    const last = kept[kept.length - 1].trim();
    if (!last || SENT_FROM_RE.test(last)) kept.pop();
    else break;
  }

  return kept.join("\n").replace(/\n{3,}/g, "\n\n").trim();
}
