/**
 * SMS-to-email REPLY job — Part 3 of the bridge (reply-to-text-back).
 *
 * The forward job (smsEmailForwardJob.ts) emails inbound texts out with
 * `Reply-To: sms+<threadId>.<sig>@<replyDomain>`. This job reads the bridge
 * mailbox (sms@loopcom.net via the injected source), and for each reply:
 * verify the signed address → match the sender to an opted-in participant →
 * strip the quoted history → send the words as a TEXT through the REAL portal
 * route (`POST /chat/threads/:id/messages`) under a short-lived JWT minted for
 * THAT user. Reusing the real route is the point: participant checks, the
 * can_send_sms permission, outbound-number resolution, MMS/segment handling and
 * delivery tracking all stay in one implementation, and the reply shows up in
 * the app attributed to the person who wrote it — never to a robot.
 *
 * Failure directions, chosen deliberately:
 *   • An email that is not a reply (no signed address) is ignored quietly —
 *     the bridge mailbox will collect spam, and spam must not generate mail.
 *   • A STRANGER whose From matches no opted-in participant gets NOTHING back
 *     (no backscatter, no oracle); the refusal is audited.
 *   • A KNOWN user whose reply cannot be sent (toggle off, no permission, empty
 *     body, api refusal, api unreachable) IS told, by a threaded notice email —
 *     they believe they just texted a customer; silence would be a lie.
 *   • A send is CLAIMED in AgentAuditLog before the POST and never auto-retried
 *     after a crash — an ambiguous half-send becomes a notice, not a duplicate
 *     text (the "a purchase is never retried" rule).
 */
import { createHmac } from "node:crypto";
import type { AuditLog } from "../audit/audit";
import type { Notifier } from "./notifier";
import { findSmsReplyAddress, verifySmsReplySignature, isAutoGeneratedEmail, extractSmsReplyText } from "./smsEmailReply";
import { formatSmsPhone } from "./smsEmail";

const b64url = (b: Buffer) => b.toString("base64").replace(/=+$/g, "").replace(/\+/g, "-").replace(/\//g, "_");

/** One parsed email out of the bridge mailbox. Header keys are lower-cased. */
export interface SmsReplyEmail {
  /** Mailbox-local id (IMAP UID as a string). */
  id: string;
  messageId: string | null;
  /** Sender address only (no display name). */
  from: string | null;
  /** Every recipient address the mail carried (To/Cc/Delivered-To/X-Original-To). */
  to: string[];
  subject: string;
  text: string | null;
  html: string | null;
  headers: Record<string, string>;
}

export interface SmsReplyEmailSource {
  /**
   * One pass over unprocessed mail. Calls `handler` per email; a `true` return
   * marks that email processed (never seen again), `false`/throw leaves it for
   * the next pass. Returns how many emails were handled.
   */
  poll(handler: (email: SmsReplyEmail) => Promise<boolean>): Promise<number>;
}

export interface SmsEmailReplyJobDeps {
  prisma: any;
  audit: AuditLog;
  /** The SMS-bridge notifier (sends AS the bridge mailbox) — used only for failure notices. */
  notifier: Notifier;
  source: SmsReplyEmailSource;
  replyDomain: () => string | null;
  replySecret: () => string | null;
  /** Same JWT_SECRET the portal api verifies with. */
  jwtSecret: () => string | null;
  apiBaseUrl: () => string;
  /** Domain for threading Message-IDs — must match the forward job's. */
  messageIdDomain: () => string;
  fetchImpl?: typeof fetch;
  brandName?: string;
}

/** Longer than any reasonable text; the api's own validation governs below this. */
const MAX_REPLY_CHARS = 4000;

export class SmsEmailReplyJob {
  private running = false;
  constructor(private deps: SmsEmailReplyJobDeps) {}

  /** One polling pass. Returns how many replies became texts. */
  async runOnce(): Promise<number> {
    if (this.running) return 0;
    if (!this.deps.replyDomain() || !this.deps.replySecret() || !this.deps.jwtSecret()) return 0;
    this.running = true;
    let sent = 0;
    try {
      await this.deps.source.poll(async (email) => {
        const outcome = await this.processOne(email);
        if (outcome === "sent") sent++;
        return outcome !== "retry";
      });
      return sent;
    } finally {
      this.running = false;
    }
  }

  private async processOne(email: SmsReplyEmail): Promise<"sent" | "dropped" | "retry"> {
    const audit = (event: string, payload: Record<string, unknown>) =>
      this.deps.audit.record({ actor: "system", event, payload: { emailId: email.id, messageId: email.messageId, ...payload } }).catch(() => {});

    // 1) Is this a reply to one of our forwards at all?
    const parsed = findSmsReplyAddress(email.to, this.deps.replyDomain() || "");
    if (!parsed) {
      await audit("sms.reply_ignored", { reason: "no_reply_address", from: email.from });
      return "dropped";
    }
    if (!verifySmsReplySignature(parsed.threadId, parsed.sig, this.deps.replySecret() || "")) {
      await audit("sms.reply_ignored", { reason: "bad_signature", from: email.from, threadId: parsed.threadId });
      return "dropped";
    }
    // 2) Never text an auto-responder's blurb to a customer.
    if (isAutoGeneratedEmail(email.headers, email.subject)) {
      await audit("sms.reply_ignored", { reason: "auto_generated", from: email.from, threadId: parsed.threadId });
      return "dropped";
    }

    const thread = await this.deps.prisma.connectChatThread.findUnique({
      where: { id: parsed.threadId },
      select: { id: true, type: true, tenantId: true, externalSmsE164: true, tenantSmsE164: true },
    });
    if (!thread || thread.type !== "SMS") {
      await audit("sms.reply_refused", { reason: "thread_gone", threadId: parsed.threadId, from: email.from });
      return "dropped";
    }

    // 3) The From must be a real, ACTIVE user of the thread's tenant. A stranger
    //    is told nothing — replying to a leaked address must not become an oracle.
    const fromEmail = String(email.from || "").trim().toLowerCase();
    const user = fromEmail.includes("@")
      ? await this.deps.prisma.user.findFirst({
          where: { email: { equals: fromEmail, mode: "insensitive" }, status: "ACTIVE" },
          select: { id: true, email: true, role: true, tenantId: true, smsEmailForwardEnabled: true },
        })
      : null;
    if (!user || user.tenantId !== thread.tenantId) {
      await audit("sms.reply_refused", { reason: "unknown_sender", from: email.from, threadId: thread.id });
      return "dropped";
    }
    // From here on the sender is one of OUR users — refusals are explained by email.
    const refuse = async (reason: string, humanText: string) => {
      await audit("sms.reply_refused", { reason, from: user.email, threadId: thread.id });
      await this.sendFailureNotice(user.email, thread, humanText).catch(() => {});
      return "dropped" as const;
    };

    if (!user.smsEmailForwardEnabled) {
      return refuse(
        "sms_to_email_off",
        "SMS to Email is switched off for your account, so replies by email are not sent as texts. Turn it back on in Quick Controls, or reply from the app.",
      );
    }
    const participant = await this.deps.prisma.connectChatParticipant.findFirst({
      where: { threadId: thread.id, userId: user.id, leftAt: null },
      select: { id: true },
    });
    if (!participant) {
      return refuse(
        "not_a_participant",
        "You are no longer on this conversation, so your reply was not sent as a text. Open the app to view the conversation.",
      );
    }

    // 4) The person's words, with quoted history and signatures cut away.
    const body = extractSmsReplyText(email.text, email.html);
    if (!body) {
      return refuse("empty_body", "We could not find any message text in your reply, so nothing was sent. Type your message above the quoted email and send again.");
    }
    if (body.length > MAX_REPLY_CHARS) {
      return refuse("too_long", `Your reply is too long to send as a text (${body.length} characters). Shorten it and send again, or reply from the app.`);
    }

    // 5) Exactly-once: claim BEFORE sending; a pre-existing claim means an earlier
    //    attempt may already have texted — never guess, never double-send.
    const dedupeId = email.messageId || `uid:${email.id}`;
    const priorClaim = await this.deps.prisma.agentAuditLog.findFirst({
      where: { event: "sms.reply_claimed", payload: { path: ["dedupeId"], equals: dedupeId } },
      select: { id: true },
    });
    if (priorClaim) {
      await audit("sms.reply_ignored", { reason: "already_claimed", dedupeId, threadId: thread.id });
      return "dropped";
    }
    await this.deps.audit.record({
      actor: "system",
      event: "sms.reply_claimed",
      payload: { dedupeId, threadId: thread.id, userId: user.id, chars: body.length },
    });

    // 6) Send through the real route as the real person.
    const doFetch = this.deps.fetchImpl ?? fetch;
    const base = this.deps.apiBaseUrl().replace(/\/$/, "");
    let res: Response;
    try {
      res = await doFetch(`${base}/chat/threads/${encodeURIComponent(thread.id)}/messages`, {
        method: "POST",
        headers: { "content-type": "application/json", authorization: `Bearer ${this.mintUserToken(user)}` },
        body: JSON.stringify({ body }),
        signal: AbortSignal.timeout(30_000),
      });
    } catch (err) {
      // Unreachable api. The claim stands, so this is NEVER retried — the person
      // is told immediately instead of maybe-texted twice later.
      await audit("sms.reply_failed", { reason: "api_unreachable", error: String(err).slice(0, 200), threadId: thread.id });
      await this.sendFailureNotice(user.email, thread, "Something went wrong on our side and your reply was not sent as a text. Please try again in a minute, or send it from the app.").catch(() => {});
      return "dropped";
    }
    if (!res.ok) {
      let detail = "";
      try {
        const bodyJson: any = await res.json();
        detail = String(bodyJson?.message || bodyJson?.error || "");
      } catch { /* body unreadable — the status alone will do */ }
      await audit("sms.reply_failed", { reason: "api_refused", status: res.status, detail: detail.slice(0, 200), threadId: thread.id });
      await this.sendFailureNotice(
        user.email,
        thread,
        detail && /[a-z] [a-z]/i.test(detail)
          ? `Your reply was not sent as a text: ${detail}`
          : "Your reply could not be sent as a text. Open the app to send it from there.",
      ).catch(() => {});
      return "dropped";
    }

    await audit("sms.reply_sent", { threadId: thread.id, userId: user.id, chars: body.length, dedupeId });
    return "sent";
  }

  /** Short-lived (2 min) HS256 token for the REPLYING user — same claim shape as a login token. */
  private mintUserToken(user: { id: string; tenantId: string; email: string; role: string }): string {
    const secret = this.deps.jwtSecret();
    if (!secret) throw new Error("no_jwt_secret");
    const header = b64url(Buffer.from(JSON.stringify({ alg: "HS256", typ: "JWT" })));
    const nowS = Math.floor(Date.now() / 1000);
    const payload = b64url(
      Buffer.from(JSON.stringify({ sub: user.id, tenantId: user.tenantId, email: user.email, role: user.role, iat: nowS, exp: nowS + 120 })),
    );
    const sig = b64url(createHmac("sha256", secret).update(`${header}.${payload}`).digest());
    return `${header}.${payload}.${sig}`;
  }

  /**
   * Threaded "your text did not go out" notice — References pins it into the
   * same email conversation as the forwards, and the stable subject matches
   * the forward job's so Gmail groups it. Auto-Submitted so responders on the
   * user's side never answer it (loop protection).
   */
  private async sendFailureNotice(
    to: string,
    thread: { id: string; externalSmsE164: string | null },
    humanText: string,
  ): Promise<void> {
    const brand = this.deps.brandName ?? "Loopcom";
    const domain = this.deps.messageIdDomain();
    const rootId = `<sms-thread-${thread.id}@${domain}>`;
    const contactName = await this.resolveContactName(thread);
    const who = contactName || formatSmsPhone(thread.externalSmsE164);
    await this.deps.notifier.send({
      kind: "sms",
      to: [to],
      subject: `Text with ${who}`,
      text: `${humanText}\n\n— ${brand}`,
      html: `<p style="font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:14px;line-height:1.5;color:#0f172a;"><strong>Your reply was not sent as a text.</strong><br>${humanText.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")}</p><p style="font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:12px;color:#94a3b8;">— ${brand}</p>`,
      messageId: `<sms-notice-${thread.id}-${Date.now()}@${domain}>`,
      headers: { "In-Reply-To": rootId, References: rootId, "Auto-Submitted": "auto-replied" },
    });
  }

  private async resolveContactName(thread: { id: string; externalSmsE164: string | null }): Promise<string | null> {
    if (!thread.externalSmsE164) return null;
    const last10 = thread.externalSmsE164.replace(/\D/g, "").slice(-10);
    if (last10.length < 7) return null;
    const row = await this.deps.prisma.connectChatThread.findUnique({ where: { id: thread.id }, select: { tenantId: true } }).catch(() => null);
    if (!row) return null;
    const match = await this.deps.prisma.contactPhone
      .findFirst({
        where: { contact: { tenantId: row.tenantId }, numberNormalized: { endsWith: last10 } },
        select: { contact: { select: { displayName: true } } },
        orderBy: { isPrimary: "desc" },
      })
      .catch(() => null);
    return match?.contact?.displayName?.trim() || null;
  }
}
