/**
 * SMS-to-email REPLY job — Part 3 of the bridge (reply-to-text-back).
 *
 * The forward job (smsEmailForwardJob.ts) emails inbound texts out with
 * `Reply-To: sms+<threadId>.<sig>@<replyDomain>`. This job reads the bridge
 * mailbox (sms@loopcom.net via the injected source), and for each reply:
 * verify the signed address → match the sender to an opted-in participant →
 * strip the quoted history → send the words as a TEXT through the REAL portal
 * route (`POST /chat/threads/:id/messages`) under a short-lived JWT minted for
 * THAT user. Reusing the real route is the point: participant checks, the
 * can_send_sms permission, outbound-number resolution, MMS/segment handling and
 * delivery tracking all stay in one implementation, and the reply shows up in
 * the app attributed to the person who wrote it — never to a robot.
 *
 * Failure directions, chosen deliberately:
 *   • An email that is not a reply (no signed address) is ignored quietly —
 *     the bridge mailbox will collect spam, and spam must not generate mail.
 *   • A STRANGER whose From matches no opted-in participant gets NOTHING back
 *     (no backscatter, no oracle); the refusal is audited.
 *   • A KNOWN user whose reply cannot be sent (toggle off, no permission, empty
 *     body, api refusal, api unreachable) IS told, by a threaded notice email —
 *     they believe they just texted a customer; silence would be a lie.
 *   • A send is CLAIMED in AgentAuditLog before the POST and never auto-retried
 *     after a crash — an ambiguous half-send becomes a notice, not a duplicate
 *     text (the "a purchase is never retried" rule).
 */
import { createHmac } from "node:crypto";
import type { AuditLog } from "../audit/audit";
import type { Notifier } from "./notifier";
import { resolveSmsReplyTarget, isAutoGeneratedEmail, extractSmsReplyText } from "./smsEmailReply";
import { formatSmsPhone, headerSafeName } from "./smsEmail";

const b64url = (b: Buffer) => b.toString("base64").replace(/=+$/g, "").replace(/\+/g, "-").replace(/\//g, "_");

/** One parsed email out of the bridge mailbox. Header keys are lower-cased. */
export interface SmsReplyEmail {
  /** Mailbox-local id (IMAP UID as a string). */
  id: string;
  messageId: string | null;
  /** Sender address only (no display name). */
  from: string | null;
  /** Every recipient address the mail carried (To/Cc/Delivered-To/X-Original-To). */
  to: string[];
  subject: string;
  text: string | null;
  html: string | null;
  headers: Record<string, string>;
}

export interface SmsReplyEmailSource {
  /**
   * One pass over unprocessed mail. Calls `handler` per email; a `true` return
   * marks that email processed (never seen again), `false`/throw leaves it for
   * the next pass. Returns how many emails were handled.
   */
  poll(handler: (email: SmsReplyEmail) => Promise<boolean>): Promise<number>;
}

export interface SmsEmailReplyJobDeps {
  prisma: any;
  audit: AuditLog;
  /** The SMS-bridge notifier (sends AS the bridge mailbox) — used only for failure notices. */
  notifier: Notifier;
  source: SmsReplyEmailSource;
  replyDomain: () => string | null;
  replySecret: () => string | null;
  /** Same JWT_SECRET the portal api verifies with. */
  jwtSecret: () => string | null;
  apiBaseUrl: () => string;
  /**
   * CDR_INGEST_SECRET - the lock on /internal/*. Used ONLY for the shared-inbox
   * system-send door; a personal send goes out as that person's own JWT.
   */
  internalSecret?: () => string | null;
  /** Domain for threading Message-IDs — must match the forward job's. */
  messageIdDomain: () => string;
  fetchImpl?: typeof fetch;
  brandName?: string;
}

/** Longer than any reasonable text; the api's own validation governs below this. */
const MAX_REPLY_CHARS = 4000;

/** Ceiling on real sends into ONE thread per hour. A leaked reply address must
 *  not become a way to flood a customer. Counted from the audit trail. */
const MAX_REPLIES_PER_THREAD_PER_HOUR = 20;

export class SmsEmailReplyJob {
  private running = false;
  constructor(private deps: SmsEmailReplyJobDeps) {}

  /** One polling pass. Returns how many replies became texts. */
  async runOnce(): Promise<number> {
    if (this.running) return 0;
    if (!this.deps.replyDomain() || !this.deps.replySecret() || !this.deps.jwtSecret()) return 0;
    this.running = true;
    let sent = 0;
    try {
      await this.deps.source.poll(async (email) => {
        const outcome = await this.processOne(email);
        if (outcome === "sent") sent++;
        return outcome !== "retry";
      });
      return sent;
    } finally {
      this.running = false;
    }
  }

  private async processOne(email: SmsReplyEmail): Promise<"sent" | "dropped" | "retry"> {
    const audit = (event: string, payload: Record<string, unknown>) =>
      this.deps.audit.record({ actor: "system", event, payload: { emailId: email.id, messageId: email.messageId, ...payload } }).catch(() => {});

    // 1) Is this a reply to one of our forwards, and to WHICH conversation?
    //    ⛔ The resolver VERIFIES before it counts. Gmail delivers the same
    //    address twice - once as sent and once lower-cased in `Delivered-To:` -
    //    and counting raw strings read that as two conversations and refused
    //    every real reply for three days. Ambiguity is a statement about proven
    //    CONVERSATIONS, never about how many strings a header carried.
    const resolution = resolveSmsReplyTarget({
      candidates: email.to,
      replyDomain: this.deps.replyDomain() || "",
      secret: this.deps.replySecret() || "",
      threadingHint: `${email.headers?.["references"] ?? ""} ${email.headers?.["in-reply-to"] ?? ""}`,
    });
    if (resolution.status === "ambiguous") {
      await audit("sms.reply_ignored", {
        reason: "ambiguous_reply_address", from: email.from,
        count: resolution.threadIds.length, threadIds: resolution.threadIds,
      });
      return "dropped";
    }
    const parsed = resolution.target;
    if (!parsed) {
      // Told apart on purpose: "not a reply at all" is ordinary mailbox traffic,
      // "carried our address but proved nothing" is a forged or mangled token.
      await audit("sms.reply_ignored", {
        reason: resolution.sawUnverified ? "bad_signature" : "no_reply_address",
        from: email.from, candidates: resolution.candidateCount,
      });
      return "dropped";
    }
    // 2) Never text an auto-responder's blurb to a customer.
    if (isAutoGeneratedEmail(email.headers, email.subject)) {
      await audit("sms.reply_ignored", { reason: "auto_generated", from: email.from, threadId: parsed.threadId });
      return "dropped";
    }

    const thread = await this.deps.prisma.connectChatThread.findUnique({
      where: { id: parsed.threadId },
      select: { id: true, type: true, tenantId: true, externalSmsE164: true, tenantSmsE164: true, smsInboxOwnerUserId: true },
    });
    if (!thread || thread.type !== "SMS") {
      await audit("sms.reply_refused", { reason: "thread_gone", threadId: parsed.threadId, from: email.from });
      return "dropped";
    }

    // 3) WHO the text goes out as is decided by the THREAD'S OWN ROUTING - never
    //    by the email's From header. The signature in step 1 already pinned WHICH
    //    conversation this is; a conversation knows its phone number, and that
    //    number's SMS routing knows the inbox it lands in. So a reply works from
    //    any address the person happens to send from (a forward, a phone, a
    //    personal account) without us ever having to recognise that address.
    //
    //    ⛔ THIS IS THE TENANT-LEAK LOCK. The resolved sender MUST be ACTIVE and
    //    MUST belong to the THREAD'S OWN tenant. Measured 2026-08-21 across all
    //    616 live SMS threads: 0 owners in another tenant, 0 inactive. The check
    //    exists to keep that true when somebody is moved, disabled or offboarded
    //    - never delete it because it currently refuses nothing.
    const fromEmail = String(email.from || "").trim().toLowerCase();
    // ⛔ '' (empty string), NOT null, is how a SHARED inbox is stored - 315 of
    //    616 live threads. `!= null` would read those as owned and try to send as
    //    a user id of "". Truthiness is the correct test here.
    const ownerId = String(thread.smsInboxOwnerUserId || "").trim();
    let sender: { id: string; email: string; role: string; tenantId: string } | null = null;
    if (ownerId) {
      const owner = await this.deps.prisma.user
        .findUnique({
          where: { id: ownerId },
          select: { id: true, email: true, role: true, tenantId: true, status: true },
        })
        .catch(() => null);
      const bad = !owner
        ? "inbox_owner_gone"
        : owner.status !== "ACTIVE"
          ? "inbox_owner_inactive"
          : owner.tenantId !== thread.tenantId
            ? "inbox_owner_tenant_mismatch"
            : null;
      if (bad || !owner) {
        await audit("sms.reply_refused", { reason: bad ?? "inbox_owner_gone", from: fromEmail, threadId: thread.id });
        return "dropped";
      }
      sender = { id: owner.id, email: owner.email, role: owner.role, tenantId: owner.tenantId };
    }
    if (!sender && fromEmail.includes("@")) {
      // SHARED inbox (no single owner — 315 of 616 live threads). There is no
      // routing owner to attribute to, so fall back to the pre-2026-08-21
      // behaviour: if the address that replied IS one of our users, send as
      // them. This is a NARROWER door than the owner path above, and it is kept
      // only so shared inboxes do not LOSE the ability they have today; the
      // any-address case for shared inboxes needs the system-send door.
      // The same tenant + ACTIVE locks apply.
      const matched = await this.deps.prisma.user
        .findFirst({
          where: { email: { equals: fromEmail, mode: "insensitive" }, status: "ACTIVE" },
          select: { id: true, email: true, role: true, tenantId: true },
        })
        .catch(() => null);
      if (matched && matched.tenantId === thread.tenantId) {
        sender = { id: matched.id, email: matched.email, role: matched.role, tenantId: matched.tenantId };
      }
    }
    // A shared inbox replied to from an address we do not recognise still goes
    // out - with NO NAME attached, through the system door. senderUserId null is
    // the schema's normal shape, and attributing a shared inbox's text to one of
    // its several people would itself be wrong.
    const routedSender = sender;
    const isSystemSend = routedSender === null;

    // A refusal is explained ONLY to the inbox owner, at the address WE hold in
    // our own database. ⛔ Never reply to the email's From: whoever holds a
    // leaked reply address must not be able to learn anything back from it - a
    // reply is a WRITE into one thread and nothing more.
    const refuse = async (reason: string, humanText: string) => {
      await audit("sms.reply_refused", { reason, from: fromEmail, sentAs: routedSender?.email ?? null, threadId: thread.id });
      // ⛔ A notice goes ONLY to an address WE hold. On a system send there is
      //    none, so nothing is sent - replying to the From would hand whoever
      //    holds a leaked address a way to learn something back.
      if (routedSender) await this.sendFailureNotice(routedSender.email, thread, humanText).catch(() => {});
      return "dropped" as const;
    };

    // A leaked address must not become a way to flood a customer. Counts real
    // sends on THIS thread in the last hour from the audit trail, so it survives
    // a restart - never a module variable.
    // ⛔ The column is `ts`, NOT `createdAt` (AgentAuditLog in schema.prisma).
    //    It was written as `createdAt` first: Prisma threw, the catch below
    //    swallowed it, sentLastHour was always 0 and this cap never fired -
    //    silently, with a green test suite. A swallowed catch on a query that
    //    DECIDES something is how a guard becomes decoration.
    const sentLastHour = await this.deps.prisma.agentAuditLog
      .count({
        where: {
          event: "sms.reply_sent",
          ts: { gte: new Date(Date.now() - 60 * 60 * 1000) },
          payload: { path: ["threadId"], equals: thread.id },
        },
      })
      .catch(async (err: any) => {
        // Fails OPEN on purpose: the signed address is the primary control and
        // a transient database error must not refuse a legitimate reply. But it
        // is never silent - a cap that stops working has to be greppable.
        await audit("sms.reply_rate_check_failed", { threadId: thread.id, error: String(err?.message ?? err).slice(0, 200) });
        return 0;
      });
    if (sentLastHour >= MAX_REPLIES_PER_THREAD_PER_HOUR) {
      return refuse(
        "rate_limited",
        "Too many replies have been sent to this conversation in the last hour, so this one was not sent as a text. Send it from the app.",
      );
    }

    // 4) The person's words, with quoted history and signatures cut away.
    const body = extractSmsReplyText(email.text, email.html);
    if (!body) {
      return refuse("empty_body", "We could not find any message text in your reply, so nothing was sent. Type your message above the quoted email and send again.");
    }
    if (body.length > MAX_REPLY_CHARS) {
      return refuse("too_long", `Your reply is too long to send as a text (${body.length} characters). Shorten it and send again, or reply from the app.`);
    }

    // 5) Exactly-once: claim BEFORE sending; a pre-existing claim means an earlier
    //    attempt may already have texted — never guess, never double-send.
    const dedupeId = email.messageId || `uid:${email.id}`;
    const priorClaim = await this.deps.prisma.agentAuditLog.findFirst({
      where: { event: "sms.reply_claimed", payload: { path: ["dedupeId"], equals: dedupeId } },
      select: { id: true },
    });
    if (priorClaim) {
      await audit("sms.reply_ignored", { reason: "already_claimed", dedupeId, threadId: thread.id });
      return "dropped";
    }
    await this.deps.audit.record({
      actor: "system",
      event: "sms.reply_claimed",
      payload: { dedupeId, threadId: thread.id, userId: routedSender?.id ?? null, sentAs: routedSender?.email ?? "(shared inbox — no name)", receivedFrom: fromEmail, chars: body.length },
    });

    // 6) Send through the REAL route as the inbox owner. ⛔ Never a parallel
    //    send path: participant checks, can_send_sms, outbound-number resolution,
    //    segmenting, MMS fallback and delivery tracking all stay in the one
    //    implementation, and every one of them is re-checked SERVER-SIDE against
    //    this user - the reply job cannot talk its way past any of them.
    const doFetch = this.deps.fetchImpl ?? fetch;
    const base = this.deps.apiBaseUrl().replace(/\/$/, "");
    let res: Response;
    try {
      res = routedSender
        ? await doFetch(`${base}/chat/threads/${encodeURIComponent(thread.id)}/messages`, {
            method: "POST",
            headers: { "content-type": "application/json", authorization: `Bearer ${this.mintUserToken(routedSender)}` },
            body: JSON.stringify({ body }),
            signal: AbortSignal.timeout(30_000),
          })
        : await doFetch(`${base}/internal/chat/sms-system-reply`, {
            method: "POST",
            headers: { "content-type": "application/json", "x-cdr-secret": this.deps.internalSecret?.() ?? "" },
            body: JSON.stringify({ threadId: thread.id, body }),
            signal: AbortSignal.timeout(30_000),
          });
    } catch (err) {
      // Unreachable api. The claim stands, so this is NEVER retried — the person
      // is told immediately instead of maybe-texted twice later.
      await audit("sms.reply_failed", { reason: "api_unreachable", error: String(err).slice(0, 200), threadId: thread.id, sentAs: routedSender?.email ?? null, systemSend: isSystemSend });
      if (routedSender) await this.sendFailureNotice(routedSender.email, thread, "Something went wrong on our side and your reply was not sent as a text. Please try again in a minute, or send it from the app.").catch(() => {});
      return "dropped";
    }
    if (!res.ok) {
      let detail = "";
      try {
        const bodyJson: any = await res.json();
        detail = String(bodyJson?.message || bodyJson?.error || "");
      } catch { /* body unreadable — the status alone will do */ }
      await audit("sms.reply_failed", { reason: "api_refused", status: res.status, detail: detail.slice(0, 200), threadId: thread.id, sentAs: routedSender?.email ?? null, systemSend: isSystemSend });
      if (routedSender) await this.sendFailureNotice(
        routedSender.email,
        thread,
        detail && /[a-z] [a-z]/i.test(detail)
          ? `Your reply was not sent as a text: ${detail}`
          : "Your reply could not be sent as a text. Open the app to send it from there.",
      ).catch(() => {});
      return "dropped";
    }

    await audit("sms.reply_sent", { threadId: thread.id, userId: routedSender?.id ?? null, sentAs: routedSender?.email ?? "(shared inbox — no name)", receivedFrom: fromEmail, systemSend: isSystemSend, chars: body.length, dedupeId });
    return "sent";
  }

  /** Short-lived (2 min) HS256 token for the REPLYING user — same claim shape as a login token. */
  private mintUserToken(user: { id: string; tenantId: string; email: string; role: string }): string {
    const secret = this.deps.jwtSecret();
    if (!secret) throw new Error("no_jwt_secret");
    const header = b64url(Buffer.from(JSON.stringify({ alg: "HS256", typ: "JWT" })));
    const nowS = Math.floor(Date.now() / 1000);
    const payload = b64url(
      Buffer.from(JSON.stringify({ sub: user.id, tenantId: user.tenantId, email: user.email, role: user.role, iat: nowS, exp: nowS + 120 })),
    );
    const sig = b64url(createHmac("sha256", secret).update(`${header}.${payload}`).digest());
    return `${header}.${payload}.${sig}`;
  }

  /**
   * Threaded "your text did not go out" notice — References pins it into the
   * same email conversation as the forwards, and the stable subject matches
   * the forward job's so Gmail groups it. Auto-Submitted so responders on the
   * user's side never answer it (loop protection).
   */
  private async sendFailureNotice(
    to: string,
    thread: { id: string; externalSmsE164: string | null },
    humanText: string,
  ): Promise<void> {
    const brand = this.deps.brandName ?? "Loopcom";
    const domain = this.deps.messageIdDomain();
    const rootId = `<sms-thread-${thread.id}@${domain}>`;
    const contactName = await this.resolveContactName(thread);
    const who = contactName || formatSmsPhone(thread.externalSmsE164);
    await this.deps.notifier.send({
      kind: "sms",
      to: [to],
      subject: `Text with ${headerSafeName(who)}`,
      text: `${humanText}\n\n— ${brand}`,
      html: `<p style="font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:14px;line-height:1.5;color:#0f172a;"><strong>Your reply was not sent as a text.</strong><br>${humanText.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")}</p><p style="font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:12px;color:#94a3b8;">— ${brand}</p>`,
      messageId: `<sms-notice-${thread.id}-${Date.now()}@${domain}>`,
      headers: { "In-Reply-To": rootId, References: rootId, "Auto-Submitted": "auto-replied" },
    });
  }

  private async resolveContactName(thread: { id: string; externalSmsE164: string | null }): Promise<string | null> {
    if (!thread.externalSmsE164) return null;
    const last10 = thread.externalSmsE164.replace(/\D/g, "").slice(-10);
    if (last10.length < 7) return null;
    const row = await this.deps.prisma.connectChatThread.findUnique({ where: { id: thread.id }, select: { tenantId: true } }).catch(() => null);
    if (!row) return null;
    const match = await this.deps.prisma.contactPhone
      .findFirst({
        where: { contact: { tenantId: row.tenantId }, numberNormalized: { endsWith: last10 } },
        select: { contact: { select: { displayName: true } } },
        orderBy: { isPrimary: "desc" },
      })
      .catch(() => null);
    return match?.contact?.displayName?.trim() || null;
  }
}
