/**
 * SMS-reply routing rules (the pure half of Part 3) + source guards on the
 * wiring. The wiring guards read SOURCE with CRLF normalised (the Windows
 * checkout rule) — a unit test of the helpers alone would pass straight
 * through a server.ts that never instantiates the jobs.
 */
import { describe, it } from "node:test";
import assert from "node:assert";
import { createHmac } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  mintSmsReplyAddress,
  mintSmsReplySignature,
  parseSmsReplyAddress,
  resolveSmsReplyTarget,
  verifySmsReplySignature,
  isAutoGeneratedEmail,
  extractSmsReplyText,
  htmlToReplyText,
} from "./smsEmailReply";

const SECRET = "test-secret-value-0123456789";
const THREAD = "cmabc123def456";

describe("mint + verify", () => {
  it("mints byte-identically to the format the forward job has always used", () => {
    // The historical inline implementation, reproduced verbatim — addresses
    // already sitting in people's inboxes must keep verifying.
    const legacySig = createHmac("sha256", SECRET)
      .update(THREAD)
      .digest("base64")
      .replace(/=+$/g, "")
      .replace(/\+/g, "-")
      .replace(/\//g, "_")
      .slice(0, 24);
    assert.strictEqual(mintSmsReplySignature(THREAD, SECRET), legacySig);
    assert.strictEqual(mintSmsReplyAddress(THREAD, SECRET, "loopcom.net"), `sms+${THREAD}.${legacySig}@loopcom.net`);
  });

  it("round-trips: mint → parse → verify", () => {
    const addr = mintSmsReplyAddress(THREAD, SECRET, "loopcom.net");
    const parsed = parseSmsReplyAddress(addr);
    assert.ok(parsed);
    assert.strictEqual(parsed!.threadId, THREAD);
    assert.strictEqual(parsed!.domain, "loopcom.net");
    assert.ok(verifySmsReplySignature(parsed!.threadId, parsed!.sig, SECRET));
  });

  it("a tampered signature or thread id is refused", () => {
    const parsed = parseSmsReplyAddress(mintSmsReplyAddress(THREAD, SECRET, "loopcom.net"))!;
    assert.strictEqual(verifySmsReplySignature(parsed.threadId, parsed.sig.slice(0, -1) + (parsed.sig.endsWith("A") ? "B" : "A"), SECRET), false);
    assert.strictEqual(verifySmsReplySignature("cmother999", parsed.sig, SECRET), false);
    assert.strictEqual(verifySmsReplySignature(parsed.threadId, parsed.sig, "wrong-secret"), false);
  });

  it("accepts the MTA-lowercased copy of OUR OWN signature, and nothing else lower-case", () => {
    // Gmail lower-cases the whole local part when it stamps Delivered-To:, and
    // base64url is case-significant. Measured on the live mailbox 2026-08-23.
    const sig = mintSmsReplySignature(THREAD, SECRET);
    assert.ok(/[A-Z]/.test(sig) || true); // (a sig with no upper-case is trivially fine)
    assert.ok(verifySmsReplySignature(THREAD, sig.toLowerCase(), SECRET), "lower-cased copy must verify");
    // A MIXED-case near-miss is still refused: only a fully flattened copy qualifies.
    if (/[a-z]/.test(sig)) {
      const flipped = sig.slice(0, -1) + sig.slice(-1).toUpperCase();
      if (flipped !== sig) assert.strictEqual(verifySmsReplySignature(THREAD, flipped, SECRET), false);
    }
    // Lower-case junk of the right length is refused.
    assert.strictEqual(verifySmsReplySignature(THREAD, "a".repeat(sig.length), SECRET), false);
  });
});

describe("resolveSmsReplyTarget", () => {
  const resolve = (candidates: string[], hint?: string) =>
    resolveSmsReplyTarget({ candidates, replyDomain: "loopcom.net", secret: SECRET, threadingHint: hint });

  it("finds the address among many recipients, bound to OUR domain only", () => {
    const ours = mintSmsReplyAddress(THREAD, SECRET, "loopcom.net");
    const foreign = mintSmsReplyAddress(THREAD, SECRET, "evil.example.com");
    assert.strictEqual(resolve(["a@b.com", ours, "c@d.com"]).target?.threadId, THREAD);
    assert.strictEqual(resolve([foreign, "sms@loopcom.net"]).status, "none");
    assert.strictEqual(resolve(["sms@loopcom.net"]).status, "none"); // the bare mailbox is not a reply address
  });

  it("⛔ THE REGRESSION: To: + the lower-cased Delivered-To: copy is ONE conversation", () => {
    const ours = mintSmsReplyAddress(THREAD, SECRET, "loopcom.net");
    const stamped = ours.toLowerCase(); // exactly what Gmail's Delivered-To carries
    const r = resolve([ours, stamped]);
    assert.strictEqual(r.status, "ok", "a real Gmail reply must not read as ambiguous");
    assert.strictEqual(r.target?.threadId, THREAD);
    assert.strictEqual(r.threadIds.length, 1);
  });

  it("two DIFFERENT proven conversations are refused, never resolved", () => {
    const r = resolve([
      mintSmsReplyAddress(THREAD, SECRET, "loopcom.net"),
      mintSmsReplyAddress("cmotherthread999", SECRET, "loopcom.net"),
    ]);
    assert.strictEqual(r.status, "ambiguous");
    assert.strictEqual(r.target, null);
    assert.strictEqual(r.threadIds.length, 2);
  });

  it("unverified junk can NOT veto a genuine reply", () => {
    // Anyone could otherwise kill a customer's replies by CC'ing a made-up address.
    const ours = mintSmsReplyAddress(THREAD, SECRET, "loopcom.net");
    const junk = `sms+cmfakethread123.${"z".repeat(24)}@loopcom.net`;
    const r = resolve([ours, junk]);
    assert.strictEqual(r.status, "ok");
    assert.strictEqual(r.target?.threadId, THREAD);
    assert.ok(r.sawUnverified);
  });

  it("addresses that carry no proof at all are 'none', and flagged as unverified", () => {
    const junk = `sms+cmfakethread123.${"z".repeat(24)}@loopcom.net`;
    const r = resolve([junk]);
    assert.strictEqual(r.status, "none");
    assert.strictEqual(r.sawUnverified, true, "must be told apart from ordinary non-reply mail");
    assert.strictEqual(resolve(["someone@example.com"]).sawUnverified, false);
  });

  it("References breaks a tie ONLY between conversations already proven", () => {
    const a = mintSmsReplyAddress(THREAD, SECRET, "loopcom.net");
    const b = mintSmsReplyAddress("cmotherthread999", SECRET, "loopcom.net");
    const picked = resolve([a, b], `<sms-thread-cmotherthread999@sms.connectcomunications.com>`);
    assert.strictEqual(picked.status, "ok");
    assert.strictEqual(picked.target?.threadId, "cmotherthread999");
    assert.ok(picked.usedThreadingHint);
    // A hint naming a thread we hold NO capability for changes nothing.
    const ignored = resolve([a, b], `<sms-thread-cmnotmine000@sms.connectcomunications.com>`);
    assert.strictEqual(ignored.status, "ambiguous");
    // A hint alone never routes.
    assert.strictEqual(resolve(["x@y.com"], `<sms-thread-${THREAD}@d>`).status, "none");
  });

  it("no secret or no domain resolves nothing", () => {
    const ours = mintSmsReplyAddress(THREAD, SECRET, "loopcom.net");
    assert.strictEqual(resolveSmsReplyTarget({ candidates: [ours], replyDomain: "", secret: SECRET }).status, "none");
    assert.strictEqual(resolveSmsReplyTarget({ candidates: [ours], replyDomain: "loopcom.net", secret: "" }).status, "none");
  });
});

describe("auto-generated mail is never texted", () => {
  it("flags Auto-Submitted, Precedence, suppress headers, bounces and OOO subjects", () => {
    assert.ok(isAutoGeneratedEmail({ "auto-submitted": "auto-replied" }, "Re: Text with X"));
    assert.ok(isAutoGeneratedEmail({ precedence: "bulk" }, ""));
    assert.ok(isAutoGeneratedEmail({ "x-auto-response-suppress": "All" }, ""));
    assert.ok(isAutoGeneratedEmail({ "return-path": "<>" }, ""));
    assert.ok(isAutoGeneratedEmail({}, "Automatic reply: Text with Chaim"));
    assert.ok(isAutoGeneratedEmail({}, "Out of Office"));
    assert.ok(isAutoGeneratedEmail({}, "Undeliverable: Text with Chaim"));
  });
  it("does not flag an ordinary human reply", () => {
    assert.strictEqual(isAutoGeneratedEmail({ "auto-submitted": "no" }, "Re: Text with Chaim"), false);
    assert.strictEqual(isAutoGeneratedEmail({}, "Re: Text with Chaim"), false);
  });
});

describe("extractSmsReplyText", () => {
  it("cuts a Gmail reply at the attribution line and quoted block", () => {
    const raw = [
      "Sounds good, see you at 3.",
      "",
      "On Tue, Aug 20, 2026 at 1:15 PM Loopcom Texts <sms@loopcom.net> wrote:",
      "> New text on your Loopcom number",
      "> hello there",
    ].join("\n");
    assert.strictEqual(extractSmsReplyText(raw), "Sounds good, see you at 3.");
  });

  it("handles the attribution wrapping onto a second line", () => {
    const raw = [
      "Yes that works",
      "",
      "On Tue, Aug 20, 2026 at 1:15 PM Loopcom Texts",
      "<sms@loopcom.net> wrote:",
      "> quoted",
    ].join("\n");
    assert.strictEqual(extractSmsReplyText(raw), "Yes that works");
  });

  it("cuts an Outlook top-posted reply at the divider / From-block", () => {
    const divider = ["We are open until 6.", "", "________________________________", "From: Loopcom Texts <sms@loopcom.net>", "Sent: Tuesday, August 20, 2026", "Subject: Text with Chaim"].join("\n");
    assert.strictEqual(extractSmsReplyText(divider), "We are open until 6.");
    const fromBlock = ["We are open until 6.", "", "From: Loopcom Texts <sms@loopcom.net>", "Sent: Tuesday, August 20, 2026"].join("\n");
    assert.strictEqual(extractSmsReplyText(fromBlock), "We are open until 6.");
  });

  it("drops '-- ' signatures and 'Sent from my iPhone'", () => {
    assert.strictEqual(extractSmsReplyText("Call me back\n\nSent from my iPhone"), "Call me back");
    assert.strictEqual(extractSmsReplyText("Call me back\n-- \nShloime Katz\nKatz Plumbing"), "Call me back");
  });

  it("keeps multi-line bodies and never rewrites the person's words", () => {
    const raw = "Line one.\nLine two — with punctuation!\n\nOn Tue, Aug 20, 2026 at 1:15 PM X <x@y.com> wrote:\n> q";
    assert.strictEqual(extractSmsReplyText(raw), "Line one.\nLine two — with punctuation!");
  });

  it("passes Yiddish through byte-for-byte", () => {
    const yi = "איך וועל דיר קלינגען שפּעטער";
    assert.strictEqual(extractSmsReplyText(`${yi}\n\nOn Tue, Aug 20, 2026 at 1:15 PM A <a@b.c> wrote:\n> x`), yi);
  });

  it("falls back to HTML when there is no text part, dropping the gmail_quote container", () => {
    const html = `<div dir="ltr">Got it, thanks!</div><br><div class="gmail_quote"><div>On Tue wrote:</div><blockquote>old stuff</blockquote></div>`;
    assert.strictEqual(extractSmsReplyText(null, html), "Got it, thanks!");
    assert.strictEqual(htmlToReplyText("<p>a&amp;b</p>").trim(), "a&b");
  });

  it("returns empty for an empty reply (nothing above the quote)", () => {
    assert.strictEqual(extractSmsReplyText("\n\nOn Tue, Aug 20, 2026 at 1:15 PM A <a@b.c> wrote:\n> x"), "");
    assert.strictEqual(extractSmsReplyText("", ""), "");
  });
});

// ── source guards on the wiring (CRLF-normalised reads) ──────────────────────
const read = (p: string) => readFileSync(p, "utf8").replace(/\r\n/g, "\n");

describe("wiring guards", () => {
  const serverSrc = read(join(__dirname, "..", "server.ts"));
  const forwardSrc = read(join(__dirname, "smsEmailForwardJob.ts"));

  it("server.ts instantiates the reply job under the AGENT_SMS_EMAIL gate", () => {
    assert.ok(serverSrc.includes("SmsEmailReplyJob"), "reply job never wired");
    assert.ok(serverSrc.includes("createSmsImapSource"), "IMAP source never wired");
  });

  it("the SMS bridge sends through its OWN notifier identity, not the shared agent one", () => {
    assert.ok(serverSrc.includes("AGENT_SMS_SMTP_USER"), "dedicated SMS SMTP identity missing");
    assert.ok(/const smsNotifier = new Notifier\(\{ \.\.\.cfg, smtp: smsSmtp \}, audit\)/.test(serverSrc), "smsNotifier construction changed");
    assert.ok(/notifier:\s*smsNotifier/.test(serverSrc), "forward job no longer uses the SMS notifier");
  });

  it("the forward job mints the reply address with the SHARED helper (mint/verify cannot drift)", () => {
    assert.ok(forwardSrc.includes("mintSmsReplyAddress(threadId, secret, domain)"), "forward job stopped using the shared mint");
  });

  it("customer-facing brand on the bridge is Loopcom", () => {
    const gateBlock = serverSrc.slice(serverSrc.indexOf('process.env.AGENT_SMS_EMAIL === "1"'));
    assert.ok(gateBlock.slice(0, 3500).includes('brandName: "Loopcom"'), "bridge brand is not Loopcom");
  });
});
