/**
 * SMS-reply routing rules (the pure half of Part 3) + source guards on the
 * wiring. The wiring guards read SOURCE with CRLF normalised (the Windows
 * checkout rule) — a unit test of the helpers alone would pass straight
 * through a server.ts that never instantiates the jobs.
 */
import { describe, it } from "node:test";
import assert from "node:assert";
import { createHmac } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  mintSmsReplyAddress,
  mintSmsReplySignature,
  parseSmsReplyAddress,
  findSmsReplyAddress,
  verifySmsReplySignature,
  isAutoGeneratedEmail,
  extractSmsReplyText,
  htmlToReplyText,
} from "./smsEmailReply";

const SECRET = "test-secret-value-0123456789";
const THREAD = "cmabc123def456";

describe("mint + verify", () => {
  it("mints byte-identically to the format the forward job has always used", () => {
    // The historical inline implementation, reproduced verbatim — addresses
    // already sitting in people's inboxes must keep verifying.
    const legacySig = createHmac("sha256", SECRET)
      .update(THREAD)
      .digest("base64")
      .replace(/=+$/g, "")
      .replace(/\+/g, "-")
      .replace(/\//g, "_")
      .slice(0, 24);
    assert.strictEqual(mintSmsReplySignature(THREAD, SECRET), legacySig);
    assert.strictEqual(mintSmsReplyAddress(THREAD, SECRET, "loopcom.net"), `sms+${THREAD}.${legacySig}@loopcom.net`);
  });

  it("round-trips: mint → parse → verify", () => {
    const addr = mintSmsReplyAddress(THREAD, SECRET, "loopcom.net");
    const parsed = parseSmsReplyAddress(addr);
    assert.ok(parsed);
    assert.strictEqual(parsed!.threadId, THREAD);
    assert.strictEqual(parsed!.domain, "loopcom.net");
    assert.ok(verifySmsReplySignature(parsed!.threadId, parsed!.sig, SECRET));
  });

  it("a tampered signature or thread id is refused", () => {
    const parsed = parseSmsReplyAddress(mintSmsReplyAddress(THREAD, SECRET, "loopcom.net"))!;
    assert.strictEqual(verifySmsReplySignature(parsed.threadId, parsed.sig.slice(0, -1) + (parsed.sig.endsWith("A") ? "B" : "A"), SECRET), false);
    assert.strictEqual(verifySmsReplySignature("cmother999", parsed.sig, SECRET), false);
    assert.strictEqual(verifySmsReplySignature(parsed.threadId, parsed.sig, "wrong-secret"), false);
  });

  it("finds the reply address among many recipients, bound to OUR domain only", () => {
    const ours = mintSmsReplyAddress(THREAD, SECRET, "loopcom.net");
    const foreign = mintSmsReplyAddress(THREAD, SECRET, "evil.example.com");
    assert.strictEqual(findSmsReplyAddress(["a@b.com", ours, "c@d.com"], "loopcom.net")?.threadId, THREAD);
    assert.strictEqual(findSmsReplyAddress([foreign, "sms@loopcom.net"], "loopcom.net"), null);
    assert.strictEqual(findSmsReplyAddress(["sms@loopcom.net"], "loopcom.net"), null); // the bare mailbox is not a reply address
    // Case-insensitive domain match — mail clients re-case addresses freely.
    assert.strictEqual(findSmsReplyAddress([ours.toUpperCase().replace("SMS+", "sms+").replace(THREAD.toUpperCase(), THREAD)], "Loopcom.NET")?.threadId, THREAD);
  });
});

describe("auto-generated mail is never texted", () => {
  it("flags Auto-Submitted, Precedence, suppress headers, bounces and OOO subjects", () => {
    assert.ok(isAutoGeneratedEmail({ "auto-submitted": "auto-replied" }, "Re: Text with X"));
    assert.ok(isAutoGeneratedEmail({ precedence: "bulk" }, ""));
    assert.ok(isAutoGeneratedEmail({ "x-auto-response-suppress": "All" }, ""));
    assert.ok(isAutoGeneratedEmail({ "return-path": "<>" }, ""));
    assert.ok(isAutoGeneratedEmail({}, "Automatic reply: Text with Chaim"));
    assert.ok(isAutoGeneratedEmail({}, "Out of Office"));
    assert.ok(isAutoGeneratedEmail({}, "Undeliverable: Text with Chaim"));
  });
  it("does not flag an ordinary human reply", () => {
    assert.strictEqual(isAutoGeneratedEmail({ "auto-submitted": "no" }, "Re: Text with Chaim"), false);
    assert.strictEqual(isAutoGeneratedEmail({}, "Re: Text with Chaim"), false);
  });
});

describe("extractSmsReplyText", () => {
  it("cuts a Gmail reply at the attribution line and quoted block", () => {
    const raw = [
      "Sounds good, see you at 3.",
      "",
      "On Tue, Aug 20, 2026 at 1:15 PM Loopcom Texts <sms@loopcom.net> wrote:",
      "> New text on your Loopcom number",
      "> hello there",
    ].join("\n");
    assert.strictEqual(extractSmsReplyText(raw), "Sounds good, see you at 3.");
  });

  it("handles the attribution wrapping onto a second line", () => {
    const raw = [
      "Yes that works",
      "",
      "On Tue, Aug 20, 2026 at 1:15 PM Loopcom Texts",
      "<sms@loopcom.net> wrote:",
      "> quoted",
    ].join("\n");
    assert.strictEqual(extractSmsReplyText(raw), "Yes that works");
  });

  it("cuts an Outlook top-posted reply at the divider / From-block", () => {
    const divider = ["We are open until 6.", "", "________________________________", "From: Loopcom Texts <sms@loopcom.net>", "Sent: Tuesday, August 20, 2026", "Subject: Text with Chaim"].join("\n");
    assert.strictEqual(extractSmsReplyText(divider), "We are open until 6.");
    const fromBlock = ["We are open until 6.", "", "From: Loopcom Texts <sms@loopcom.net>", "Sent: Tuesday, August 20, 2026"].join("\n");
    assert.strictEqual(extractSmsReplyText(fromBlock), "We are open until 6.");
  });

  it("drops '-- ' signatures and 'Sent from my iPhone'", () => {
    assert.strictEqual(extractSmsReplyText("Call me back\n\nSent from my iPhone"), "Call me back");
    assert.strictEqual(extractSmsReplyText("Call me back\n-- \nShloime Katz\nKatz Plumbing"), "Call me back");
  });

  it("keeps multi-line bodies and never rewrites the person's words", () => {
    const raw = "Line one.\nLine two — with punctuation!\n\nOn Tue, Aug 20, 2026 at 1:15 PM X <x@y.com> wrote:\n> q";
    assert.strictEqual(extractSmsReplyText(raw), "Line one.\nLine two — with punctuation!");
  });

  it("passes Yiddish through byte-for-byte", () => {
    const yi = "איך וועל דיר קלינגען שפּעטער";
    assert.strictEqual(extractSmsReplyText(`${yi}\n\nOn Tue, Aug 20, 2026 at 1:15 PM A <a@b.c> wrote:\n> x`), yi);
  });

  it("falls back to HTML when there is no text part, dropping the gmail_quote container", () => {
    const html = `<div dir="ltr">Got it, thanks!</div><br><div class="gmail_quote"><div>On Tue wrote:</div><blockquote>old stuff</blockquote></div>`;
    assert.strictEqual(extractSmsReplyText(null, html), "Got it, thanks!");
    assert.strictEqual(htmlToReplyText("<p>a&amp;b</p>").trim(), "a&b");
  });

  it("returns empty for an empty reply (nothing above the quote)", () => {
    assert.strictEqual(extractSmsReplyText("\n\nOn Tue, Aug 20, 2026 at 1:15 PM A <a@b.c> wrote:\n> x"), "");
    assert.strictEqual(extractSmsReplyText("", ""), "");
  });
});

// ── source guards on the wiring (CRLF-normalised reads) ──────────────────────
const read = (p: string) => readFileSync(p, "utf8").replace(/\r\n/g, "\n");

describe("wiring guards", () => {
  const serverSrc = read(join(__dirname, "..", "server.ts"));
  const forwardSrc = read(join(__dirname, "smsEmailForwardJob.ts"));

  it("server.ts instantiates the reply job under the AGENT_SMS_EMAIL gate", () => {
    assert.ok(serverSrc.includes("SmsEmailReplyJob"), "reply job never wired");
    assert.ok(serverSrc.includes("createSmsImapSource"), "IMAP source never wired");
  });

  it("the SMS bridge sends through its OWN notifier identity, not the shared agent one", () => {
    assert.ok(serverSrc.includes("AGENT_SMS_SMTP_USER"), "dedicated SMS SMTP identity missing");
    assert.ok(/const smsNotifier = new Notifier\(\{ \.\.\.cfg, smtp: smsSmtp \}, audit\)/.test(serverSrc), "smsNotifier construction changed");
    assert.ok(/notifier:\s*smsNotifier/.test(serverSrc), "forward job no longer uses the SMS notifier");
  });

  it("the forward job mints the reply address with the SHARED helper (mint/verify cannot drift)", () => {
    assert.ok(forwardSrc.includes("mintSmsReplyAddress(threadId, secret, domain)"), "forward job stopped using the shared mint");
  });

  it("customer-facing brand on the bridge is Loopcom", () => {
    const gateBlock = serverSrc.slice(serverSrc.indexOf('process.env.AGENT_SMS_EMAIL === "1"'));
    assert.ok(gateBlock.slice(0, 3500).includes('brandName: "Loopcom"'), "bridge brand is not Loopcom");
  });
});
