/**
 * Pushing what the agent is doing UP to LoopCom, so the support console can show
 * it live.
 *
 * ⛔⛔ WHY THIS EXISTS: the watcher runs on a laptop; the console runs on
 * loopcom. The console cannot read this machine. Everything an operator needs to
 * see has to be sent as it happens — a run that only reported its result would
 * leave them blind for the ten-plus minutes that actually matter.
 *
 * ⛔ EVERY FUNCTION HERE FAILS SOFT AND RETURNS, NEVER THROWS. Losing the live
 * view costs visibility; letting a failed push break the run costs the customer
 * their investigation. The report is on disk either way.
 */

const TIMEOUT_MS = 15_000;

async function post(cfg, path, body) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(`${cfg.base}${path}`, {
      method: "POST",
      headers: {
        authorization: `Bearer ${cfg.token}`,
        "content-type": "application/json",
        accept: "application/json",
      },
      body: JSON.stringify(body),
      signal: ctrl.signal,
    });
    if (!res.ok) {
      const text = await res.text().catch(() => "");
      return { ok: false, status: res.status, error: text.slice(0, 200) };
    }
    return { ok: true, body: await res.json().catch(() => null) };
  } catch (err) {
    return { ok: false, error: String(err?.message ?? err).slice(0, 200) };
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Upsert one run. Called repeatedly during the run — at start, every few seconds
 * with new steps, and once at the end with the report.
 *
 * ⛔ `runId` is generated by the watcher and stays the same for the whole run,
 * which is what makes a re-push an update rather than a duplicate row.
 */
export function pushRun(cfg, payload) {
  return post(cfg, "/admin/support/agent-runs", payload);
}

/** "I am alive, here is what I am doing and what I have spent today." */
export function pushWatcherBeat(cfg, payload) {
  return post(cfg, "/admin/support/agent-watcher", payload);
}

/**
 * Turn one line of `claude --output-format stream-json` into something a person
 * would want to read on a dashboard.
 *
 * ⛔ Returns null for the events that are noise. The dashboard is for a human
 * watching work happen, not a protocol dump — showing every frame would bury
 * the two lines that say what it is actually doing.
 */
export function stepFromEvent(ev) {
  if (!ev || typeof ev !== "object") return null;
  const at = new Date().toISOString();

  if (ev.type === "system" && ev.subtype === "init") {
    return { at, kind: "system", text: "started", sessionId: ev.session_id };
  }

  if (ev.type === "assistant") {
    const content = ev.message?.content;
    if (!Array.isArray(content)) return null;
    for (const c of content) {
      if (c?.type === "tool_use") {
        return { at, kind: "tool", text: describeTool(c) };
      }
    }
    const text = content
      .filter((c) => c?.type === "text")
      .map((c) => String(c.text ?? "").trim())
      .filter(Boolean)
      .join(" ");
    // One line is enough on a dashboard; the full text is in the report.
    return text ? { at, kind: "text", text: firstLines(text, 2) } : null;
  }

  if (ev.type === "result") {
    return {
      at,
      kind: ev.is_error ? "error" : "system",
      text: ev.is_error ? `failed: ${ev.subtype ?? "error"}` : "finished",
      final: String(ev.result ?? ""),
      sessionId: ev.session_id,
      costUsd: ev.total_cost_usd,
      turns: ev.num_turns,
      // ⛔ Worth surfacing: this is the agent trying something it was not allowed
      // to do. On a support run that is a signal, not a footnote.
      denials: Array.isArray(ev.permission_denials) ? ev.permission_denials.length : 0,
    };
  }

  return null;
}

/** "Bash: grep -rn answer_unacked apps/portal" — the verb and its subject, briefly. */
function describeTool(c) {
  const name = String(c.name ?? "tool");
  const short = name.startsWith("mcp__loopcom-support__") ? name.replace("mcp__loopcom-support__", "") : name;
  const input = c.input ?? {};
  const detail =
    input.command ??
    input.pattern ??
    input.file_path ??
    input.path ??
    input.reference ??
    input.query ??
    (typeof input === "object" ? Object.values(input).find((v) => typeof v === "string") : "");
  const d = String(detail ?? "").replace(/\s+/g, " ").trim();
  return d ? `${short}: ${d.slice(0, 160)}` : short;
}

function firstLines(s, n) {
  return String(s)
    .split("\n")
    .filter((l) => l.trim())
    .slice(0, n)
    .join(" ")
    .slice(0, 300);
}
