ALTER TABLE "Tenant"
  ADD COLUMN IF NOT EXISTS "dailySmsLimit" INTEGER NOT NULL DEFAULT 500,
  ADD COLUMN IF NOT EXISTS "hourlySmsLimit" INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS "perSecondRateLimit" INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS "maxCampaignSize" INTEGER NOT NULL DEFAULT 2000,
  ADD COLUMN IF NOT EXISTS "smsSuspended" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "smsSuspendedReason" TEXT,
  ADD COLUMN IF NOT EXISTS "smsSuspendedAt" TIMESTAMP(3);
