-- Supermarket mode (Gesheft plan Phases 0-7), 2026-08-26.
--
-- Additive only: two IntegrationProvider enum values, one Tenant column
-- (crmMode, default 'classic' = every existing tenant keeps byte-identical
-- behaviour), and eight new tables that all start EMPTY. Nothing changes for
-- any customer until a tenant is switched to supermarket mode AND given a
-- POS_TRACKING ProviderCredential row. Generated by prisma migrate diff
-- against HEAD; FK statements are Prisma's own.
-- NOTE: ALTER TYPE ... ADD VALUE needs PostgreSQL 12+ inside a transaction;
-- prod is on 14+ (capacity tuning 2026-08-23 used ALTER SYSTEM there).

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "IntegrationProvider" ADD VALUE 'POS_TRACKING';
ALTER TYPE "IntegrationProvider" ADD VALUE 'SOLA';
ALTER TYPE "IntegrationProvider" ADD VALUE 'OPENAI';

-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN     "crmMode" TEXT NOT NULL DEFAULT 'classic';

-- CreateTable
CREATE TABLE "PosCatalogItem" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "posProductId" TEXT NOT NULL,
    "code" TEXT NOT NULL DEFAULT '',
    "name" TEXT NOT NULL DEFAULT '',
    "priceCents" INTEGER NOT NULL DEFAULT 0,
    "priceQty" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "unitPriceCents" INTEGER NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "posLastMod" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PosCatalogItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PosCatalogSyncState" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "lastMod" TEXT,
    "cursor" TEXT,
    "lastSyncAt" TIMESTAMP(3),
    "lastError" TEXT,
    "creditsSpent" INTEGER NOT NULL DEFAULT 0,
    "itemCount" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PosCatalogSyncState_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SupermarketOrderDraft" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "sourceType" TEXT NOT NULL,
    "sourceId" TEXT NOT NULL,
    "threadId" TEXT,
    "customerName" TEXT NOT NULL DEFAULT '',
    "customerPhone" TEXT NOT NULL DEFAULT '',
    "posCustomerId" TEXT,
    "transcript" TEXT NOT NULL DEFAULT '',
    "translation" TEXT NOT NULL DEFAULT '',
    "items" JSONB NOT NULL DEFAULT '[]',
    "comments" TEXT NOT NULL DEFAULT '',
    "notes" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'NEEDS_REVIEW',
    "agentItems" JSONB,
    "corrections" JSONB,
    "orderMethod" TEXT NOT NULL DEFAULT 'Pickup',
    "posOrderId" TEXT,
    "posExternalId" TEXT,
    "submitError" TEXT,
    "reviewedBy" TEXT,
    "approvedAt" TIMESTAMP(3),
    "submittedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SupermarketOrderDraft_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SupermarketPhonePin" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "posCustomerId" TEXT NOT NULL,
    "phoneE164" TEXT NOT NULL,
    "pinEnc" TEXT NOT NULL,
    "lastUsedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SupermarketPhonePin_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SupermarketPayCall" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "callId" TEXT NOT NULL,
    "callerNumber" TEXT NOT NULL DEFAULT '',
    "state" JSONB,
    "posCustomerId" TEXT,
    "chargeSeq" INTEGER NOT NULL DEFAULT 0,
    "chargedCents" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'open',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SupermarketPayCall_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SupermarketSpecial" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "recipientCount" INTEGER NOT NULL DEFAULT 0,
    "sentCount" INTEGER NOT NULL DEFAULT 0,
    "createdBy" TEXT,
    "sentAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SupermarketSpecial_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MarketingUnsubscribe" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MarketingUnsubscribe_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SupermarketSettings" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "autoSubmitEnabled" BOOLEAN NOT NULL DEFAULT false,
    "autoSubmitMaxCorrectionPct" DOUBLE PRECISION NOT NULL DEFAULT 5,
    "autoSubmitMinWeeks" INTEGER NOT NULL DEFAULT 2,
    "deliveryIngestEnabled" BOOLEAN NOT NULL DEFAULT false,
    "deliveryStoreRef" TEXT NOT NULL DEFAULT 'main',
    "payIvrEnabled" BOOLEAN NOT NULL DEFAULT false,
    "updatedBy" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SupermarketSettings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "VoiceAgentSettings" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "model" TEXT NOT NULL DEFAULT 'gpt-realtime',
    "voice" TEXT NOT NULL DEFAULT 'cedar',
    "greeting" TEXT NOT NULL DEFAULT '',
    "instructionsExtra" TEXT NOT NULL DEFAULT '',
    "maxCallSeconds" INTEGER NOT NULL DEFAULT 600,
    "maxConcurrentCalls" INTEGER NOT NULL DEFAULT 4,
    "monthlyMinuteCap" INTEGER NOT NULL DEFAULT 3000,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "VoiceAgentSettings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "VoiceAgentCall" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "sessionUuid" TEXT NOT NULL,
    "callerNumber" TEXT,
    "did" TEXT,
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "endedAt" TIMESTAMP(3),
    "seconds" INTEGER NOT NULL DEFAULT 0,
    "endReason" TEXT,
    "transcript" JSONB,
    "toolCalls" JSONB,
    "draftId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "VoiceAgentCall_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "PosCatalogItem_tenantId_code_idx" ON "PosCatalogItem"("tenantId", "code");

-- CreateIndex
CREATE INDEX "PosCatalogItem_tenantId_isActive_name_idx" ON "PosCatalogItem"("tenantId", "isActive", "name");

-- CreateIndex
CREATE UNIQUE INDEX "PosCatalogItem_tenantId_posProductId_key" ON "PosCatalogItem"("tenantId", "posProductId");

-- CreateIndex
CREATE UNIQUE INDEX "PosCatalogSyncState_tenantId_key" ON "PosCatalogSyncState"("tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "SupermarketOrderDraft_posExternalId_key" ON "SupermarketOrderDraft"("posExternalId");

-- CreateIndex
CREATE INDEX "SupermarketOrderDraft_tenantId_status_createdAt_idx" ON "SupermarketOrderDraft"("tenantId", "status", "createdAt");

-- CreateIndex
CREATE INDEX "SupermarketOrderDraft_tenantId_createdAt_idx" ON "SupermarketOrderDraft"("tenantId", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "SupermarketOrderDraft_tenantId_sourceType_sourceId_key" ON "SupermarketOrderDraft"("tenantId", "sourceType", "sourceId");

-- CreateIndex
CREATE INDEX "SupermarketPhonePin_tenantId_phoneE164_idx" ON "SupermarketPhonePin"("tenantId", "phoneE164");

-- CreateIndex
CREATE UNIQUE INDEX "SupermarketPhonePin_tenantId_posCustomerId_phoneE164_key" ON "SupermarketPhonePin"("tenantId", "posCustomerId", "phoneE164");

-- CreateIndex
CREATE INDEX "SupermarketPayCall_tenantId_createdAt_idx" ON "SupermarketPayCall"("tenantId", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "SupermarketPayCall_tenantId_callId_key" ON "SupermarketPayCall"("tenantId", "callId");

-- CreateIndex
CREATE INDEX "SupermarketSpecial_tenantId_createdAt_idx" ON "SupermarketSpecial"("tenantId", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "MarketingUnsubscribe_tenantId_email_key" ON "MarketingUnsubscribe"("tenantId", "email");

-- CreateIndex
CREATE UNIQUE INDEX "SupermarketSettings_tenantId_key" ON "SupermarketSettings"("tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "VoiceAgentSettings_tenantId_key" ON "VoiceAgentSettings"("tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "VoiceAgentCall_sessionUuid_key" ON "VoiceAgentCall"("sessionUuid");

-- CreateIndex
CREATE INDEX "VoiceAgentCall_tenantId_startedAt_idx" ON "VoiceAgentCall"("tenantId", "startedAt");

-- AddForeignKey
ALTER TABLE "PosCatalogItem" ADD CONSTRAINT "PosCatalogItem_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PosCatalogSyncState" ADD CONSTRAINT "PosCatalogSyncState_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SupermarketOrderDraft" ADD CONSTRAINT "SupermarketOrderDraft_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SupermarketPhonePin" ADD CONSTRAINT "SupermarketPhonePin_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SupermarketPayCall" ADD CONSTRAINT "SupermarketPayCall_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SupermarketSpecial" ADD CONSTRAINT "SupermarketSpecial_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MarketingUnsubscribe" ADD CONSTRAINT "MarketingUnsubscribe_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SupermarketSettings" ADD CONSTRAINT "SupermarketSettings_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

