/**
 * VitalPBX CSV generator for onboarding exports. No upload/side-effects.
 * Escapes commas/quotes/newlines and validates duplicates.
 */

function csvEscapeCell(raw: string | number | null | undefined): string {
  const s = raw == null ? "" : String(raw);
  if (/[",\n]/.test(s)) return '"' + s.replace(/"/g, '""') + '"';
  return s;
}

export type CsvExtensionRow = {
  extNumber: string;      // numeric-only string already validated
  name?: string | null;   // maps to ext_name
  email?: string | null;
  password?: string | null; // device_password — blank = auto-generated by VitalPBX
  vmEnabled?: boolean;    // true = "yes", false = "no" (default yes)
  class_of_service?: string | null;
};

// VitalPBX import column order (must match exactly)
const HEADER = [
  "mode",
  "extension",
  "ext_name",
  "email",
  "class_of_service",
  "vm_enabled",
  "device_user",
  "device_password",
];

export function generateVitalPbxCsv(rows: CsvExtensionRow[]): { filename: string; mime: string; body: string } {
  // Validate duplicates
  const seen = new Set<string>();
  for (const r of rows) {
    const k = String(r.extNumber || "");
    if (!k) throw new Error("missing_ext_number");
    if (seen.has(k)) throw new Error("duplicate_extension");
    seen.add(k);
  }
  const lines: string[] = [HEADER.join(",")];
  for (const r of rows) {
    const rec = [
      "add",                                             // mode
      csvEscapeCell(r.extNumber),                        // extension
      csvEscapeCell(r.name || ""),                       // ext_name
      csvEscapeCell(r.email || ""),                      // email
      csvEscapeCell(r.class_of_service || ""),           // class_of_service
      r.vmEnabled === false ? "no" : "yes",              // vm_enabled
      csvEscapeCell(r.extNumber),                        // device_user (= ext number creates a device)
      csvEscapeCell(r.password || ""),                   // device_password (blank = auto-generate)
    ];
    lines.push(rec.join(","));
  }
  const body = lines.join("\n");
  const filename = `vitalpbx_extensions_${Date.now()}.csv`;
  return { filename, mime: "text/csv; charset=utf-8", body };
}
