#include vitalpbx/manager__*.conf

[connectcommsgefenu]
secret = REDACTED
deny = 0.0.0.0/0.0.0.0
permit = 45.14.194.179/255.255.255.255
read = system,call,log,verbose,command,agent,user,config,dtmf,reporting,cdr,dialplan
write = system,call,command,agent,user,originate,reporting,message
writetimeout = 5000
