[asterisk]
enabled => yes
dsn => MySQL-asterisk
username => asterisk
password =REDACTED
pre-connect => yes

[vitalpbx]
enabled => yes
dsn => MySQL-vitalpbx
username => vitalpbx
password =REDACTED
pre-connect => yes