#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# ConnectComms — coturn (TURN server) installer
# Run on the backend server: 45.14.194.179
# Usage: bash scripts/install-turn.sh [TURN_PASSWORD]
#
# If TURN_PASSWORD is not supplied, a random 32-byte hex secret is generated
# and printed at the end — copy it into your .env file.
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

PUBLIC_IP="45.14.194.179"
REALM="connectcomms.local"
TURN_USER="connectcomms"
CONF_FILE="/etc/turnserver.conf"
DEFAULT_FILE="/etc/default/coturn"
RELAY_MIN=49152
RELAY_MAX=65535

# ── Password ───────────────────────────────────────────────────────────────
TURN_PASS="${1:-}"
if [[ -z "$TURN_PASS" ]]; then
  TURN_PASS="$(openssl rand -hex 24)"
  echo "Generated TURN password: $TURN_PASS"
  echo "(Add this to your .env as TURN_PASSWORD=$TURN_PASS)"
fi

# ── 1. Install coturn ──────────────────────────────────────────────────────
echo "→ Installing coturn..."
apt-get update -qq
apt-get install -y coturn openssl ssl-cert

# ── 2. Enable service ─────────────────────────────────────────────────────
echo "→ Enabling coturn service..."
sed -i 's/#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' "$DEFAULT_FILE" 2>/dev/null || true
grep -q "^TURNSERVER_ENABLED=1" "$DEFAULT_FILE" || echo "TURNSERVER_ENABLED=1" >> "$DEFAULT_FILE"

# ── 3. Locate TLS certificate ─────────────────────────────────────────────
# Prefer Let's Encrypt if present on the server, fall back to snakeoil
CERT_FILE="/etc/ssl/certs/ssl-cert-snakeoil.pem"
KEY_FILE="/etc/ssl/private/ssl-cert-snakeoil.key"

if [[ -f "/etc/letsencrypt/live/app.connectcomunications.com/fullchain.pem" ]]; then
  CERT_FILE="/etc/letsencrypt/live/app.connectcomunications.com/fullchain.pem"
  KEY_FILE="/etc/letsencrypt/live/app.connectcomunications.com/privkey.pem"
  echo "→ Using Let's Encrypt certificate for TLS"
else
  echo "→ Using snakeoil certificate for TLS (replace with Let's Encrypt for production)"
fi

# ── 4. Write /etc/turnserver.conf ─────────────────────────────────────────
echo "→ Writing $CONF_FILE..."
cat > "$CONF_FILE" << EOF
# ConnectComms coturn configuration
# Generated by scripts/install-turn.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ── Network ──────────────────────────────────────────────────────────────
listening-port=3478
tls-listening-port=5349
listening-ip=$PUBLIC_IP
relay-ip=$PUBLIC_IP
external-ip=$PUBLIC_IP

# ── Authentication ────────────────────────────────────────────────────────
fingerprint
lt-cred-mech
realm=$REALM
user=$TURN_USER:$TURN_PASS

# ── Quotas / rate limiting ────────────────────────────────────────────────
total-quota=200
bps-capacity=0
stale-nonce=600

# ── Security ─────────────────────────────────────────────────────────────
no-loopback-peers
no-multicast-peers
# Block RFC-1918 private ranges so coturn cannot be used as a proxy
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=172.16.0.0-172.31.255.255

# ── Relay ports ───────────────────────────────────────────────────────────
min-port=$RELAY_MIN
max-port=$RELAY_MAX

# ── TLS ───────────────────────────────────────────────────────────────────
cert=$CERT_FILE
pkey=$KEY_FILE

# ── Logging ───────────────────────────────────────────────────────────────
log-file=/var/log/turnserver.log
# Uncomment for verbose debugging:
# verbose
EOF

chmod 640 "$CONF_FILE"
chown root:root "$CONF_FILE" 2>/dev/null || true

# ── 5. Open firewall ports (UFW) ──────────────────────────────────────────
if command -v ufw &>/dev/null; then
  echo "→ Configuring UFW..."
  ufw allow 3478/tcp  comment "TURN TCP"  2>/dev/null || true
  ufw allow 3478/udp  comment "TURN UDP"  2>/dev/null || true
  ufw allow 5349/tcp  comment "TURNS TLS" 2>/dev/null || true
  ufw allow "$RELAY_MIN:$RELAY_MAX/udp" comment "TURN relay ports" 2>/dev/null || true
  echo "UFW rules added (run 'ufw status' to verify)"
else
  echo "→ UFW not found — ensure these ports are open on your firewall:"
  echo "   3478/tcp  3478/udp  5349/tcp  $RELAY_MIN-${RELAY_MAX}/udp"
fi

# ── iptables fallback ─────────────────────────────────────────────────────
if command -v iptables &>/dev/null && ! command -v ufw &>/dev/null; then
  echo "→ Adding iptables rules..."
  iptables -C INPUT -p tcp --dport 3478 -j ACCEPT 2>/dev/null || iptables -A INPUT -p tcp --dport 3478 -j ACCEPT
  iptables -C INPUT -p udp --dport 3478 -j ACCEPT 2>/dev/null || iptables -A INPUT -p udp --dport 3478 -j ACCEPT
  iptables -C INPUT -p tcp --dport 5349 -j ACCEPT 2>/dev/null || iptables -A INPUT -p tcp --dport 5349 -j ACCEPT
  iptables -C INPUT -p udp --dport "$RELAY_MIN:$RELAY_MAX" -j ACCEPT 2>/dev/null || \
    iptables -A INPUT -p udp --dport "$RELAY_MIN:$RELAY_MAX" -j ACCEPT
fi

# ── 6. Enable and start coturn ────────────────────────────────────────────
echo "→ Starting coturn..."
systemctl enable coturn
systemctl restart coturn
sleep 2

# ── 7. Print summary ──────────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════════════"
echo "  coturn installed and running"
echo "═══════════════════════════════════════════════════════"
systemctl is-active coturn && echo "  Status: active ✓" || echo "  Status: FAILED — check: journalctl -u coturn -n 50"
echo ""
echo "  Add these to /opt/connectcomms/app/.env (or your secrets):"
echo ""
echo "  TURN_SERVER=45.14.194.179"
echo "  TURN_USERNAME=$TURN_USER"
echo "  TURN_PASSWORD=$TURN_PASS"
echo ""
echo "  Then restart the API container:"
echo "    cd /opt/connectcomms/app"
echo "    docker compose -f docker-compose.app.yml up -d api worker"
echo ""
echo "  Verify with: bash scripts/test-turn.sh"
echo "═══════════════════════════════════════════════════════"
