[sonata-billing]
name = Sonata Billing
url = 
logo = /static/pictures/branding-desktop-logo.png?b0aad08b3f76602b6bc63bc1b5d07065
mobile_logo = /static/pictures/branding-mobile-logo.png?2340426fb9a00bceb8dcc06f05e3ff9f
fp_mobile_logo = /var/lib/vitalpbx/static/pictures/branding-mobile-logo.png
fp_desktop_logo = /var/lib/vitalpbx/static/pictures/branding-desktop-logo.png

[sonata-dialer]
name = Sonata Dialer
url = 
logo = /static/pictures/branding-desktop-logo.png?b0aad08b3f76602b6bc63bc1b5d07065
mobile_logo = /static/pictures/branding-mobile-logo.png?2340426fb9a00bceb8dcc06f05e3ff9f
fp_mobile_logo = /var/lib/vitalpbx/static/pictures/branding-mobile-logo.png
fp_desktop_logo = /var/lib/vitalpbx/static/pictures/branding-desktop-logo.png

[sonata-recordings]
name = Sonata Recordings
url = 
logo = /static/pictures/branding-desktop-logo.png?b0aad08b3f76602b6bc63bc1b5d07065
mobile_logo = /static/pictures/branding-mobile-logo.png?2340426fb9a00bceb8dcc06f05e3ff9f
fp_mobile_logo = /var/lib/vitalpbx/static/pictures/branding-mobile-logo.png
fp_desktop_logo = /var/lib/vitalpbx/static/pictures/branding-desktop-logo.png

[sonata-stats]
name = Sonata Stats
url = 
logo = /static/pictures/branding-desktop-logo.png?b0aad08b3f76602b6bc63bc1b5d07065
mobile_logo = /static/pictures/branding-mobile-logo.png?2340426fb9a00bceb8dcc06f05e3ff9f
fp_mobile_logo = /var/lib/vitalpbx/static/pictures/branding-mobile-logo.png
fp_desktop_logo = /var/lib/vitalpbx/static/pictures/branding-desktop-logo.png

[sonata-switchboard]
name = Sonata Switchboard
url = 
logo = /static/pictures/branding-desktop-logo.png?b0aad08b3f76602b6bc63bc1b5d07065
mobile_logo = /static/pictures/branding-mobile-logo.png?2340426fb9a00bceb8dcc06f05e3ff9f
fp_mobile_logo = /var/lib/vitalpbx/static/pictures/branding-mobile-logo.png
fp_desktop_logo = /var/lib/vitalpbx/static/pictures/branding-desktop-logo.png

[vitxi]
name = VitXi
url = 
logo = /static/pictures/branding-desktop-logo.png?b0aad08b3f76602b6bc63bc1b5d07065
mobile_logo = /static/pictures/branding-mobile-logo.png?2340426fb9a00bceb8dcc06f05e3ff9f
fp_mobile_logo = /var/lib/vitalpbx/static/pictures/branding-mobile-logo.png
fp_desktop_logo = /var/lib/vitalpbx/static/pictures/branding-desktop-logo.png
