import { webkit, devices } from "@playwright/test";
const b = await webkit.launch();
const ctx = await b.newContext({ ...devices["iPhone 14"] });
const p = await ctx.newPage();
p.on("console", (m) => { if (m.type() === "error" || m.type() === "warning") console.log("[console]", m.type(), m.text().slice(0, 220)); });
p.on("requestfailed", (r) => console.log("[reqfail]", r.method(), r.url(), r.failure()?.errorText));
p.on("response", (r) => { if (r.url().includes("3101")) console.log("[resp]", r.request().method(), r.status(), r.url()); });
await p.goto("http://localhost:3100/join", { waitUntil: "networkidle" });
const email = `wk-${Date.now()}@example.test`;
await p.getByTestId("join-first").fill("Web");
await p.getByTestId("join-last").fill("Kit");
await p.getByTestId("join-email").fill(email);
await p.getByTestId("join-password").fill("E2e-strong-pass-42");
await p.getByTestId("join-tos").check();
await p.getByTestId("join-submit").click();
await p.waitForTimeout(6000);
console.log("url after submit:", p.url());
console.log("alerts:", await p.locator('[role="alert"]').allInnerTexts());
await b.close();
