import { webkit, devices } from "@playwright/test";
const API = "http://localhost:3101";
const b = await webkit.launch();
const ctx = await b.newContext({ ...devices["iPhone 14"] });
const p = await ctx.newPage();
const mk = async (tag) => { const email = `wki-${tag}-${Date.now()}@example.test`; const r = await fetch(`${API}/auth/register`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ firstName: "Web", lastName: "Kit" + tag, email, password: "E2e-strong-pass-42" }) }).then((r) => r.json()); const c = await fetch(`${API}/dev/last-code?target=${encodeURIComponent(email)}`).then((r) => r.json()); await fetch(`${API}/auth/verify/confirm`, { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${r.accessToken}` }, body: JSON.stringify({ purpose: "email", target: email, code: c.code }) }); return r; };
const a = await mk("a"); const t = await mk("t");
await p.goto("http://localhost:3100/login");
await p.evaluate(([acc, ref]) => { localStorage.setItem("lc.access", acc); localStorage.setItem("lc.refresh", ref); }, [a.accessToken, a.refreshToken]);
await p.goto(`http://localhost:3100/people/${t.person.username}`);
await p.getByTestId("profile-message").click();
await p.waitForURL(/\/messages\//);
await p.getByTestId("messages-input").fill("Hi there");
await p.getByTestId("messages-send").click();
await p.waitForTimeout(1500);
console.log("report visible before:", await p.getByTestId("messages-info-report").filter({ visible: true }).count());
await p.getByRole("button", { name: "Conversation actions" }).click();
await p.waitForTimeout(300);
console.log("conv-info visible:", await p.getByTestId("messages-conv-info").isVisible());
await p.getByTestId("messages-conv-info").click();
await p.waitForTimeout(800);
console.log("dialog count:", await p.locator('[role="dialog"]').count(), "report visible after:", await p.getByTestId("messages-info-report").filter({ visible: true }).count());
await p.screenshot({ path: "e2e/screenshots/_debug-info.png" });
await b.close();
