import { StyleSheet } from 'react-native';
import { darkColors } from './colors';

export const colors = StyleSheet.create({
  screen: { flex: 1, backgroundColor: darkColors.bg },
  topbar: {
    height: 52,
    backgroundColor: darkColors.bgSecondary,
    borderBottomWidth: 1,
    borderBottomColor: darkColors.border,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topbarTitle: { color: darkColors.text, fontSize: 15, fontWeight: '600' },
  topbarAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: darkColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topbarAvatarText: { color: darkColors.white, fontSize: 11, fontWeight: '700' },
  content: { flex: 1, padding: 12 },
  card: {
    backgroundColor: darkColors.surface,
    borderColor: darkColors.border,
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  title: { fontSize: 22, fontWeight: '700', color: darkColors.text, marginBottom: 10 },
  sectionTitle: { fontSize: 14, fontWeight: '600', color: darkColors.text, marginBottom: 10 },
  text: { color: darkColors.textSecondary, fontSize: 13, marginBottom: 6 },
  input: {
    height: 44,
    borderWidth: 1,
    borderColor: darkColors.border,
    borderRadius: 10,
    backgroundColor: darkColors.surfaceElevated,
    paddingHorizontal: 14,
    color: darkColors.text,
    marginBottom: 10,
    fontSize: 15,
  },
  button: {
    height: 44,
    borderRadius: 10,
    backgroundColor: darkColors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginRight: 8,
    marginBottom: 8,
  },
  buttonText: { color: darkColors.white, fontSize: 14, fontWeight: '600' },
  row: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center' },
  chip: {
    paddingHorizontal: 10,
    height: 24,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    marginRight: 8,
    marginBottom: 4,
  },
  chipText: { fontSize: 10, fontWeight: '700' },
});
