; *********************************************************************************
; @Date : Sun May 3 21:39:04 GMT 2026
; @Document : cdr__10-general.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general]
enable = yes
debug = no
unanswered = yes
congestion = yes
endbeforehexten = yes
initiatedseconds = no
safeshutdown = yes
batch = no
size = 100
time = 300
