; *********************************************************************************
; @Date : Sun May 3 21:39:04 GMT 2026
; @Document : cel__10-general.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general]
enable=yes
apps=dial,park,queue,confbridge,voicemail,originate,page,voicemailmain,transfer,blindtransfer,attendedtransfer
events=APP_START,CHAN_START,CHAN_END,ANSWER,HANGUP,BRIDGE_ENTER,BRIDGE_EXIT,BLINDTRANSFER,ATTENDEDTRANSFER,PICKUP,FORWARD,USER_DEFINED
dateformat=%F %T
