; *********************************************************************************
; @Date : Wed Jun 3 1:01:36 GMT 2026
; @Document : confbridge__50-32-profiles.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

