; *********************************************************************************
; @Date : Wed Jun 3 1:01:36 GMT 2026
; @Document : confbridge__40-32-menu.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

