; *********************************************************************************
; @Date : Sun May 3 21:39:16 GMT 2026
; @Document : confbridge__50-6-profiles.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

