; *********************************************************************************
; @Date : Thu May 21 16:43:10 GMT 2026
; @Document : confbridge__50-28-profiles.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

