; *********************************************************************************
; @Date : Sun May 3 21:39:35 GMT 2026
; @Document : confbridge__50-20-profiles.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

