; *********************************************************************************
; @Date : Wed Jun 3 0:56:31 GMT 2026
; @Document : confbridge__50-31-profiles.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

