; *********************************************************************************
; @Date : Fri May 29 15:01:52 GMT 2026
; @Document : confbridge__50-30-profiles.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

