; *********************************************************************************
; @Date : Thu May 14 15:12:17 GMT 2026
; @Document : confbridge__50-3-profiles.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

