; *********************************************************************************
; @Date : Thu May 21 16:43:28 GMT 2026
; @Document : confbridge__50-29-profiles.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

