; *********************************************************************************
; @Date : Fri May 29 15:01:52 GMT 2026
; @Document : extensions__25-30-hints.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T30_extension-hints]
exten => 300,hint,pjsip/T30_300&pjsip/T30_300_1&Custom:T30_DND_300

exten => 101,hint,pjsip/T30_101&pjsip/T30_101_1&Custom:T30_DND_101

exten => 102,hint,pjsip/T30_102&pjsip/T30_102_1&Custom:T30_DND_102

exten => unavailable,hint,T30_unavailable

exten => QAGENT,hint,Custom:T30_QAGENT

exten => 701,hint,park:701@parking-30-parkedcalls

exten => 702,hint,park:702@parking-30-parkedcalls

exten => 703,hint,park:703@parking-30-parkedcalls

exten => 704,hint,park:704@parking-30-parkedcalls

exten => 705,hint,park:705@parking-30-parkedcalls

exten => 706,hint,park:706@parking-30-parkedcalls

exten => 707,hint,park:707@parking-30-parkedcalls

exten => 708,hint,park:708@parking-30-parkedcalls

exten => 709,hint,park:709@parking-30-parkedcalls

exten => 710,hint,park:710@parking-30-parkedcalls


