; *********************************************************************************
; @Date : Thu Jun 4 10:46:33 GMT 2026
; @Document : extensions__25-2-hints.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T2_extension-hints]
exten => 103,hint,pjsip/T2_103&pjsip/T2_103_1&Custom:T2_DND_103

exten => Agent103,hint,pjsip/T2_103&pjsip/T2_103_1&Custom:T2_QAGENT

exten => QA_103,hint,pjsip/T2_103&pjsip/T2_103_1

exten => 108,hint,pjsip/T2_108&pjsip/T2_108_1&Custom:T2_DND_108

exten => 107,hint,pjsip/T2_107&Custom:T2_DND_107

exten => 101,hint,pjsip/T2_101&Custom:T2_DND_101

exten => 102,hint,pjsip/T2_102&Custom:T2_DND_102

exten => 104,hint,pjsip/T2_104&Custom:T2_DND_104

exten => 105,hint,pjsip/T2_105&Custom:VirtualDev178&Custom:T2_DND_105

exten => Agent105,hint,pjsip/T2_105&Custom:VirtualDev178&Custom:T2_QAGENT

exten => QA_105,hint,pjsip/T2_105&Custom:VirtualDev178

exten => 106,hint,Custom:VirtualDev9&Custom:T2_DND_106

exten => 109,hint,Custom:VirtualDev10&Custom:T2_DND_109

exten => 110,hint,Custom:VirtualDev159&pjsip/T2_110&Custom:T2_DND_110

exten => 502,hint,pjsip/T2_502&Custom:T2_DND_502

exten => 503,hint,pjsip/T2_503&Custom:T2_DND_503

exten => 504,hint,pjsip/T2_504&Custom:T2_DND_504

exten => 505,hint,pjsip/T2_505&Custom:T2_DND_505

exten => 506,hint,pjsip/T2_506&Custom:T2_DND_506

exten => 507,hint,pjsip/T2_507&Custom:T2_DND_507

exten => 509,hint,pjsip/T2_509&Custom:T2_DND_509

exten => 510,hint,pjsip/T2_510&Custom:T2_DND_510

exten => 111,hint,pjsip/T2_111&Custom:T2_DND_111

exten => 112,hint,pjsip/T2_112&Custom:T2_DND_112

exten => unavailable,hint,T2_unavailable

exten => QAGENT,hint,Custom:T2_QAGENT

exten => QAL_103_600,hint,Custom:T2_QAL_103_600
 same => 1,Set(__QNUMBER=600)
 same => 2,Gosub(T2_cos-all-init,*50*600,1)

exten => QAL_103,hint,Custom:T2_QAL_103
 same => 1,Gosub(T2_cos-all-init,*52,1)

exten => QAP_103_600,hint,Custom:T2_QAP_103_600
 same => 1,Set(__QNUMBER=600)
 same => 2,Gosub(T2_cos-all-init,*51*600,1)

exten => QAP_103,hint,Custom:T2_QAP_103
 same => 1,Gosub(T2_cos-all-init,*53,1)

exten => QAL_105_600,hint,Custom:T2_QAL_105_600
 same => 1,Set(__QNUMBER=600)
 same => 2,Gosub(T2_cos-all-init,*50*600,1)

exten => QAL_105,hint,Custom:T2_QAL_105
 same => 1,Gosub(T2_cos-all-init,*52,1)

exten => QAP_105_600,hint,Custom:T2_QAP_105_600
 same => 1,Set(__QNUMBER=600)
 same => 2,Gosub(T2_cos-all-init,*51*600,1)

exten => QAP_105,hint,Custom:T2_QAP_105
 same => 1,Gosub(T2_cos-all-init,*53,1)

exten => 701,hint,park:701@parking-2-parkedcalls

exten => 702,hint,park:702@parking-2-parkedcalls

exten => 703,hint,park:703@parking-2-parkedcalls

exten => 704,hint,park:704@parking-2-parkedcalls

exten => 705,hint,park:705@parking-2-parkedcalls

exten => 706,hint,park:706@parking-2-parkedcalls

exten => 707,hint,park:707@parking-2-parkedcalls

exten => 708,hint,park:708@parking-2-parkedcalls

exten => 709,hint,park:709@parking-2-parkedcalls

exten => 710,hint,park:710@parking-2-parkedcalls

exten => TC1,hint,Custom:TC1
 same => 1,NoOp(Time Condition: Main)
 same => n,Gosub(sub-set-global-vars,s,1(f3df739ac62197cd,${EXTEN},parking-2))
 same => n,Gosub(sub-set-call-vars,s,1(f3df739ac62197cd,${EXTEN},,,))
 same => n,Gosub(sub-construct-cid,s,1)
 same => n,Gosub(sub-toggle-tc-state,s,1(1,TG-1))


