; *********************************************************************************
; @Date : Sun May 3 21:39:12 GMT 2026
; @Document : extensions__25-4-hints.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T4_extension-hints]
exten => 201,hint,pjsip/T4_201&Custom:T4_DND_201

exten => 202,hint,pjsip/T4_202&Custom:T4_DND_202

exten => 203,hint,pjsip/T4_203&Custom:T4_DND_203

exten => unavailable,hint,T4_unavailable

exten => QAGENT,hint,Custom:T4_QAGENT

exten => 701,hint,park:701@parking-4-parkedcalls

exten => 702,hint,park:702@parking-4-parkedcalls

exten => 703,hint,park:703@parking-4-parkedcalls

exten => 704,hint,park:704@parking-4-parkedcalls

exten => 705,hint,park:705@parking-4-parkedcalls

exten => 706,hint,park:706@parking-4-parkedcalls

exten => 707,hint,park:707@parking-4-parkedcalls

exten => 708,hint,park:708@parking-4-parkedcalls

exten => 709,hint,park:709@parking-4-parkedcalls

exten => 710,hint,park:710@parking-4-parkedcalls


