; An example on how to add a custom feature code that tells you the current time
; by appending to context cos-all

; [cos-all](+)
; exten => *250,1,NoOp(FEATURE: SAY CLOCK)
;  same => n,Answer
;  same => n,NoCDR()
;  same => n,Wait(1)
;  same => n,Playback(at-tone-time-exactly)
;  same => n,Playback(beep)
;  same => n,SayUnixTime(,,AdBY)
;  same => n,Wait(1)
;  same => n,SayUnixTime(,,IMp)
;  same => n,Wait(1)
;  same => n,Hangup()
