; *********************************************************************************
; @Date : Fri May 8 12:47:27 GMT 2026
; @Document : extensions__25-18-hints.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T18_extension-hints]
exten => 101,hint,pjsip/T18_101&pjsip/T18_101_1&Custom:T18_DND_101

exten => 105,hint,pjsip/T18_105&pjsip/T18_105_1&Custom:T18_DND_105

exten => 106,hint,pjsip/T18_106&pjsip/T18_106_1&Custom:T18_DND_106

exten => 389,hint,Custom:VirtualDev127&Custom:T18_DND_389

exten => 662,hint,Custom:VirtualDev128&Custom:T18_DND_662

exten => 104,hint,pjsip/T18_104&Custom:T18_DND_104

exten => unavailable,hint,T18_unavailable

exten => QAGENT,hint,Custom:T18_QAGENT

exten => 701,hint,park:701@parking-18-parkedcalls

exten => 702,hint,park:702@parking-18-parkedcalls

exten => 703,hint,park:703@parking-18-parkedcalls

exten => 704,hint,park:704@parking-18-parkedcalls

exten => 705,hint,park:705@parking-18-parkedcalls

exten => 706,hint,park:706@parking-18-parkedcalls

exten => 707,hint,park:707@parking-18-parkedcalls

exten => 708,hint,park:708@parking-18-parkedcalls

exten => 709,hint,park:709@parking-18-parkedcalls

exten => 710,hint,park:710@parking-18-parkedcalls

exten => TC11,hint,Custom:TC11
 same => 1,NoOp(Time Condition: Main)
 same => n,Gosub(sub-set-global-vars,s,1(fb6a694802f40408,${EXTEN},parking-18))
 same => n,Gosub(sub-set-call-vars,s,1(fb6a694802f40408,${EXTEN},,,))
 same => n,Gosub(sub-construct-cid,s,1)
 same => n,Gosub(sub-toggle-tc-state,s,1(11,TG-11))


