; *********************************************************************************
; @Date : Tue May 26 14:16:08 GMT 2026
; @Document : extensions__25-28-hints.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T28_extension-hints]
exten => 101,hint,pjsip/T28_101&Custom:T28_DND_101

exten => 102,hint,pjsip/T28_102&pjsip/T28_102_1&Custom:T28_DND_102

exten => 103,hint,pjsip/T28_103&Custom:T28_DND_103

exten => 104,hint,pjsip/T28_104&Custom:T28_DND_104

exten => 105,hint,pjsip/T28_105&Custom:T28_DND_105

exten => 106,hint,pjsip/T28_106&Custom:T28_DND_106

exten => 107,hint,pjsip/T28_107&Custom:T28_DND_107

exten => unavailable,hint,T28_unavailable

exten => QAGENT,hint,Custom:T28_QAGENT

exten => 701,hint,park:701@parking-28-parkedcalls

exten => 702,hint,park:702@parking-28-parkedcalls

exten => 703,hint,park:703@parking-28-parkedcalls

exten => 704,hint,park:704@parking-28-parkedcalls

exten => 705,hint,park:705@parking-28-parkedcalls

exten => 706,hint,park:706@parking-28-parkedcalls

exten => 707,hint,park:707@parking-28-parkedcalls

exten => 708,hint,park:708@parking-28-parkedcalls

exten => 709,hint,park:709@parking-28-parkedcalls

exten => 710,hint,park:710@parking-28-parkedcalls


