; *********************************************************************************
; @Date : Sun May 3 21:39:03 GMT 2026
; @Document : features__50-main.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general]
pickupexten = *08
transferdigittimeout => 3
featuredigittimeout = 1000
atxfernoanswertimeout = 15
atxferdropcall = no

[featuremap]
blindxfer => #1
disconnect => *0
automon =>
atxfer => *2
parkcall => *4
automixmon =>