[applicationmap]
one_touch_rec => *3,self/caller,Gosub(sub-call-recording-on-demand,s,1(app,fmap))
auto_rec_switch_out => *00,peer/caller,Gosub(sub-auto-recording-switch,s,1) ; Outgoing
auto_rec_switch_in => *1,self/caller,Gosub(sub-auto-recording-switch,s,1) ; Incoming

[custom-features]
one_touch_rec =>
auto_rec_switch_out =>
auto_rec_switch_in =>