[general]

[LOCK-PHONE]
writehandle=vitalpbx
readsql=SELECT `lock` FROM ombu_extensions WHERE extension='${SQL_ESC(${ARG1})}' and tenant_id=(SELECT tenant_id from ombu_tenants WHERE path='${SQL_ESC(${ARG2})}')
writesql=UPDATE ombu_extensions SET `lock`='${SQL_ESC(${VAL1})}' WHERE extension='${SQL_ESC(${ARG1})}' and tenant_id=(SELECT tenant_id from ombu_tenants WHERE path='${SQL_ESC(${ARG2})}')

[VOICEMAIL-PASSWORD]
writehandle=vitalpbx
writesql=UPDATE ombu_extensions_vm as vm LEFT JOIN ombu_extensions as e ON (e.`extension_id` = vm.`extension_id`) SET vm.`password`='${SQL_ESC(${VAL1})}' WHERE e.`extension`='${SQL_ESC(${ARG1})}' and `e`.`tenant_id`=(SELECT tenant_id from ombu_tenants WHERE path='${SQL_ESC(${ARG2})}')

[DIVERSIONS]
writehandle=vitalpbx
writesql=UPDATE ombu_extension_diversions as d LEFT JOIN ombu_extensions as e ON (e.`extension_id` = d.`extension_id`) SET d.`enable`='${SQL_ESC(${VAL1})}' WHERE (e.`extension`='${SQL_ESC(${ARG1})}' and `e`.`tenant_id`=(SELECT tenant_id from ombu_tenants WHERE path='${SQL_ESC(${ARG2})}')) and d.`name`='${SQL_ESC(${ARG3})}'

[QUEUES-LIST]
writehandle=vitalpbx
readsql=SELECT GROUP_CONCAT(extension SEPARATOR '^') as `queues` FROM ombu_queues where tenant_id=(SELECT tenant_id from ombu_tenants WHERE path='${SQL_ESC(${ARG1})}')

[TENANT-DID-NUMBERS]
writehandle=vitalpbx
readsql=SELECT `did` FROM ombu_tenant_dids WHERE did='${SQL_ESC(${ARG1})}'

[EXTENSION-ID]
writehandle=vitalpbx
prefix=GET
readsql=SELECT `extension_id` FROM ombu_extensions WHERE extension='${SQL_ESC(${ARG1})}' and tenant_id=(SELECT tenant_id from ombu_tenants WHERE path='${SQL_ESC(${ARG2})}')

[VIRTUAL-DEVICES]
writehandle=vitalpbx
prefix=GET
readsql=SELECT device_id FROM ombu_devices WHERE extension_id = ( SELECT extension_id FROM ombu_extensions WHERE extension = '${SQL_ESC(${ARG1})}' AND tenant_id = ( SELECT tenant_id FROM ombu_tenants WHERE path = '${SQL_ESC(${ARG2})}' ) ) AND tenant_id = ( SELECT tenant_id FROM ombu_tenants WHERE path = '${SQL_ESC(${ARG2})}' ) AND technology = 'virtual'
mode=multirow

[EMERGENCY-CID]
writehandle=vitalpbx
prefix=GET
readsql=SELECT `cid_name`, `cid_number` FROM ombu_emergency_locations WHERE id='${SQL_ESC(${ARG1})}' and tenant_id=(SELECT tenant_id from ombu_tenants WHERE path='${SQL_ESC(${ARG2})}')

[DEFAULT-EMERGENCY-CID]
writehandle=vitalpbx
prefix=GET
readsql=SELECT `cid_name`, `cid_number` FROM ombu_emergency_locations WHERE `default` = 'yes' and tenant_id=(SELECT tenant_id from ombu_tenants WHERE path='${SQL_ESC(${ARG1})}')

[EXTENSION-SETTING]
writehandle=vitalpbx
readsql=SELECT `${SQL_ESC(${ARG1})}` FROM ombu_extensions WHERE extension='${SQL_ESC(${ARG2})}' and tenant_id=(SELECT tenant_id from ombu_tenants WHERE path='${SQL_ESC(${ARG3})}')

[EXTENSION-CRM-ID]
writehandle=vitalpbx
prefix=GET
readsql=SELECT `crm_id` FROM crm_users WHERE extension_id=${SQL_ESC(${ARG1})}

