[WK-STATE]
writehandle=vitalpbx
writesql=INSERT INTO ombu_room_wakeup_call_state VALUES(${SQL_ESC(${VAL1})},'${SQL_ESC(${VAL2})}') ON DUPLICATE KEY UPDATE state='${SQL_ESC(${VAL2})}'

[ROOM-STATE]
writehandle=vitalpbx
writesql=INSERT INTO ombu_room_state VALUES(${SQL_ESC(${VAL1})},${SQL_ESC(${VAL2})}) ON DUPLICATE KEY UPDATE status_id=${SQL_ESC(${VAL2})}

[ROOM-CONSUMPTION]
writehandle=vitalpbx
writesql=INSERT INTO ombu_room_consumption VALUES(${SQL_ESC(${VAL1})},${SQL_ESC(${VAL2})})