[AUTH-DEST-CODE]
writehandle=vitalpbx
prefix=GET
readsql=SELECT `auth_code`,`cid_name` FROM ombu_auth_destinations_groups_codes WHERE auth_destination_group_id='${SQL_ESC(${ARG1})}' and auth_code='${SQL_ESC(${ARG2})}'