; *********************************************************************************
; @Date : Sun May 3 21:39:04 GMT 2026
; @Document : http__10-general.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general]
tlsbindaddr=0.0.0.0:8089
bindaddr=0.0.0.0
bindport=8088
enabled=yes
tlsenable=yes
sessionlimit=1000
tlscertfile=/usr/share/vitalpbx/certificates/m.connectcomunications.com/bundle.pem
tlsprivatekey=/usr/share/vitalpbx/certificates/m.connectcomunications.com/private.pem
