; *********************************************************************************
; @Date : Thu May 21 16:43:28 GMT 2026
; @Document : iax__20-29-registers.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general](+)
