; *********************************************************************************
; @Date : Fri May 29 15:01:51 GMT 2026
; @Document : iax__50-30-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


