; *********************************************************************************
; @Date : Thu May 28 5:47:38 GMT 2026
; @Document : iax__10-general.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general]
rtcachefriends=yes
bindport=4569
language=en
bandwidth=low
adsi=yes
srvlookup=no
nochecksums=yes
iaxcompat=yes
minregexpire=60
maxregexpire=60
iaxthreadcount=10
iaxmaxthreadcount=100
autokill=yes
trunkfreq=20
authdebug=no
trunktimestamps=yes
codecpriority=caller
allow=!all,ulaw,alaw,g729
