; *********************************************************************************
; @Date : Wed May 27 4:41:10 GMT 2026
; @Document : iax__50-1-trunks.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

