; *********************************************************************************
; @Date : Sun May 3 21:39:31 GMT 2026
; @Document : iax__50-14-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


