; *********************************************************************************
; @Date : Wed Jun 3 1:01:36 GMT 2026
; @Document : iax__20-32-registers.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general](+)
