; *********************************************************************************
; @Date : Wed Jun 3 0:56:31 GMT 2026
; @Document : iax__20-31-registers.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general](+)
