; *********************************************************************************
; @Date : Fri May 29 15:01:52 GMT 2026
; @Document : iax__50-30-trunks.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

