; *********************************************************************************
; @Date : Thu May 28 5:47:38 GMT 2026
; @Document : iax__50-limits.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[callnumberlimits]

