; *********************************************************************************
; @Date : Thu May 21 16:43:28 GMT 2026
; @Document : iax__50-29-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


