; *********************************************************************************
; @Date : Sun May 3 21:39:31 GMT 2026
; @Document : iax__20-14-registers.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general](+)
