; *********************************************************************************
; @Date : Thu May 21 16:43:10 GMT 2026
; @Document : iax__20-28-registers.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general](+)
