; *********************************************************************************
; @Date : Sun May 3 21:39:04 GMT 2026
; @Document : logger__10-general.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general]
dateformat=%F %T
appendhostname=no
rotatestrategy=sequential
queue_log_realtime_use_gmt = yes
queue_log = yes