; *********************************************************************************
; @Date : Sun May 3 21:39:04 GMT 2026
; @Document : logger__50-files.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[logfiles]
fail2ban => debug,dtmf,error,notice,verbose(15),warning,security
console => debug,dtmf,error,notice,verbose(3),warning,security
full => debug,dtmf,error,notice,verbose(3),warning,security