; *********************************************************************************
; @Date : Sun May 3 21:39:26 GMT 2026
; @Document : manager__50-10-users.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


