; *********************************************************************************
; @Date : Sun May 3 21:39:35 GMT 2026
; @Document : manager__50-20-users.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


