; *********************************************************************************
; @Date : Sun May 3 21:39:12 GMT 2026
; @Document : manager__50-4-users.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


