[modules](+)
; pre-load some modules that will be loaded before pbx_config.
; This is needed before some parsing of the dialplan (related to hints)
; is done at load time rather than at run time.
preload => res_odbc.so
preload => res_config_odbc.so
preload => func_logic.so
preload => func_strings.so
preload => func_db.so
