; Modules not to load automatically.
[modules](+)
; Only a single voicemail module should be loaded. We use app_voicemail.so:
noload => app_directory_odbcstorage.so
noload => app_voicemail_odbcstorage.so
noload => app_minivm.so

; Alternative console channel drivers: We use chan_alsa:
noload => chan_oss.so
noload => chan_console.so

; Other completely useless channel drivers:
noload => chan_motif.so
noload => chan_mgcp.so
noload => chan_phone.so
noload => chan_skinny.so
noload => chan_unistim.so

; Alternative configuration mechanisms:
noload => res_config_ldap.so
noload => res_config_pgsql.so
noload => res_config_sqlite
noload => res_config_sqlite3
noload => pbx_ael.so
noload => pbx_lua.so

; CDR mechanisms we don't use:
noload => cel_custom.so
noload => cdr_manager.so
noload => cdr_odbc.so
noload => cdr_custom.so
noload => cdr_pgsql.so
noload => cel_pgsql.so
noload => cdr_radius.so
noload => cel_radius.so
noload => cdr_sqlite3_custom.so
noload => cel_sqlite3_custom.so
noload => cdr_syslog.so
noload => cdr_tds.so
noload => cel_tds.so
noload => cdr_mysql.so
noload => app_mysql.so
noload => res_config_mysql.so

noload => pbx_dundi.so
noload => res_hep.so
noload => res_hep_rtcp.so
noload => res_phoneprov.so
noload => res_snmp.so

; Disable DPMA Drivers
noload => res_digium_phone.so
noload => res_pjsip_endpoint_identifier_dpma.so
noload => res_pjsip_dialog_info_digium_body_supplement.so
noload => res_pjsip_pidf_digium_body_supplement.so

; Don't edit this file.
; If you want to override it, create a new file.
; e.g. /etc/asterisk/vitalpbx/modules-30-odbc_voicemail.conf:
;[modules](+)
;noload => app_voicemail.so
;load => app_voicemail_odbcstorage.so
