; *********************************************************************************
; @Date : Wed May 20 16:19:21 GMT 2026
; @Document : musiconhold__50-1-main.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[default]
mode=files
directory=/var/lib/vitalpbx/static/2dc3974017c1bc65/moh/moh3
sort=random

[moh3]
mode=files
directory=/var/lib/vitalpbx/static/2dc3974017c1bc65/moh/moh3
sort=random

[moh5]
mode=files
directory=/var/lib/vitalpbx/static/2dc3974017c1bc65/moh/moh5
sort=random

[moh8]
mode=files
directory=/var/lib/vitalpbx/static/2dc3974017c1bc65/moh/moh8
sort=alpha

