; *********************************************************************************
; @Date : Thu May 14 15:12:17 GMT 2026
; @Document : musiconhold__50-3-main.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[moh4]
mode=files
directory=/var/lib/vitalpbx/static/56a4d7cbd1c39e31/moh/moh4
sort=random

