; *********************************************************************************
; @Date : Thu May 7 18:58:02 GMT 2026
; @Document : pjsip__50-21-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T21_101](p1)
type=endpoint
auth=authT21_101
identify_by=username,auth_username
outbound_auth=authT21_101
aors=T21_101
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T21_101
set_var=CHANNEL(parkinglot)=parking-21
subscribe_context=T21_extension-hints
language=en
moh_suggest=default
context=T21_cos-all
mailboxes=101@test-voicemail
device_state_busy_at=0
callerid="Home" <101>

[authT21_101]
type=auth
auth_type=userpass
username=T21_101
password=REDACTED

[T21_101](p1-aor)
type=aor
max_contacts=5

[T21_102](p1)
type=endpoint
auth=authT21_102
identify_by=username,auth_username
outbound_auth=authT21_102
aors=T21_102
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T21_102
set_var=CHANNEL(parkinglot)=parking-21
subscribe_context=T21_extension-hints
language=en
moh_suggest=default
context=T21_cos-all
mailboxes=102@test-voicemail
device_state_busy_at=0
callerid="home 2" <102>

[authT21_102]
type=auth
auth_type=userpass
username=T21_102
password=REDACTED

[T21_102](p1-aor)
type=aor
max_contacts=5

[T21_101_1](p12)
type=endpoint
auth=authT21_101_1
identify_by=username,auth_username
outbound_auth=authT21_101_1
aors=T21_101_1
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T21_101_1
set_var=CHANNEL(parkinglot)=parking-21
subscribe_context=T21_extension-hints
language=en
moh_suggest=default
context=T21_cos-all
mailboxes=101@test-voicemail
device_state_busy_at=0
callerid="Home" <101>

[authT21_101_1]
type=auth
auth_type=userpass
username=T21_101_1
password=REDACTED

[T21_101_1](p12-aor)
type=aor
max_contacts=3


