; *********************************************************************************
; @Date : Thu May 28 5:47:37 GMT 2026
; @Document : pjsip__50-1-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[101](p1)
type=endpoint
auth=auth101
identify_by=username,auth_username
outbound_auth=auth101
aors=101
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=101
set_var=CHANNEL(parkinglot)=parking-1
subscribe_context=extension-hints
language=en
moh_suggest=default
context=cos-all
mailboxes=101@vitalpbx-voicemail
device_state_busy_at=0
callerid="izzy" <101>

[auth101]
type=auth
auth_type=userpass
username=101
password=REDACTED

[101](p1-aor)
type=aor
max_contacts=5

[101_1](p1)
type=endpoint
auth=auth101_1
identify_by=username,auth_username
outbound_auth=auth101_1
aors=101_1
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=101_1
set_var=CHANNEL(parkinglot)=parking-1
subscribe_context=extension-hints
language=en
moh_suggest=default
context=cos-all
mailboxes=101@vitalpbx-voicemail
device_state_busy_at=0
callerid="izzy" <101>

[auth101_1]
type=auth
auth_type=userpass
username=101_1
password=REDACTED

[101_1](p1-aor)
type=aor
max_contacts=3


