; rfc3842
; put empty "Content=>" at the end to have CRLF after last body line

[clear-mwi]
Event=>message-summary
Content-type=>application/simple-message-summary
Content=>Messages-Waiting: no
Content=>Message-Account: sip:asterisk@127.0.0.1
Content=>Voice-Message: 0/0 (0/0)
Content=>

; Aastra
[reboot-aastra]
Event=>check-sync

[aastra-xml]
Event=>aastra-xml

; Digium
[reboot-digium]
Event=>check-sync

; Linksys
[reboot-linksys]
Event=>reboot_now

[linksys-cold-restart]
Event=>reboot_now

[linksys-warm-restart]
Event=>restart_now

; Polycom
[reboot-polycom]
Event=>check-sync

[reboot-poly]
Event=>check-sync

[polycom-check-cfg]
Event=>check-sync

[poly-check-cfg]
Event=>check-sync

; Sipura
[reboot-sipura]
Event=>resync

[sipura-get-report]
Event=>report

; Snom
[snom-check-cfg]
Event=>check-sync\;reboot=false

[reboot-snom]
Event=>check-sync\;reboot=true

; Cisco
[reboot-cisco]
Event=>check-sync

[cisco-check-cfg]
Event=>check-sync

; Yealink
[yealink-check-cfg]
Event=>check-sync\;reboot=false

[reboot-yealink]
Event=>check-sync\;reboot=true

; Fanvil
[reboot-fanvil]
Event => check-sync\;reboot=true

; Grandstream
[reboot-grandstream]
Event => reboot, Content-Length => 0

; Vtech
[reboot-vtech]
Event => check-sync

; Htek
[reboot-htek]
Event => check-sync;check-sync;reboot=false;check-sync;reboot=true;reboot

; ALE
[reboot-alcatel]
Event=>check-sync\;reboot=true

; Atcom
[reboot-atcom]
Event=>check-sync\;reboot=true