; *********************************************************************************
; @Date : Sun May 3 21:39:44 GMT 2026
; @Document : pjsip__50-26-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T26_101](p1)
type=endpoint
auth=authT26_101
identify_by=username,auth_username
outbound_auth=authT26_101
aors=T26_101
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T26_101
set_var=CHANNEL(parkinglot)=parking-26
subscribe_context=T26_extension-hints
language=en
moh_suggest=default
context=T26_cos-all
mailboxes=101@luzer-voicemail
device_state_busy_at=0
callerid="Luzer" <101>

[authT26_101]
type=auth
auth_type=userpass
username=T26_101
password=REDACTED

[T26_101](p1-aor)
type=aor
max_contacts=5


