; *********************************************************************************
; @Date : Tue May 19 7:26:26 GMT 2026
; @Document : pjsip__50-11-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T11_103](p1)
type=endpoint
auth=authT11_103
identify_by=username,auth_username
outbound_auth=authT11_103
aors=T11_103
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T11_103
set_var=CHANNEL(parkinglot)=parking-11
subscribe_context=T11_extension-hints
language=en
moh_suggest=default
context=T11_cos-all
mailboxes=103@trimpro-voicemail
device_state_busy_at=0
callerid="Shlomie folkowits" <103>

[authT11_103]
type=auth
auth_type=userpass
username=T11_103
password=REDACTED

[T11_103](p1-aor)
type=aor
max_contacts=5

[T11_105](p1)
type=endpoint
auth=authT11_105
identify_by=username,auth_username
outbound_auth=authT11_105
aors=T11_105
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T11_105
set_var=CHANNEL(parkinglot)=parking-11
subscribe_context=T11_extension-hints
language=en
moh_suggest=default
context=T11_cos-all
mailboxes=105@trimpro-voicemail
device_state_busy_at=0
callerid="Shia Weinstock" <105>

[authT11_105]
type=auth
auth_type=userpass
username=T11_105
password=REDACTED

[T11_105](p1-aor)
type=aor
max_contacts=5

[T11_101](p1)
type=endpoint
auth=authT11_101
identify_by=username,auth_username
outbound_auth=authT11_101
aors=T11_101
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T11_101
set_var=CHANNEL(parkinglot)=parking-11
subscribe_context=T11_extension-hints
language=en
moh_suggest=default
context=T11_cos-all
mailboxes=101@trimpro-voicemail
device_state_busy_at=0
callerid="Nachemya Ungar" <101>

[authT11_101]
type=auth
auth_type=userpass
username=T11_101
password=REDACTED

[T11_101](p1-aor)
type=aor
max_contacts=5

[T11_102](p1)
type=endpoint
auth=authT11_102
identify_by=username,auth_username
outbound_auth=authT11_102
aors=T11_102
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T11_102
set_var=CHANNEL(parkinglot)=parking-11
subscribe_context=T11_extension-hints
language=en
moh_suggest=default
context=T11_cos-all
mailboxes=102@trimpro-voicemail
device_state_busy_at=0
callerid="Mrs. Schwarts" <102>

[authT11_102]
type=auth
auth_type=userpass
username=T11_102
password=REDACTED

[T11_102](p1-aor)
type=aor
max_contacts=1

[T11_105_1](p12)
type=endpoint
auth=authT11_105_1
identify_by=username,auth_username
outbound_auth=authT11_105_1
aors=T11_105_1
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T11_105_1
set_var=CHANNEL(parkinglot)=parking-11
subscribe_context=T11_extension-hints
language=en
moh_suggest=default
context=T11_cos-all
mailboxes=105@trimpro-voicemail
device_state_busy_at=0
callerid="Shia Weinstock" <105>

[authT11_105_1]
type=auth
auth_type=userpass
username=T11_105_1
password=REDACTED

[T11_105_1](p12-aor)
type=aor
max_contacts=1

[T11_107](p1)
type=endpoint
auth=authT11_107
identify_by=username,auth_username
outbound_auth=authT11_107
aors=T11_107
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T11_107
set_var=CHANNEL(parkinglot)=parking-11
subscribe_context=T11_extension-hints
language=en
moh_suggest=default
context=T11_cos-all
mailboxes=107@trimpro-voicemail
device_state_busy_at=0
callerid="Samuel Stern" <107>

[authT11_107]
type=auth
auth_type=userpass
username=T11_107
password=REDACTED

[T11_107](p1-aor)
type=aor
max_contacts=5


