; *********************************************************************************
; @Date : Sun May 3 21:39:12 GMT 2026
; @Document : pjsip__50-4-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T4_201](p1)
type=endpoint
auth=authT4_201
identify_by=username,auth_username
outbound_auth=authT4_201
aors=T4_201
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T4_201
set_var=CHANNEL(parkinglot)=parking-4
subscribe_context=T4_extension-hints
language=en
moh_suggest=default
context=T4_cos-all
mailboxes=201@addb_builders-voicemail
device_state_busy_at=0
callerid="Yisrael Brach" <201>

[authT4_201]
type=auth
auth_type=userpass
username=T4_201
password=REDACTED

[T4_201](p1-aor)
type=aor
max_contacts=5

[T4_202](p1)
type=endpoint
auth=authT4_202
identify_by=username,auth_username
outbound_auth=authT4_202
aors=T4_202
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T4_202
set_var=CHANNEL(parkinglot)=parking-4
subscribe_context=T4_extension-hints
language=en
moh_suggest=default
context=T4_cos-all
mailboxes=202@addb_builders-voicemail
device_state_busy_at=0
callerid="Yossi krous" <202>

[authT4_202]
type=auth
auth_type=userpass
username=T4_202
password=REDACTED

[T4_202](p1-aor)
type=aor
max_contacts=5

[T4_203](p1)
type=endpoint
auth=authT4_203
identify_by=username,auth_username
outbound_auth=authT4_203
aors=T4_203
deny=0.0.0.0/0
contact_deny=0.0.0.0/0
permit=0.0.0.0/0
contact_permit=0.0.0.0/0
dtmf_mode=rfc4733
message_context=messages
set_var=DEVICENAME=T4_203
set_var=CHANNEL(parkinglot)=parking-4
subscribe_context=T4_extension-hints
language=en
moh_suggest=default
context=T4_cos-all
mailboxes=203@addb_builders-voicemail
device_state_busy_at=0
callerid="Fishy Teller" <203>

[authT4_203]
type=auth
auth_type=userpass
username=T4_203
password=REDACTED

[T4_203](p1-aor)
type=aor
max_contacts=5


