; *********************************************************************************
; @Date : Sun May 3 21:39:04 GMT 2026
; @Document : pjsip__20-transport.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

; UDP (Default)
[transport-udp-3baa003c2d301de89c68]
type=transport
protocol=udp
local_net=127.0.0.1/8
local_net=209.145.60.79/20
bind=0.0.0.0:5060
external_media_address=209.145.60.79
external_signaling_address=209.145.60.79
allow_reload=no
symmetric_transport=no

; TCP (Default)
[transport-tcp-37eda84c495b784c1dd0]
type=transport
protocol=tcp
local_net=127.0.0.1/8
local_net=209.145.60.79/20
bind=0.0.0.0:5060
external_media_address=209.145.60.79
external_signaling_address=209.145.60.79
allow_reload=no
symmetric_transport=no

; TLS (Default)
[transport-tls-608c7bb6130ab9815fbe]
type=transport
protocol=tls
verify_client=no
verify_server=no
allow_wildcard_certs=no
method=tlsv1_2
ca_list_path=/etc/ssl/certs
local_net=127.0.0.1/8
local_net=209.145.60.79/20
bind=0.0.0.0:5061
external_media_address=209.145.60.79
external_signaling_address=209.145.60.79
allow_reload=no
symmetric_transport=no

; WS (Default)
[transport-ws-4a22e66ed2320d0b84e8]
type=transport
protocol=ws
local_net=127.0.0.1/8
local_net=209.145.60.79/20
bind=0.0.0.0:5060
external_media_address=209.145.60.79
external_signaling_address=209.145.60.79
allow_reload=no
symmetric_transport=no

; WSS (Default)
[transport-wss-eb7e9c0a1b729f563090]
type=transport
protocol=wss
local_net=127.0.0.1/8
local_net=209.145.60.79/20
bind=0.0.0.0:5060
external_media_address=209.145.60.79
external_signaling_address=209.145.60.79
allow_reload=no
symmetric_transport=no

; TLS + MS Teams (Default)
[transport-tls-ms-teams-bef5de028ca2dda67de6]
type=transport
protocol=tls
verify_client=no
verify_server=no
allow_wildcard_certs=no
method=tlsv1_2
ca_list_path=/etc/ssl/certs
local_net=127.0.0.1/8
local_net=209.145.60.79/20
bind=0.0.0.0:5061
external_media_address=209.145.60.79
external_signaling_address=209.145.60.79
allow_reload=no
symmetric_transport=no

; transport-t7-tmobile-tcp (Custom)
[transport-tcp-fd04c5b4a5136cbc6a47]
type=transport
protocol=tcp
bind=0.0.0.0:5070
allow_reload=yes
symmetric_transport=no

