; *********************************************************************************
; @Date : Wed May 20 16:26:23 GMT 2026
; @Document : queues__50-8-main.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[T8_Q750]
periodic-announce=vpbx/qc-instructions
context=QUEUE-CALLBACK-IVR-1
setqueueentryvar=yes
setqueuevar=yes
timeoutpriority=app
strategy=ringall
musicclass=default
autofill=yes
maxlen=0
announce=
wrapuptime=0
announce-frequency=30
announce-round-seconds=0
announce-to-first-user=no
announce-position=yes
relative-periodic-announce=yes
announce-holdtime=no
autopause=no
ringinuse=yes
timeoutrestart=no
joinempty=yes
timeout=30
leavewhenempty=no
retry=5
member=>Local/101@T8_queue-call-to-agents/n,0,101,hint:Agent101@T8_extension-hints,yes
member=>Local/102@T8_queue-call-to-agents/n,0,102,hint:Agent102@T8_extension-hints,yes
member=>Local/108@T8_queue-call-to-agents/n,0,108,hint:Agent108@T8_extension-hints,yes
queue-thankyou=

[T8_Q751]
setqueueentryvar=yes
setqueuevar=yes
timeoutpriority=app
strategy=linear
musicclass=default
autofill=yes
maxlen=0
announce=
wrapuptime=0
announce-frequency=30
announce-round-seconds=0
announce-to-first-user=no
announce-position=yes
relative-periodic-announce=yes
announce-holdtime=yes
autopause=no
ringinuse=yes
timeoutrestart=no
joinempty=yes
timeout=15
leavewhenempty=no
retry=5
member=>Local/102@T8_queue-call-to-agents/n,0,102,hint:Agent102@T8_extension-hints,yes
member=>Local/108@T8_queue-call-to-agents/n,0,108,hint:Agent108@T8_extension-hints,yes
member=>Local/101@T8_queue-call-to-agents/n,0,101,hint:Agent101@T8_extension-hints,yes
queue-thankyou=

[T8_Q752]
setqueueentryvar=yes
setqueuevar=yes
timeoutpriority=app
strategy=ringall
musicclass=default
autofill=yes
maxlen=0
announce=
wrapuptime=0
announce-round-seconds=0
announce-to-first-user=no
announce-position=no
relative-periodic-announce=yes
announce-holdtime=no
autopause=no
ringinuse=yes
timeoutrestart=no
joinempty=yes
timeout=15
leavewhenempty=no
retry=5
member=>Local/104@T8_queue-call-to-agents/n,0,104,hint:Agent104@T8_extension-hints,yes
member=>Local/105@T8_queue-call-to-agents/n,0,105,hint:Agent105@T8_extension-hints,yes
member=>Local/106@T8_queue-call-to-agents/n,0,106,hint:Agent106@T8_extension-hints,yes
queue-thankyou=

