; *********************************************************************************
; @Date : Sun May 3 21:39:31 GMT 2026
; @Document : queues__50-14-main.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


