; *********************************************************************************
; @Date : Wed Jun 3 1:01:36 GMT 2026
; @Document : queues__50-32-main.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


