; *********************************************************************************
; @Date : Thu May 21 16:43:10 GMT 2026
; @Document : res_parking__50-28-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[parking-28]
parkext=>700
context=>parking-28-parkedcalls
comebackcontext=parking-28-callback
courtesytone=beep
parkpos=>701-710
parkedmusicclass=ringback
parkingtime=>45
comebackdialtime=20
parkedplay=caller
parkedcalltransfers=no
parkedcallreparking=no
parkedcallhangup=no
findslot=>first
comebacktoorigin=no
parkext_exclusive=yes

