; *********************************************************************************
; @Date : Thu May 21 16:43:28 GMT 2026
; @Document : res_parking__50-29-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[parking-29]
parkext=>700
context=>parking-29-parkedcalls
comebackcontext=parking-29-callback
courtesytone=beep
parkpos=>701-710
parkedmusicclass=ringback
parkingtime=>45
comebackdialtime=20
parkedplay=caller
parkedcalltransfers=no
parkedcallreparking=no
parkedcallhangup=no
findslot=>first
comebacktoorigin=no
parkext_exclusive=yes

