; *********************************************************************************
; @Date : Sun May 3 21:39:37 GMT 2026
; @Document : res_parking__50-21-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[parking-21]
parkext=>700
context=>parking-21-parkedcalls
comebackcontext=parking-21-callback
courtesytone=beep
parkpos=>701-710
parkedmusicclass=ringback
parkingtime=>45
comebackdialtime=20
parkedplay=caller
parkedcalltransfers=no
parkedcallreparking=no
parkedcallhangup=no
findslot=>first
comebacktoorigin=no
parkext_exclusive=yes

