; *********************************************************************************
; @Date : Sun May 3 21:39:29 GMT 2026
; @Document : res_parking__50-11-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[parking-11]
parkext=>700
context=>parking-11-parkedcalls
comebackcontext=parking-11-callback
courtesytone=beep
parkpos=>701-710
parkedmusicclass=ringback
parkingtime=>45
comebackdialtime=20
parkedplay=caller
parkedcalltransfers=no
parkedcallreparking=no
parkedcallhangup=no
findslot=>first
comebacktoorigin=no
parkext_exclusive=yes

