; *********************************************************************************
; @Date : Sun May 3 21:39:04 GMT 2026
; @Document : rtp__10-general.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general]
icesupport=yes
rtpchecksums=no
rtpend=20000
rtpstart=10000
strictrtp=no
