; *********************************************************************************
; @Date : Sun May 3 21:39:12 GMT 2026
; @Document : sip__50-4-trunks.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

