; *********************************************************************************
; @Date : Tue May 19 7:26:26 GMT 2026
; @Document : sip__50-11-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


