; *********************************************************************************
; @Date : Thu May 21 16:43:10 GMT 2026
; @Document : sip__50-28-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


