; *********************************************************************************
; @Date : Sun May 3 21:39:44 GMT 2026
; @Document : sip__50-26-trunks.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

