; *********************************************************************************
; @Date : Sun May 3 21:39:29 GMT 2026
; @Document : sip__50-11-trunks.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

