; *********************************************************************************
; @Date : Thu May 28 5:47:38 GMT 2026
; @Document : sip__10-general.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general]
context=sip-default
rtcachefriends=yes
udpbindaddr=0.0.0.0:5062
tcpbindaddr=0.0.0.0:5062
tlsbindaddr=0.0.0.0:5063
tlscipher=ALL
tlsclientmethod=tlsv1
accept_outofcall_message=yes
allow=!all,ulaw,alaw,g729
allowguest=no
allowtransfer=yes
alwaysauthreject=yes
authfailureevents=no
autoframing=no
defaultexpiry=120
dumphistory=no
dynamic_exclude_static=no
faxdetect=no
g726nonstandard=no
jbenabled=no
jbforce=no
jbimpl=fixed
language=en
maxcallbitrate=384
maxexpiry=3600
minexpiry=60
notifycid=no
notifyhold=no
notifyringing=yes
preferred_codec_only=no
recordhistory=no
rtpholdtimeout=300
rtptimeout=30
sipdebug=no
srvlookup=yes
tonezone=us
tos_audio=ef
tos_sip=cs3
tos_video=af41
videosupport=no
nat=no
websocket_enabled=no
autodomain=no
allowexternaldomains=yes
tlscertfile=/usr/share/vitalpbx/certificates/m.connectcomunications.com/bundle.pem
tlscafile=/usr/share/vitalpbx/certificates/m.connectcomunications.com/chain.pem
tcpenable=no
tlsenable=no
tlsdontverifyserver=no
useragent=Connect
register_attempts=0
contact_user=17778620916102
context=from-pstn
callcounter=yes
tos_text=af41
cos_sip=3
cos_audio=5
cos_video=4
cos_text=3
recordonfeature=one_touch_rec
recordofffeature=one_touch_rec
vmexten=*97
outofcall_message_context=messages
auth_message_requests=no
transport=udp
websocket_enabled=false
