; *********************************************************************************
; @Date : Wed Jun 3 0:56:31 GMT 2026
; @Document : sip__50-31-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


