; *********************************************************************************
; @Date : Sun May 3 21:39:22 GMT 2026
; @Document : sip__50-8-trunks.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

