; *********************************************************************************
; @Date : Fri May 29 15:01:52 GMT 2026
; @Document : sip__20-30-registers.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general](+)
