; *********************************************************************************
; @Date : Thu May 14 15:12:17 GMT 2026
; @Document : sip__20-3-registers.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general](+)
