; *********************************************************************************
; @Date : Sun May 3 21:39:39 GMT 2026
; @Document : sip__50-24-extensions.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


