; *********************************************************************************
; @Date : Sun May 3 21:39:33 GMT 2026
; @Document : sip__20-18-registers.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general](+)
