; *********************************************************************************
; @Date : Sun May 3 21:39:40 GMT 2026
; @Document : sip__20-24-registers.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general](+)
