; *********************************************************************************
; @Date : Sun May 3 21:39:26 GMT 2026
; @Document : sip__50-10-trunks.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

