; *********************************************************************************
; @Date : Wed May 27 4:41:10 GMT 2026
; @Document : sip__20-1-registers.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general](+)
