; *********************************************************************************
; @Date : Thu May 28 5:47:38 GMT 2026
; @Document : sip__40-1-profiles.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

;Default SIP Profile - Default SIP Profile
[p11](!)
host = dynamic
trustrpid = yes
sendrpid = yes
type = friend
qualify = 2000
qualifyfreq = 60
transport = udp
avpf = no
directmedia = nonat
icesupport = no
encryption = no
dtlsenable = no
dtlsverify = no
dtlssetup = actpass
dtlsfingerprint = sha-256
dtlsrekey = 0
force_avp = no
rtcp_mux = no
