[reboot-aastra]
Event => check-sync

[reboot-cisco]
Event => check-sync

[reboot-fanvil]
Event => check-sync

[reboot-grandstream]
Event => reboot, Content-Length => 0

[reboot-linksys]
Event => reboot_now

[reboot-polycom]
Event => check-sync

[reboot-sipura]
Event => resync

[reboot-snom]
Event => check-sync\;reboot=true

[reboot-spa]
Event => reboot

[reboot-vtech]
Event => check-sync

[reboot-yealink]
Event => check-sync\;reboot=true

[reboot-xorcom]
Event => check-sync\;reboot=true

[reboot-htek]
Event => check-sync;check-sync;reboot=false;check-sync;reboot=true;reboot

[reboot-d-link]
Event => check-sync
