; *********************************************************************************
; @Date : Sun May 3 21:39:04 GMT 2026
; @Document : voicemail__20-zonemessages.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[zonemessages]
eastern=America/New_York|'vm-received' Q 'digits/at' IMp
central=America/Chicago|'vm-received' Q 'digits/at' IMp
central24=America/Chicago|'vm-received' q 'digits/at' H N 'hours'
european=Europe/Copenhagen|'vm-received' a d b 'digits/at' HM
