; *********************************************************************************
; @Date : Sun May 3 21:39:26 GMT 2026
; @Document : voicemail__50-10-main.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[comfort_control-voicemail]
101 => 101,Ari Schonbrun,Ari@comfortctrl.com,,attach=yes|saycid=yes|sayduration=yes|envelope=yes|delete=no|hidefromdir=no|operator=no|emailbody=category:${VM_CATEGORY}\nvm_name:${VM_NAME}\nduration:${VM_DUR}\nmsg_num:${VM_MSGNUM}\ncid:${VM_CALLERID}\ncid_name:${VM_CIDNAME}\ncid_num:${VM_CIDNUM}\ndate:${VM_DATE}\nmsg_file:${VM_MESSAGEFILE}\ntenant:ab6beaa898dd9618\nextension:101\nmailbox:${VM_MAILBOX}
