; *********************************************************************************
; @Date : Sun May 3 21:39:39 GMT 2026
; @Document : voicemail__50-24-main.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************


