; *********************************************************************************
; @Date : Sun May 3 21:39:04 GMT 2026
; @Document : voicemail__10-general.conf
; @Author : VitalPBX
; @Platform : VitalPBX
; *********************************************************************************

[general]
attachfmt=wav
format=wav
maxsecs=400
maxgreet=60
maxsilence=10
maxlogins=3
moveheard=yes
backupdeleted=100
forcename=no
usedirectory=yes
review=yes
attach=no
forcegreetings=no
maxmsg=9999
locale=en_GB.utf8
emaildateformat=%A, %B %d %Y, %R
mailcmd=/usr/share/vitalpbx/scripts/voicemail2email
fromstring=Connect
serveremail=support@connectcomunications.com
emailbody=Dummy
emailsubject=New Voicemail Message from ${VM_CALLERID}
externpass=/bin/true
charset=UTF-8
searchcontexts=no
