/**
 * Zero-touch desk phone setup — the rules, with nothing that talks to a network.
 *
 * ⛔ Everything here is a pure function. The reason is that these decisions —
 * may this phone be wiped, which colleague gets which button, what is the customer
 * told — are the ones that must be testable without a phone, a PBX or a customer.
 */
export * from "./standards";
export * from "./buttonLayout";
export * from "./states";
export * from "./deviceIdentity";
export * from "./escalation";
export * from "./discoveryFilter";
export * from "./deviceKinds";
export * from "./provisioningRecord";
export * from "./retry";
export * from "./resetSafety";

/**
 * The PBX's own provisioning catalogue (generated) and the per-brand adapters built on it.
 *
 * The catalogue is regenerated by scripts/deskPhoneSetup/gen-vendor-catalog.py and must never
 * be edited by hand; the adapters are hand-written and every claim in them carries a source.
 */
export * from "./vendorCatalog.generated";
export * from "./vendorAdapters";
