#!/usr/bin/env bash
set -euo pipefail

# ── DEPRECATED ──────────────────────────────────────────────────────────────
# This is the original tenant-T25-only installer. It is preserved for
# emergency rollback ONLY. For new installs use the universal version:
#
#     scripts/pbx/install-connect-wake-dialplan.sh
#
# The universal script wires push-wake into the Connect option/exit routers
# and direct-dial path so EVERY tenant + EVERY extension dial is covered
# without per-tenant dialplan edits. It also publishes the AstDB keys the
# new wrapper reads.
# ────────────────────────────────────────────────────────────────────────────
#
# Install the Connect Push-Wake (Option 2) dialplan on a VitalPBX host for
# tenant T25. See docs/pbx/connect-push-wake-T25.md for full context.
#
# Run on the PBX host as root (or with sudo).
#
# Required env:
#   CONNECT_API_BASE      e.g. https://app.connectcomunications.com/api
#   CONNECT_CDR_SECRET    paste from /opt/connectcomms/env/api.env on Connect prod
#   T25_VITAL_TENANT      defaults to "T25" — only override if the dialplan
#                         globals refer to T25 by a different identifier.
#
# Optional:
#   CONNECT_WAIT_SECONDS  defaults to 6; increase to 8 if S25 is still flaky
#   DRY_RUN=1             prints what would change but doesn't write

if [[ "${EUID}" -ne 0 ]]; then
  echo "ERROR: run as root on the VitalPBX host" >&2
  exit 1
fi

: "${CONNECT_API_BASE:?set CONNECT_API_BASE (e.g. https://app.connectcomunications.com/api)}"
# CONNECT_CDR_SECRET is optional. If empty (or unset), the API endpoint runs
# in "warn and allow" mode — fine for the pilot. Set this to the value of
# CDR_INGEST_SECRET on the Connect API container if/when that secret is
# configured for proper auth.
CONNECT_CDR_SECRET="${CONNECT_CDR_SECRET:-}"
T25_VITAL_TENANT="${T25_VITAL_TENANT:-T25}"
CONNECT_WAIT_SECONDS="${CONNECT_WAIT_SECONDS:-6}"
DRY_RUN="${DRY_RUN:-0}"

ASTERISK_DIR="/etc/asterisk"
CUSTOM_FILE="${ASTERISK_DIR}/extensions__95-connect-push-wake.conf"
GLOBALS_FILE="${ASTERISK_DIR}/extensions_custom.conf"

if [[ ! -d "${ASTERISK_DIR}" ]]; then
  echo "ERROR: ${ASTERISK_DIR} not found — is this a VitalPBX host?" >&2
  exit 1
fi

if ! command -v curl >/dev/null 2>&1; then
  echo "ERROR: curl required (used by the dialplan macro at runtime)" >&2
  exit 1
fi

# Quick reachability test to give a clear error before we touch anything.
echo "[*] Testing reachability of ${CONNECT_API_BASE}/health …"
if curl --silent --show-error --max-time 5 "${CONNECT_API_BASE%/}/health" | grep -q '"ok":true'; then
  echo "    OK"
else
  echo "    WARN: health endpoint did not return ok=true. Push-wake will not work until the PBX can reach Connect."
  echo "          Continuing — you can re-test after fixing egress."
fi

NEW_FILE=$(mktemp)
cat >"${NEW_FILE}" <<EOF
; ────────────────────────────────────────────────────────────────────────────
; Connect Push-Wake (Option 2) — generated by scripts/pbx/install-t25-push-wake.sh
; Tenant: ${T25_VITAL_TENANT}
; Connect API: ${CONNECT_API_BASE}
; Wait: ${CONNECT_WAIT_SECONDS}s
;
; DO NOT EDIT BY HAND. Re-run the installer to regenerate.
; ────────────────────────────────────────────────────────────────────────────

[macro-connect-push-wake]
exten => s,1,NoOp(== Connect Push-Wake start ext=\${ARG1} call=\${LINKEDID} ==)
 same =>   n,Set(__CONNECT_WAKE_FROM=\${IF($["\${CALLERID(num)}" != ""]?\${CALLERID(num)}:unknown)})
 same =>   n,Set(__CONNECT_WAKE_DISPLAY=\${IF($["\${CALLERID(name)}" != ""]?\${CALLERID(name)}:\${CALLERID(num)})})
 same =>   n,Set(__CONNECT_WAKE_PAYLOAD=\\{\\"pbxCallId\\":\\"\${LINKEDID}\\",\\"pbxVitalTenantId\\":\\"${T25_VITAL_TENANT}\\",\\"extensionNumber\\":\\"\${ARG1}\\",\\"fromNumber\\":\\"\${CONNECT_WAKE_FROM}\\",\\"fromDisplay\\":\\"\${CONNECT_WAKE_DISPLAY}\\"\\})
 same =>   n,NoOp(Wake payload: \${CONNECT_WAKE_PAYLOAD})
 same =>   n,Set(CONNECT_WAKE_RESP=\${SHELL(curl --silent --show-error --max-time 3 -X POST '${CONNECT_API_BASE%/}/internal/pbx/wake-extension' -H 'content-type: application/json' -H 'x-cdr-secret: ${CONNECT_CDR_SECRET}' -d '\${CONNECT_WAKE_PAYLOAD}' 2>&1)})
 same =>   n,NoOp(Wake response: \${CONNECT_WAKE_RESP})
 same =>   n,Wait(${CONNECT_WAIT_SECONDS})
 same =>   n,NoOp(== Connect Push-Wake end ext=\${ARG1} call=\${LINKEDID} ==)
 same =>   n,MacroExit()

[T25_push_wake_extension]
exten => _X!,1,NoOp(== T25 push-wake exten=\${EXTEN} ==)
 same =>     n,Macro(connect-push-wake,\${EXTEN})
 same =>     n,Set(__CONNECT_TARGET=PJSIP/\${EXTEN}_1)
 same =>     n,Dial(\${CONNECT_TARGET},30,Tt)
 same =>     n,NoOp(Dial finished status=\${DIALSTATUS})
 same =>     n,GotoIf($["\${DIALSTATUS}"="ANSWER"]?hangup)
 same =>     n(vm),Goto(sub-leave-vm,\${EXTEN}_1,1)
 same =>     n(hangup),Hangup()
EOF

if [[ "${DRY_RUN}" == "1" ]]; then
  echo "[DRY_RUN] would write the following to ${CUSTOM_FILE}:"
  echo "─────────────────────────────────────────────────────"
  cat "${NEW_FILE}"
  echo "─────────────────────────────────────────────────────"
  rm -f "${NEW_FILE}"
  exit 0
fi

if [[ -f "${CUSTOM_FILE}" ]]; then
  cp -a "${CUSTOM_FILE}" "${CUSTOM_FILE}.bak.$(date -u +%Y%m%dT%H%M%SZ)"
  echo "[*] Backed up existing ${CUSTOM_FILE}"
fi

install -m 0644 -o root -g root "${NEW_FILE}" "${CUSTOM_FILE}"
rm -f "${NEW_FILE}"
echo "[*] Installed dialplan: ${CUSTOM_FILE}"

# VitalPBX picks up files matching extensions__*.conf automatically. Reload
# to make sure the dialplan is active.
asterisk -rx "dialplan reload" || {
  echo "WARN: 'asterisk -rx dialplan reload' failed — try via the GUI 'Apply Changes' instead." >&2
}

echo
echo "DONE. Next steps:"
echo "  1) In the VitalPBX GUI, point T25's inbound route(s) for the target"
echo "     extension(s) to 'Custom Application': Goto(T25_push_wake_extension,<ext>,1)"
echo "  2) Place a test call. Watch:"
echo "       asterisk -rvvv     # PBX side"
echo "       Mobile app → Settings → Diagnostics → Call Wake — Timeline"
echo "  3) If Samsung S25 still falls through to voicemail, re-run with"
echo "     CONNECT_WAIT_SECONDS=8 (or 10) and reload."
