// Generated by scripts/browser-companion/schema.mjs --write; do not edit.
export function safeUrl(input) {
    if (typeof input !== "string" || input.length > 4096)
        throw Error("invalid_url");
    const u = new URL(input);
    if (!["https:", "http:"].includes(u.protocol) || u.username || u.password)
        throw Error("unsafe_url");
    return u.href;
}
export const COMMANDS = ["tabs", "open", "read", "act", "download", "upload", "screenshot", "wait", "close"];
/** Reject unknown fields rather than silently forwarding arbitrary browser capabilities. */
export function validateArgs(command, args) {
    const fields = {
        tabs: [], open: ["url"], read: ["tabId", "query", "offset", "limit"],
        act: ["tabId", "action", "ref", "value", "checked", "x", "y"], download: ["tabId", "ref"],
        upload: ["tabId", "ref", "path"], screenshot: ["tabId"], wait: ["tabId", "text", "timeoutMs"], close: ["tabId"],
    };
    if (!Object.hasOwn(fields, command) || !args || Array.isArray(args) || typeof args !== "object")
        throw Error("invalid_command");
    for (const [k, v] of Object.entries(args)) {
        if (!fields[command].includes(k))
            throw Error(`unexpected_field:${k}`);
        if (typeof v === "string" && v.length > 8192)
            throw Error(`field_too_long:${k}`);
        if (typeof v !== "string" && typeof v !== "number" && typeof v !== "boolean")
            throw Error(`invalid_field:${k}`);
        if (["url", "query", "action", "ref", "value", "path", "text"].includes(k) && typeof v !== "string")
            throw Error(`invalid_string:${k}`);
        if (k === "checked" && typeof v !== "boolean")
            throw Error("invalid_boolean:checked");
        if (["tabId", "offset", "limit", "timeoutMs", "x", "y"].includes(k) && !Number.isSafeInteger(v))
            throw Error(`invalid_number:${k}`);
    }
    if (command !== "tabs" && command !== "open" && (!Number.isSafeInteger(args.tabId) || Number(args.tabId) < 1))
        throw Error("tab_id_required");
    if (command === "open")
        safeUrl(args.url);
    const range = (key, min, max) => { if (args[key] !== undefined && (Number(args[key]) < min || Number(args[key]) > max))
        throw Error(`out_of_range:${key}`); };
    range("tabId", 1, 2147483647);
    range("offset", 0, 1000000);
    range("limit", 1, 200);
    range("timeoutMs", 1, 30000);
    range("x", -2000, 2000);
    range("y", -2000, 2000);
    if (typeof args.query === "string" && args.query.length > 200)
        throw Error("query_too_long");
    if (command === "act") {
        if (!["click", "fill", "select", "check", "scroll", "hover", "focus", "submit"].includes(String(args.action)))
            throw Error("invalid_action");
        const actionFields = { click: ["ref"], fill: ["ref", "value"], select: ["ref", "value"], check: ["ref", "checked"], scroll: ["x", "y"], hover: ["ref"], focus: ["ref"], submit: ["ref"] };
        for (const key of Object.keys(args))
            if (!["tabId", "action", ...actionFields[String(args.action)]].includes(key))
                throw Error(`unexpected_action_field:${key}`);
        if (["fill", "select"].includes(String(args.action)) && typeof args.value !== "string")
            throw Error("value_required");
        if (args.action === "check" && typeof args.checked !== "boolean")
            throw Error("checked_required");
        if (args.action === "scroll" && args.x === undefined && args.y === undefined)
            throw Error("scroll_delta_required");
    }
    if (["upload", "download"].includes(command) || (command === "act" && args.action !== "scroll")) {
        if (typeof args.ref !== "string" || !args.ref.trim() || args.ref.length > 120)
            throw Error("element_ref_required");
    }
    if (command === "upload" && (typeof args.path !== "string" || !args.path.trim() || args.path.includes("\0")))
        throw Error("file_required");
    if (command === "wait" && (typeof args.text !== "string" || !args.text.trim() || args.text.length > 2000))
        throw Error("wait_text_required");
}
